### ISSUE TITLE
must have one register DataBase alias named default

### ISSUE THREAD

**Issue by gyjx** [lifei6671/mindoc#100]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.6

2. 你当前使用的是什么操作系统?
linux centos6.9 64

3. 你是如何操作的？
./mindoc_linux_amd64 install

4. 你期望得到什么结果?
5. 当前遇到的是什么结果?
[ORM]2017/07/15 00:21:20 register db Ping `default`, Error 1862: Your password has expired. To log in you must change it using a client that supports expired passwords.
Initializing...
must have one register DataBase alias named `default`
环境变量配置如下
export GOROOT=/usr/local/go
export GOBIN=$GOROOT/bin
export GOPKG=$GOROOT/pkg/tool/linux_amd64
export GOARCH=amd64
export GOOS=linux
export GOPATH=/usr/local/golang
export ZONEINFO=/usr/local/mindoc/lib/time/zoneinfo.zip
export PATH=$PATH:$GOBIN:$GOPKG:$GOPATH/bin

**Comment by lifei6671** [comment]
你的数据库密码不支持客户端链接。

**Comment by miaomiaoguoke** [comment]
这个是说密码过期了吧。
