### ISSUE TITLE
VERSION BUILD_TIME 的值是在哪什么时候赋值的啊

### ISSUE THREAD

**Issue by arashicage** [lifei6671/mindoc#101]
在看你代码，没看明白 https://github.com/lifei6671/mindoc/blob/master/conf/enumerate.go 的
var (
	VERSION    string
	BUILD_TIME string
	GO_VERSION string
) 都是在哪被赋值的，翻遍了源码没找到啊。

下载的二进制 
mindoc version 输出
MinDoc current version =>  v0.6
MinDoc last version =>  v0.6

自己编译的
mindoc version 输出
MinDoc current version =>  
MinDoc last version =>  v0.6

还有能不能提供markdown 导出功能？

**Comment by lifei6671** [comment]
这几个值是编译时赋值的，具体可看根目录的.travis.yml文件和appveyor.yml文件的编译命令。

Markdown导出功能暂时没计划开发。
