### ISSUE TITLE
项目与项目交互

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#104]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
6.0

2. 你当前使用的是什么操作系统?
win

3. 你是如何操作的？
比如项目A和项目B需要某个说明文件项目穿插交互如何实现，目前我在项目A做了一个文章，发现和项目B有交集（或者项目A文章需要移动到项目B里面去），这种从新编辑很麻烦。已经做好了。素材也删除了。

4. 你期望得到什么结果?
项目与项目之间的文章可以相互交换也就是项目A里面的东西移动到项目B里面去。

5. 当前遇到的是什么结果?
无法实现。

**Comment by lifei6671** [comment]
暂时不支持项目之间的互通。

**Comment by gdlaoqiang** [comment]
考虑下
