### ISSUE TITLE
在HTML编辑器编辑时候文字多了之后出现颜色变更这些显示不全了。

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#105]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?
win

3. 你是如何操作的？
看下图

4. 你期望得到什么结果?

改变颜色背胶色应该不会出现这样结果的
5. 当前遇到的是什么结果?
正常编辑应该如下图
![image](https://user-images.githubusercontent.com/28562551/28821858-b37b3e30-76e9-11e7-9a75-5fb9b2673731.png)
文字 多了一只就出现
![image](https://user-images.githubusercontent.com/28562551/28821887-ca280b90-76e9-11e7-8c6a-f285506bec80.png)

**Comment by lifei6671** [comment]
不好意思不明白你说的具体是什么结果？

**Comment by gdlaoqiang** [comment]
下图颜色是不是看不到最上的那排了？

**Comment by gdlaoqiang** [comment]
![image](https://user-images.githubusercontent.com/28562551/28923036-1a33ac24-788f-11e7-89ee-c24436609cbc.png)

**Comment by lifei6671** [comment]
0.7版本已重写富文本编辑器。
