### ISSUE TITLE
创建docker容器时，如何挂接数据卷？

### ISSUE THREAD

**Issue by zhangfisher** [lifei6671/mindoc#108]
在ubuntu下使用docker安装时，可以指定mysql参数，请教一下，是否可以
指定一个数据卷用来存储配置或者upload数据？

比如
docker run xxxx    -v myuploads:/xxxx/

将上传的文件或配置文件等存储在数据卷？
这样才能方便进行上传数据的管理。

**Comment by lifei6671** [comment]
建议你搜索一下docker命令。
MinDoc的上传目录位于/uploads中。
