### ISSUE TITLE
linux下可以给一个官方的安装流程吗？

### ISSUE THREAD

**Issue by elinxer** [lifei6671/mindoc#109]
## 目前是go语言的刚学习的phper
希望学习golang，在使用mindoc的是感觉是非常好的，不过问题是公司的使用必然导致要有公司自己开发的功能，这也是一个学习的契机。希望官方给一个linux下一个完整的安装流程，我使用golang glide安装的时候各种错误。。。

**Comment by lifei6671** [comment]
去wiki中看。
