### ISSUE TITLE
docker安装后找不到“添加项目”的按钮

### ISSUE THREAD

**Issue by zhangfisher** [lifei6671/mindoc#110]
使用最新的docker安装，已经成功了，也可以访问，但是找不到“添加项目”的按钮，也无法添加用户，好象整个应用就是只读的一样，我看官方的例子是有的？？？

docker run -p 8181:8181 --name  mindoc -v /uploads:/uploads -e MYSQL_PORT_3306_TCP_ADDR=172.17.0.2 -e MYSQL_PORT_3306_TCP_PORT=3306 -e MYSQL_INSTANCE_NAME=rdcenter_mindoc -e MYSQL_USERNAME=root -e MYSQL_PASSWORD=123456 -e httpport=8181 -d harryhan1989/m

####
也就是说上方的“添加项目、用户”的功能，我看了一下CSS，由于搜索框在我的电脑上被自动调节到第二行，导致工具栏被上方的DIV盖住了，应该是CSS兼容性的问题。我用的chrome和360极速浏览器。

但是在访问官网的DEMO则没有问题。

**Comment by lifei6671** [comment]
请将网站题目设置的短一些。
