### ISSUE TITLE
安装docker镜像后，导出PDF时出错

### ISSUE THREAD

**Issue by zhangfisher** [lifei6671/mindoc#111]
操作系统：ubuntu
docker image:

安装后在生成PDF时出错，提示HTTP 500 ： 服务器异常

查看docker logs 发现：
[E] [document.go:822] fork/exec D:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe: no such file or directory

**Comment by lifei6671** [comment]
请看文档PDF导出配置。

**Comment by zhangfisher** [comment]
安装wkhtmltopdf在docker容器里面不能运行，容器基础镜像是Alpine，不知道是否跟此有关。

**Comment by lifei6671** [comment]
这个有可能，你去wkhtmltopdf官网上看看能在alpine下运行不。

**Comment by zhangfisher** [comment]
wkhtmltopdf在ubuntu和cenos均是可以运行的，但我在
Alpinep容器里面死活跑不起来，而golang的镜像没好象有基于ubuntu和cenos

**Comment by lifei6671** [comment]
可以自己编译个golang镜像

**Comment by xsplus** [comment]
请问楼主，在使用官方的docker镜像（基础镜像是Alpine）后配置wkhtmltopdf的问题解决了吗？这边遇到了和你一样的问题。

**Comment by zhangfisher** [comment]
使用Ubuntu自己作镜像
