### ISSUE TITLE
linux 和mac 都试了 报错一样

### ISSUE THREAD

**Issue by hanwenbo** [lifei6671/mindoc#113]
[ERROR]	Update failed for golang.org/x/image/font: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/image/math/fixed
[ERROR]	Update failed for golang.org/x/image/math/fixed: Cannot detect VCS

**Comment by lifei6671** [comment]
请自备梯子。

**Comment by hanwenbo** [comment]
李飞  我有梯子  目前用的蓝灯 你呢？
