### ISSUE TITLE
must have one register DataBase alias named `default`   BUG

### ISSUE THREAD

**Issue by hanwenbo** [lifei6671/mindoc#114]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

最后一个版本
2. 你当前使用的是什么操作系统?
centos 7

3. 你是如何操作的？
直接下载按着https://github.com/lifei6671/mindoc/releases教程安装

4. 你期望得到什么结果?

能跑起来
5. 当前遇到的是什么结果?
must have one register DataBase alias named `default`
没学过go的表示一头雾水  一直装不上 但又想用

**Comment by hanwenbo** [comment]
李飞 你mysql文件放哪了 releases版本里

**Comment by lifei6671** [comment]
这个问题一般是你配置的数据库信息不对。
mindoc是code first模式。没有数据库文件，

**Comment by hanwenbo** [comment]
解决了  是我数据库配置的不对
