### ISSUE TITLE
谷歌浏览器编辑文档时弹出框不能关闭

### ISSUE THREAD

**Issue by qizhijun** [lifei6671/mindoc#115]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. linux centos 7

3. 使用chrome浏览器编辑文档的时候

4. 弹出框可以关闭

5. 无法关闭

**Comment by zhangfisher** [comment]
同上

**Comment by lifei6671** [comment]
是HTML编辑器还是Markdown编辑器？有没有尝试换其他版本的Chrome呢？

**Comment by qizhijun** [comment]
非常感谢，问题已经解决了。因为我用的是触摸屏，是Markdown编辑器的问题，它代码中touchend的事件覆盖了click事件，就是说只要是触摸屏，鼠标点击就不能用。我改了一下，可以用了。
