### ISSUE TITLE
制作好了一个可用完整的Docker镜像

### ISSUE THREAD

**Issue by zhangfisher** [lifei6671/mindoc#116]
官方现有的发布的Docker镜像不支持PDF导出，原因可能是该镜像基于Alpine，
在创建好的容器里安装wkhtmltopdf后不能运行，因此导出PDF时会出错。
因此我做了一个基于ubuntu的镜像，解决了pdf导出的问题。

但是现在程序还有些BUG,在编辑界面好些外对话框弹出后就不能关闭，等作者解决后再发布共享。

**Comment by lifei6671** [comment]
你说的界面对话框不能关闭是Markdown编辑器还是HTML编辑器？

**Comment by zhangfisher** [comment]
Markdown编辑器的插入链接、图片、表格、代码块等有弹出对话框的都不能关闭，也不能插入数据。

**Comment by lifei6671** [comment]
我这边暂时测试没发现这个问题。

**Comment by zhangfisher** [comment]
浏览器：chrome 最新版本
306极速浏览器

**Comment by KarlFreecss** [comment]
我刚刚试了下：
EDGE 和 Firefox可以关闭
Chrome 不能关闭

**Comment by xshow-xs** [comment]
@zhangfisher @lifei6671 在使用mindoc中的dokerfile文件构建镜像时，一直卡在
Step 6/13 : RUN go get -u github.com/golang/dep/cmd/dep && dep ensure &&     CGO_ENABLE=1 go build -v -o mindoc_linux_amd64 -ldflags="-w -X main.VERSION=$TAG -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'" &&         rm -rf commands controllers models modules routers tasks vendor docs search data utils graphics .git Godeps uploads/* .gitignore .travis.yml Dockerfile gide.yaml LICENSE main.go README.md conf/enumerate.go conf/mail.go install.lock
 ---> Running in 8503fb3622f3
停留在这里很长时间，是因为墙的问题么

**Comment by run100** [comment]
dep ensure 这个地方卡死了，怎么解决

**Comment by lifei6671** [comment]
二次开发需要有golang基础，如果对golang不太了解的，请先学习golang，再二次开发mindoc。
