### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zhangfisher** [lifei6671/mindoc#117]
功能上建议：

1、首页的列表能支持多种视图显示，如列表显示等。
   现有的显示方式信息量太少，大部分情况下均只是显示一个默认封面，实在价值有限
2、支持项目分类显示、浏览。
3、支持收藏夹功能
4、支持为单个文档设置密码
5、支持将基于里面的某个文档复制或移至其他 项目
6、增加评论或找错功能支持
7、支持点赞功能
8、增加访问量统计
9、首页对移动端的支持要优化

**Comment by lifei6671** [comment]
你说的这些功能适合对外开放的服务类应用。和看云类似。我的目标是企业内开发手册的管理。
