### ISSUE TITLE
在配置管理里设置过长的文件名，会导致搜索框样式错位，盖住添加其他页面。

### ISSUE THREAD

**Issue by cainiaoDJ** [lifei6671/mindoc#118]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.6

2. 你当前使用的是什么操作系统?
Linux

3. 你是如何操作的？
修改『网站标题』为比较长的文字，会导致搜索条变到第二行。覆盖其他按钮

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
这个问题已经发现了，目前建议不要将网站标题设置的过长。

**Comment by lifei6671** [comment]
0.7版本已修复
