### ISSUE TITLE
建议新功能 简繁体模糊搜索

### ISSUE THREAD

**Issue by naokij** [lifei6671/mindoc#119]
如果团队内部有人用繁体字写作，那么用简体字搜索，就无法搜索出繁体的内容。

比如搜”开通“不会出现”開通“有关的结果。

希望能够有一个选项”简繁体模糊搜索“，开启以后，搜索的时候，自动把关键字转换成繁体或者简体，同时搜索简体与繁体的关键字。

**Comment by lifei6671** [comment]
这个需求太小众了。。

**Comment by naokij** [comment]
可以用go-opencc做简繁转换

https://github.com/stevenyao/go-opencc
