### ISSUE TITLE
pdf导出后，pdf文件中目录顺序没有与系统中文档目录保持一致

### ISSUE THREAD

**Issue by iconan** [lifei6671/mindoc#122]
用的是V0.6版本，期望导出为pdf文件后，pdf文档中API接口目录结构与系统中文档目录结构保持一致；
另外，后续有没有可能加入导出为Word文档功能

**Comment by lifei6671** [comment]
如果你的文档目录没有调整排序，导出顺序是一致的，如果调整了排序就不一致了。这个后面会优化。

**Comment by iconan** [comment]
后续有没有加入导出Word文档功能，我今天刚在公司把这个装上去了，大家反馈还不错。。。。很赞

**Comment by lifei6671** [comment]
导出配置请查看： https://www.iminho.me/wiki/docs/mindoc/mindoc-calibre.md
