### ISSUE TITLE
希望将SESSION认证改为COOKIE+TOKEN的模式

### ISSUE THREAD

**Issue by lxepoo** [lifei6671/mindoc#124]
当前是用的SESSION方式，有个致命问题，一段时间不操作，会弹回登录页面，写东西的时候，可能离开很久，去WC或者去喝茶。回来一操作就变成了登录页面，写的东西容易丢。

随时保存是个好习惯，但是不是每个人都能做到。

**Comment by lifei6671** [comment]
新版本会提示登录。
