### ISSUE TITLE
docker用户部署MINDOC的注意事项

### ISSUE THREAD

**Issue by lxepoo** [lifei6671/mindoc#126]
我自己用dockerfile build了一个镜像到阿里云，镜像仓库：

`registry-vpc.cn-hangzhou.aliyuncs.com/router/mindoc:master`

使用过程中注意几个事项：

1.需要挂数据卷或映射一个数据目录，否则附件在docker容器重启后会丢。

挂载到这个目录：`/go/src/github.com/lifei6671/mindoc/uploads`

2.注意把MYSQL的账号信息写到docker容器的ENV环境变量里。

**Comment by yuwenxing** [comment]
导出功能可以用么？

**Comment by lxepoo** [comment]
不能，有别的用户封装了能用导出的docker，我这个只是为了方便国内用户拉去，dockerfile就是源码里那个。
