### ISSUE TITLE
头像区域的URL处理有问题

### ISSUE THREAD

**Issue by lxepoo** [lifei6671/mindoc#127]
如果是头像字段为：/uploads/201708/attach_14dd33a8f51a8013.png 就可以显示

如果是使用了一个外部图片作为头像，比如在显示时，会显示为
`/http://baidu.com/uploads/201708/attach_14dd33a8f51a8013.png`导头像无法出现，但是会员管理处是正常的。

我的用户是直接数据库导入的，所以不是一个个上传头像的。

不是很要紧，但是您看有空能否优化下。

**Comment by lifei6671** [comment]
建议你将外部头像导入到本地。
下个版本会用cdnimg函数生成图片地址。

**Comment by lxepoo** [comment]
建议还是考虑一下外链头像的可能性。谢谢。

**Comment by lifei6671** [comment]
新版本已支持以http或https开头的头像，至于外链头像，因为头像有尺寸限制，所以这个暂时无法实现。
