### ISSUE TITLE
关于一个小功能的建议

### ISSUE THREAD

**Issue by MrYoungGuofeng** [lifei6671/mindoc#130]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新的版本

2. 你当前使用的是什么操作系统?
Linux

3. 你是如何操作的？
没有操作

4. 你期望得到什么结果?

管理员能不能查看是谁看过or下载过文章的附件。。也就是管理员能不能查看类似log的功能呢？？
5. 当前遇到的是什么结果?
这只是添加一个新功能

**Comment by lifei6671** [comment]
感觉这个功能没什么意义。

**Comment by MrYoungGuofeng** [comment]
嗯，因为这是一个文档管理系统，有些资料被下载是需要被记录的，所以我想问问能否加这个功能的，不过还是谢谢您了～
