### ISSUE TITLE
配置邮件服务后，使用邮件服务时报错 550 5.8.1 Local user only

### ISSUE THREAD

**Issue by xsplus** [lifei6671/mindoc#131]
1. 当前 MinDoc 版本?
v0.6

2. 你当前使用的是什么操作系统?
CentOS7.2

3. 问题
配置好邮件服务后，使用忘记密码功能，发送重置密码邮件时，网页端提示邮件发送成功，但是实际上没有发送成功，日志显示邮件发送失败，具体日志如下：
邮件发送失败 =>  960346496@qq.com 550 5.8.1 Local user only. 

请问这是什么原因呢？

**Comment by lifei6671** [comment]
还是邮件服务没配置好。有些邮件服务可能不支持第三方发送邮件。

**Comment by lifei6671** [comment]
新版本已支持
