### ISSUE TITLE
mindoc能不能导入markdown文件，能不能导出，文件存在什么地方了

### ISSUE THREAD

**Issue by iiot2017** [lifei6671/mindoc#132]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
   v0.6

2. 你当前使用的是什么操作系统?
   centos 6.4

3. 问题
mindoc能不能导入markdown文件，能不能导出，文件存在什么地方了

**Comment by lifei6671** [comment]
存在数据库，可以从数据库导出来。
