### ISSUE TITLE
安装过程中依赖GLIBC_2.14能否降为2.12

### ISSUE THREAD

**Issue by shizhao1100** [lifei6671/mindoc#133]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
V 0.6
2. 你当前使用的是什么操作系统?
CentOS 6.9
3. 你是如何操作的？
修改Linux环境变量以后
./mindoc_linux_amd64 install
4.遇见什么问题？
"./mindoc_linux_amd64: /lib64/libc.so.6 version 'GLIBC_2.14' not found(required by ./mindoc_linux_amd64)"
5.期望？
装了一天了没装上 升级GLIBC貌似需要升级内核。成本有点儿高啊···目前主流的GLIBC版本是2.12吧 可能是我操作有误。肯能是机器环境的确过低。

**Comment by lifei6671** [comment]
自己编译才行。

**Comment by shizhao1100** [comment]
感谢回复。接下来我将在服务器配置golang环境。通过编译安装的方式进行安装。感谢作者的开源精神已经提供的mindoc

**Comment by shizhao1100** [comment]
由于是内网环境 go 无法执行
go get github.com/astaxie/beego/session 
package github.com/astaxie/beego/session 
imports github.com/astaxie/beego/session 

编译安装仍然出错 cannot find package “github.com/astaxie/beego/session/memcache”
