### ISSUE TITLE
输入可用的邮箱系统提示邮箱格式不正确

### ISSUE THREAD

**Issue by tonitech** [lifei6671/mindoc#134]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.6

2. 你当前使用的是什么操作系统?
linux centos

3. 你是如何操作的？
创建用户->输入邮箱地址：zhiang.wang@whats-egg.com

4. 你期望得到什么结果?
我们的邮箱就是这样的

5. 当前遇到的是什么结果?
系统提示邮箱格式不正确

**Comment by lifei6671** [comment]
可能是邮件检测的正则表达式不支持你这种带有特殊字符的邮箱。
