### ISSUE TITLE
0.6编译版找不到开启评论的配置

### ISSUE THREAD

**Issue by abyss-cmg** [lifei6671/mindoc#136]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.6 编译版

2. 你当前使用的是什么操作系统?
Linux centos 7 64

3. 你是如何操作的？
登录超级管理员 - 管理后台 - 配置管理

4. 你期望得到什么结果?
开启评论

5. 当前遇到的是什么结果?
没有评论配置选项

**Comment by lifei6671** [comment]
评论没有开发完。
