### ISSUE TITLE
markdown编辑模式，在关闭实时预览的情况下，不能保存

### ISSUE THREAD

**Issue by qianlongzt** [lifei6671/mindoc#138]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
`v0.6`
2. 你当前使用的是什么操作系统?

服务器 `ubuntu 16.04`，浏览器 `chrome 60` ，Markdown 编辑模式下

3. 你是如何操作的？
关闭实时预览，然后 Ctrl + S 

4. 你期望得到什么结果?

保存成功

5. 当前遇到的是什么结果?

弹出alert框 `Error: settings.watch == false`

**Comment by lifei6671** [comment]
保存的时候其实是将Markdown和预览结果一起保存到服务器的。如果你关闭了预览就无法保存HTML了。
