### ISSUE TITLE
增加文档级别的权限控制

### ISSUE THREAD

**Issue by Huarong** [lifei6671/mindoc#140]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

linux_amd64

2. 你当前使用的是什么操作系统?

centos 7.3

3. 你是如何操作的？
常规

4. 你期望得到什么结果?
增加文档级别的权限控制

5. 当前遇到的是什么结果?
好像现在只有项目级别的权限控制

**Comment by lifei6671** [comment]
属于小众需求，可能无法实现。
