### ISSUE TITLE
增加评论功能

### ISSUE THREAD

**Issue by geekperson** [lifei6671/mindoc#141]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

godoc_windows_amd64
2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？

按照手册操作
4. 你期望得到什么结果?
增加一个评论

5. 当前遇到的是什么结果?
当前没评论功能

**Comment by bruceqqq** [comment]
增加一个评论功能

**Comment by lifei6671** [comment]
评论没有开发。
