### ISSUE TITLE
导出PDF报错！！

### ISSUE THREAD

**Issue by zhangxiangfeng** [lifei6671/mindoc#143]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

MinDoc version => v0.6

2. 你当前使用的是什么操作系统?

deepin linux

3. 你是如何操作的？

点 导出pdf

4. 你期望得到什么结果?

导出pdf

5. 当前遇到的是什么结果?

其它功能都正常

![deepinscreenshot_select-area_20170913115449](https://user-images.githubusercontent.com/10842186/30359037-c042ebbe-980d-11e7-888d-2bd952780dd7.png)

![deepinscreenshot_select-area_20170913115503](https://user-images.githubusercontent.com/10842186/30359038-c072d2f2-980d-11e7-97bf-313b9c72d186.png)

**Comment by lifei6671** [comment]
请仔细阅读手册： [https://github.com/lifei6671/mindoc/wiki](https://github.com/lifei6671/mindoc/wiki)
