### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by jun283** [lifei6671/mindoc#144]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
刚下载，最新

2. 你当前使用的是什么操作系统?
Macbook

3. 你是如何操作的？
macOS 10.12.6

4. 你期望得到什么结果?
编译成功

5. 当前遇到的是什么结果?
/usr/local/Cellar/go/1.9/libexec/bin/go build -i [/Users/zhangjun/Workspace/src/mindoc]
# mindoc/vendor/github.com/astaxie/beego/utils
flag provided but not defined: -goversion
usage: compile [options] file.go...
  -%	debug non-static initializers
  -+	compiling runtime
  -B	disable bounds checking
  -D path
    	set relative path for local imports
  -E	debug symbol export
  -I directory
    	add directory to import search path
  -K	debug missing line numbers
  -N	disable optimizations
  -S	print assembly listing
  -V	print compiler version
  -W	debug parse tree after type checking
  -asmhdr file
    	write assembly header to file
  -bench file
    	append benchmark times to file
  -buildid id
    	record id as the build id in the export metadata
  -complete
    	compiling complete package (no C or assembly)
  -cpuprofile file
    	write cpu profile to file
  -d list
    	print debug information about items in list
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -f	debug stack frames
  -h	halt on error
  -i	debug line number stack
  -importmap definition
    	add definition of the form source=actual to import map
  -installsuffix suffix
    	set pkg directory suffix
  -j	debug runtime-initialized variables
  -l	disable inlining
  -largemodel
    	generate code that assumes a large memory model
  -linkobj file
    	write linker-specific object to file
  -live
    	debug liveness analysis
  -m	print optimization decisions
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	build code compatible with C/C++ memory sanitizer
  -nolocalimports
    	reject local (relative) imports
  -o file
    	write output to file
  -p path
    	set expected package import path
  -pack
    	write package file instead of object file
  -r	debug generated wrappers
  -race
    	enable race detector
  -s	warn about composite literals that can be simplified
  -shared
    	generate code that can be linked into a shared library
  -traceprofile file
    	write an execution trace to file
  -trimpath prefix
    	remove prefix from recorded source file paths
  -u	reject unsafe code
  -v	increase debug verbosity
  -w	debug type checking
  -wb
    	enable write barrier (default true)
# mindoc/vendor/github.com/go-sql-driver/mysql
flag provided but not defined: -goversion
usage: compile [options] file.go...
  -%	debug non-static initializers
。。。。。。。。。。。。。。
错误: 进程退出代码 2.

**Comment by lifei6671** [comment]
请安装golang的包管理工具glide，然后再mindoc根目录执行glide update，之后再进行编译。

**Comment by jun283** [comment]
我是这样做的：

1：git clone https://github.com/lifei6671/mindoc.git

2：cd mindoc.git

3: glide update

4: go build -ldflags "-w"

1-3步应没问题，第4步就出错


glide update
[WARN]	The name listed in the config file (github.com/lifei6671/mindoc) does not match the current location (mindoc)
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching updates for github.com/garyburd/redigo.
[INFO]	--> Fetching updates for github.com/go-sql-driver/mysql.
[INFO]	--> Fetching updates for github.com/bradfitz/gomemcache.
[INFO]	--> Fetching updates for gopkg.in/ldap.v2.
[INFO]	--> Fetching updates for github.com/nfnt/resize.
[INFO]	--> Fetching updates for golang.org/x/image.
[INFO]	--> Fetching updates for github.com/golang/freetype.
[INFO]	--> Fetching updates for gopkg.in/asn1-ber.v1.
[INFO]	--> Fetching updates for github.com/boombuler/barcode.
[INFO]	--> Fetching updates for github.com/astaxie/beego.
[INFO]	--> Fetching updates for github.com/lifei6671/gocaptcha.
[INFO]	--> Fetching updates for github.com/mattn/go-sqlite3.
[INFO]	--> Setting version for github.com/boombuler/barcode to 059b33dac2e9f716cf906bc5071ebb42e607228f.
[INFO]	--> Setting version for github.com/garyburd/redigo to ac91d6ff49bd0d278a90201de77a4f8ad9628e25.
[INFO]	--> Setting version for github.com/lifei6671/gocaptcha to b244e66362327cfd7d47c1a75eb1ca3845ffc52a.
[INFO]	--> Setting version for github.com/mattn/go-sqlite3 to 467f50b0c026317ad28fc2c0a08aab6f755cfc7a.
[INFO]	--> Setting version for github.com/go-sql-driver/mysql to 1421caf44f6464fd2ee8de694c7508ee13f92964.
[INFO]	--> Setting version for github.com/nfnt/resize to 891127d8d1b52734debe1b3c3d7e747502b6c366.
[INFO]	--> Setting version for github.com/golang/freetype to d9be45aaf7452cc30c0ceb1b1bf7efe1d17b7c87.
[INFO]	--> Detected semantic version. Setting version for github.com/astaxie/beego to v1.9.0.
[INFO]	--> Setting version for golang.org/x/image to 69afd001f792d732a78bd7225793315a8deb09ea.
[INFO]	--> Setting version for github.com/bradfitz/gomemcache to 1952afaa557dc08e8e0d89eafab110fb501c1a2b.
[INFO]	--> Detected semantic version. Setting version for gopkg.in/ldap.v2 to v2.5.0.
[INFO]	--> Detected semantic version. Setting version for gopkg.in/asn1-ber.v1 to v1.2.
[INFO]	Resolving imports
[INFO]	--> Fetching updates for github.com/kardianos/osext.
[INFO]	--> Fetching updates for golang.org/x/sys.
[INFO]	--> Fetching updates for github.com/PuerkitoBio/goquery.
[INFO]	--> Fetching updates for github.com/russross/blackfriday.
[INFO]	--> Fetching updates for github.com/andybalholm/cascadia.
[INFO]	--> Fetching updates for golang.org/x/net.
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching updates for github.com/kardianos/service.
[INFO]	Setting references for remaining imports
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/astaxie/beego
[INFO]	--> Exporting github.com/boombuler/barcode
[INFO]	--> Exporting github.com/bradfitz/gomemcache
[INFO]	--> Exporting github.com/russross/blackfriday
[INFO]	--> Exporting github.com/andybalholm/cascadia
[INFO]	--> Exporting github.com/garyburd/redigo
[INFO]	--> Exporting github.com/go-sql-driver/mysql
[INFO]	--> Exporting github.com/golang/freetype
[INFO]	--> Exporting github.com/PuerkitoBio/goquery
[INFO]	--> Exporting github.com/nfnt/resize
[INFO]	--> Exporting github.com/lifei6671/gocaptcha
[INFO]	--> Exporting github.com/mattn/go-sqlite3
[INFO]	--> Exporting github.com/kardianos/service
[INFO]	--> Exporting github.com/kardianos/osext
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting gopkg.in/asn1-ber.v1
[INFO]	--> Exporting gopkg.in/ldap.v2
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/image
[INFO]	Replacing existing vendor dependencies
[INFO]	Project relies on 19 dependencies.
