### ISSUE TITLE
macOS 本地编译

### ISSUE THREAD

**Issue by xunjianxiang** [lifei6671/mindoc#145]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
V0.6

2. 你当前使用的是什么操作系统?
macOS Sierra 10.12.6

3. 你是如何操作的？
git clone https://github.com/lifei6671/mindoc.git

4. 你期望得到什么结果?
仅仅是反馈

5. 当前遇到的是什么结果?
直接 go get github.com/lifei6671/mindoc

作为一个 go 的门外汉，我通过 git clone 之后一大堆问题。
经过同事指点，使用 go get 的方式，编译很顺利。

PS：MinDoc 将作为我司的内部文档工具，特别感谢作者。

**Comment by jun283** [comment]
请问你go get是怎么做的？我用：
go get github.com/lifei6671/mindoc

还是不成功。

**Comment by xunjianxiang** [comment]
go get github.com/lifei6671/mindoc

cd $GOPATH/src/github.com/lifei6671/mindoc

glide update

go build -ldflags "-w"

./mindoc install

./mindoc


这样就可以了 前提是你的 go 环境设置没问题。

golang.org <http://golang.org/> 中的包会被墙掉，自己搭个梯子
