### ISSUE TITLE
邮件发送问题

### ISSUE THREAD

**Issue by tchroot** [lifei6671/mindoc#149]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
godoc_linux_amd64 version

2. 你当前使用的是什么操作系统?
CentOS7.2

3. 你是如何操作的？
配置了邮件服务外发

4. 你期望得到什么结果?
可以正常发送邮件

5. 当前遇到的是什么结果?
[E] [account.go:229] 邮件发送失败 =>  li_zhaojun@topsec.com x509: cannot validate certificate for 192.168.66.9 because it doesn't contain any IP SANs

**Comment by lifei6671** [comment]
v0.8版本已支持ssl发送邮件
