### ISSUE TITLE
[asm_amd64.s:2197] ListenAndServe:  listen tcp :8181: bind: address already in use

### ISSUE THREAD

**Issue by lucas-sre** [lifei6671/mindoc#151]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
godoc_linux_amd64 

2. 你当前使用的是什么操作系统?
CentOS 7.2

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
英文提示已经很明确了。
