### ISSUE TITLE
检查邮箱格式的正则表达式需要修改

### ISSUE THREAD

**Issue by yetist** [lifei6671/mindoc#153]
conf/enumerate.go 文件中的
`const RegexpEmail = `^(\w)+(\.\w+)*@(\w)+((\.\w+)+)$`
`
无法匹配这种邮箱：`aa.bb@cc-dd.com.cn`，在注册新用户时会返回“邮箱格式不正确”的错误。

**Comment by wienerxu** [comment]
换这个正则试试
^([a-zA-Z0-9_-.])+@([a-zA-Z0-9_-])+(.[a-zA-Z0-9_-.])+

**Comment by yetist** [comment]
这个正则不行，换成这样就可以了：
