### ISSUE TITLE
配置PDF

### ISSUE THREAD

**Issue by xsplus** [lifei6671/mindoc#159]
能否有一个配置PDF的教程，或者大家有没有可以贡献一下的，这边现在在 CentOS7.2 和 Alpine 3.6（官方 Dockerfile 里面的基础镜像是这个） 下安装 wkhtmltopdf 无法成功，主要是安装  X11 libs (libX11, libXext, libXrender) 报错

**Comment by yuwenxing** [comment]
我自己写了个Dockerfile，你去我主页看下

**Comment by xsplus** [comment]
不好意思，请问您说的主页是这个吗？  www.iminho.me  这里面没看到，能否贴一下详细地址，十分感谢。
