### ISSUE TITLE
增加子项目

### ISSUE THREAD

**Issue by Huarong** [lifei6671/mindoc#160]
由于权限是以项目为单位的，在目前的机制中，目录是没有单独权限的。

希望能够增加子项目，子项目能有自己的权限。

现在所有的项目都在首页，项目一多，则非常乱。

**Comment by lifei6671** [comment]
没明白什么意思。

**Comment by hackstoic** [comment]
我们用着mindoc来做wiki。 建了一个品宣文档的项目， 其中有两个目录， 一个目录叫public 所有人可以看， 一个目录叫secret，只想让某个人看。目前mindoc是没法直接做到的。 只能通过建两个独立的项目。

**Comment by lifei6671** [comment]
@hackstoic 是的，目前只能限制到项目。
