### ISSUE TITLE
bug 关闭预览保存出错

### ISSUE THREAD

**Issue by tcliuyong** [lifei6671/mindoc#161]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新版本

2. 你当前使用的是什么操作系统?
centos

3. 你是如何操作的？
编辑文档时，关闭预览，保存和提交出错，并且保存不上

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
settings.watch==false

**Comment by lifei6671** [comment]
已经有人提过了，为了保证预览和前台展示效果一致，储存的HTML是前台预览中生成的。所以关闭预览是无法保存的。
