### ISSUE TITLE
分号分隔多个标签有bug

### ISSUE THREAD

**Issue by ccxopen** [lifei6671/mindoc#162]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
编译版  2017-9-18 https://github.com/lifei6671/mindoc/commit/5bb61618fc0d5418cd305196d29ac0271a59c06f

2. 你当前使用的是什么操作系统?
linux ubuntu 16.04

3. 你是如何操作的？
为一个项目设标签，abc;def

4. 你期望得到什么结果?
前台会分别显示两个不同的标签，abc   def

5. 当前遇到的是什么结果?
显示一个合并的标签：abc;def
查看表md_label也是合并了的标签abc;def，正确应是分开两个标签

**Comment by lifei6671** [comment]
标签是用英文下的逗号分隔，不是分号。

**Comment by ccxopen** [comment]
项目设置下面有一栏：  最多允许添加10个标签，多个标签请用“;”分割
即是提示信息错误了？

**Comment by lifei6671** [comment]
不是啊，提示里面也是逗号啊。你是不是看错了？

**Comment by ccxopen** [comment]
最多允许添加10个标签，多个标签请用“;”分割
上面呢句话是copy and paste的，所以不会看错

**Comment by lifei6671** [comment]
不可能的。你去官网上看看。

**Comment by imzye** [comment]
如何才能删除标签？

**Comment by lifei6671** [comment]
@imzye 目前没开发标签删除功能

**Comment by imzye** [comment]
@lifei6671 ，那只能从mysql里面删喽？
