### ISSUE TITLE
邮件设置问题

### ISSUE THREAD

**Issue by ccxopen** [lifei6671/mindoc#163]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
    编译版 2017-9-18 5bb6161

2. 你当前使用的是什么操作系统?
    linux ubuntu 16.04

3. 你是如何操作的？
    设置邮件服务
    a.我们有内部的邮件发送服务器，并不需要用户及密码的，提示发送邮件成功，但发现收不到邮件，是不是程序没有考虑空用户及空密码的问题？
    b.转用smtp.gmail.com，不考虑被墙的问题，是否没有支持SSL？

4. 你期望得到什么结果?
    不只是提示发送成功，而是真的会收到邮件

5. 当前遇到的是什么结果?
    用上面的a,b两种方法都没有成功收到邮件

**Comment by lifei6671** [comment]
目前不支持ssl发送。用户名和密码也是必须的。
