### ISSUE TITLE
关于nginx配置代理？

### ISSUE THREAD

**Issue by Darren-wh** [lifei6671/mindoc#164]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.6

2. 你当前使用的是什么操作系统?
centos7.0

目前主要想咨询下  nginx配置代理这块，

 location ~ .*\.(ttf|woff2|eot|otf|map|swf|svg|gif|jpg|jpeg|bmp|png|ico|txt|js|css)$ {
    
        #此处将路径执行 MinDoc 的跟目录
        root "/var/go/godoc";
        expires 30m;
    }

#此处将路径执行 MinDoc 的跟目录  这个是指我的 mindoc安装目录吗？ 是解压安装的mindoc目录？

**Comment by lifei6671** [comment]
不太明白你说的解压目录和安装目录具体指什么？
这里的配置是代理MinDoc 静态文件的。
