### ISSUE TITLE
做项目迁移或是数据迁移

### ISSUE THREAD

**Issue by chencl628** [lifei6671/mindoc#165]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
V0.6

2. 你当前使用的是什么操作系统?

linux

3. 你是如何操作的？

4. 你期望得到什么结果?
 

5. 当前遇到的是什么结果?

请问生成的文本文件放在哪个目录了？我想做迁移怎么办

**Comment by lifei6671** [comment]
数据库
