### ISSUE TITLE
管理后台的用户管理的后面分页没有数据

### ISSUE THREAD

**Issue by qianlongzt** [lifei6671/mindoc#167]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64 version
MinDoc current version =>  v0.6
MinDoc last version =>  v0.6
2. 你当前使用的是什么操作系统?
Ubuntu 16.04.3LTS
3. 你是如何操作的？
管理后台->用户管理，分页显示

4. 你期望得到什么结果?
分页显示正确

5. 当前遇到的是什么结果?
有43个用户，3、6号被删除，显示出来有 5个分页，但是4、5分页没有数据
![image](https://user-images.githubusercontent.com/18493471/31849230-e36e827e-b671-11e7-9474-ad4ee22d139a.png)

**Comment by lifei6671** [comment]
是的，这是一个BUG，下个版本会修复。
