### ISSUE TITLE
阅读页面点击右上角【返回编辑】后无法直接跳转到某页面的编辑界面

### ISSUE THREAD

**Issue by imzye** [lifei6671/mindoc#168]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.6

2. 你当前使用的是什么操作系统?
CentOS 7

3. 你是如何操作的？
在某个阅读页面上点击右上角【返回编辑】

4. 你期望得到什么结果?
返回当前查看页面的编辑界面

5. 当前遇到的是什么结果?
返回项目首页的编辑界面，还需要重新展开左侧导航栏，找到刚刚查看的页面，进行编辑。

能否改成直接跳转到该查看页面对应的编辑界面？

**Comment by lifei6671** [comment]
这个不太好实现。编辑界面需要涉及到很多的js加载和执行的。

**Comment by lifei6671** [comment]
v0.13版本已实现。
