### ISSUE TITLE
新增需求

### ISSUE THREAD

**Issue by wjangelking** [lifei6671/mindoc#169]
1. 你当前使用的是哪个版本的 MinDoc   v0.6

需求1：用户信息中添加昵称字段，方便设置成员真实姓名

需求2：在项目管理，添加成员这里，可下拉框列出所有成员账户（昵称），可滚动，输入关键字时匹配模糊结果

![tim 20171122164306](https://user-images.githubusercontent.com/17584830/33117686-54e52d86-cfa4-11e7-86b2-63cced7dea15.png)

@lifei6671

**Comment by lifei6671** [comment]
[v0.8版本已实现](https://github.com/lifei6671/mindoc/releases/tag/v0.8.1)
