### ISSUE TITLE
关闭实时预览的情况下快捷键保存报错

### ISSUE THREAD

**Issue by 2017noobman** [lifei6671/mindoc#171]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64 v0.6

2. 你当前使用的是什么操作系统?
Mac OS 10.13.1

3. 你是如何操作的？
关闭了实时预览，使用command+s保存

4. 你期望得到什么结果?
不知道就是这样设计的还是bug，希望可以保存

5. 当前遇到的是什么结果?
Error:setting.watch == false

**Comment by lifei6671** [comment]
已经有人提过这个问题了。实际上数据库储存的是预览后的html结果。所以，关闭预览无法保存。
