### ISSUE TITLE
支持设置session 有效期吗？

### ISSUE THREAD

**Issue by zhangxiangfeng** [lifei6671/mindoc#172]
请按照一下格式提交issue，谢谢！

哪里可以设置session 的有效期，现在的有效期太短了，我需要设置成1年的。

**Comment by lifei6671** [comment]
配置文件中`sessiongcmaxlifetime` 配置的是session有效期，默认是3600秒。

**Comment by lifei6671** [comment]
更多的配置信息可以参考这： [https://beego.me/docs/mvc/controller/session.md](https://beego.me/docs/mvc/controller/session.md)

**Comment by zhangxiangfeng** [comment]
谢谢.我试试
