### ISSUE TITLE
文档中出现<>这类操作预览不能显示

### ISSUE THREAD

**Issue by qianqian123** [lifei6671/mindoc#174]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.5

2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？
文档中出现<>这类操作预览不能显示
4. 你期望得到什么结果?
希望能显示

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
这个符号有可能会被解释成html标签。建议你用&gt; 和&lt;替换。
