### ISSUE TITLE
markdow编辑器增加 flowchart 或是 mermaid 支持 画流程图

### ISSUE THREAD

**Issue by xhb** [lifei6671/mindoc#177]
问题： 我们的小团队码农较多，希望编辑器可以使用 flowchart 语法，或是 mermaid 语法来画流程图。
就像这样：
写这样：
![2601010457-57ad3f0c71b54_articlex](https://user-images.githubusercontent.com/3167082/33972752-751dd0ae-e0ba-11e7-9391-d031693da6f2.png)

得到这个：
![3918294250-57ad373d3fc6e_articlex](https://user-images.githubusercontent.com/3167082/33972757-7d58ac6c-e0ba-11e7-872d-399ac1185e03.png)

**Comment by lifei6671** [comment]
这个对前端CSS渲染有严格的要求，目前前端有自定义的CSS，可能会因为冲突导致流程图变形。所以去掉了这块的功能。

**Comment by lifei6671** [comment]
v0.8已支持时序图和流程图
