### ISSUE TITLE
增加匿名访问首页logo位，广告位，备案号位等

### ISSUE THREAD

**Issue by diagoo** [lifei6671/mindoc#182]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.6

2. 你当前使用的是什么操作系统?
centos 7 64位

3. 你是如何操作的？
正常操作

4. 你期望得到什么结果?
a、匿名访问站点首页可设置logo，及广告位，
b、匿名访问站点首页中下部可增加备案信息设置，
c、搜索结果关键词高亮
d、markdown编辑下没有居左居中设置（好像确实不支持各种格式操作。。汗。。。）

5. 当前遇到的是什么结果?
a、无
b、无
c、目前搜索结果可定位到文档范围。
d、文字和图片需要居中，但无法做到

**Comment by lifei6671** [comment]
1、你这个还是自己二开的，定位不一样。
2、这个备案，如果你是需要公开给第三方用的话，建议你修改下模板。
3、这个是有高亮的，不是你说的高亮具体指什么？
4、Markdown语法就不支持居中。想要实现居中可以切换微html编辑器。
