### ISSUE TITLE
不同项目的文档标识不能一样

### ISSUE THREAD

**Issue by MetSystem** [lifei6671/mindoc#185]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.6

2. 你当前使用的是什么操作系统?
window  server 2008

3. 你是如何操作的？
无

4. 你期望得到什么结果?
每个项目的文档标识应该是可以重复的。
比如： 项目A  文档标识为 start           =>  A_start
            项目B  文档标识为 start           =>  B_start

5. 当前遇到的是什么结果?
当前v0.6版本我在项目A中创建了start，再到项目B中创建start却提示已经存在

**Comment by lifei6671** [comment]
是的，文档标识需要全局唯一。因为系统内部是用文档标识定位项目和权限的。

**Comment by MetSystem** [comment]
文档标识全局唯一是正常的。我的意思是不是可以每个项目前面自动生产一个GUID +自己手写的标识
或者全部自动生产。

1. 项目标识的GUID+ 手写部分的
2.全都自动生产不需要手写

**Comment by lifei6671** [comment]
你可以不手动填，系统会用自增序列当标识。

**Comment by MetSystem** [comment]
这个好，我之前没发现。
