### ISSUE TITLE
MacOS系统怎么安装？

### ISSUE THREAD

**Issue by tesondraw** [lifei6671/mindoc#186]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?
     MacOS

3. 你是如何操作的？

4. 你期望得到什么结果?
    MacOS系统下能安装吗？下载Linux包安装吗？

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
MacOS需要自己编译。

**Comment by tesondraw** [comment]
没有编译过。：）
