### ISSUE TITLE
如何增加一个类似EXCEL这样的设置好计算公式，输入一个数据生成一个值出来呢？

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#187]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
这个不是文档系统的功能，你应该需要excel。
