### ISSUE TITLE
默认封面没有什么用，如果把标题等信息显示在默认封面里就好了

### ISSUE THREAD

**Issue by gao88** [lifei6671/mindoc#19]

**Comment by lifei6671** [comment]
考虑过这个问题，go语言在图片上写字格式很难掌握，所以就没做。

**Comment by everyx** [comment]
@lifei6671 是否可以考虑在这种情况下，不用生成带文字的图片，而直接使用 html（文字） + css（相对定位） 来设置封面？

**Comment by lifei6671** [comment]
@everyx 可以考虑，不过可能很多用户希望能够自定义项目的封面。

**Comment by xgithub** [comment]
封面真的不能修改啊，我找了一圈配图，回来发现不能更换封面！

**Comment by jannson** [comment]
我看　wiki 首页说是支持封面了，但我还是找不到封面设置的地方啊，谁能帮忙指导下吗？

**Comment by lifei6671** [comment]
封面是需要在我的项目->设置->点击右侧封面图片来修改，

**Comment by venliong** [comment]
不一定要使用golang生成图片，可以利用HTML 5 canvas 在浏览器中生成图片，然后post到服务器保存

**Comment by lifei6671** [comment]
@venliong 有道理，有时间研究下。
