### ISSUE TITLE
如何使用富文本编辑器？

### ISSUE THREAD

**Issue by Roadshr** [lifei6671/mindoc#192]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.6

2. 你当前使用的是什么操作系统?
mac

3. 你是如何操作的？
使用编译后的版本部署，在Ubuntu部署

4. 你期望得到什么结果?
能够使用评论和富文本编辑器

5. 当前遇到的是什么结果?
没有评论功能和富文本编辑器

**Comment by lifei6671** [comment]
评论功能未开发。富文本编辑器请在项目设置中切换。

**Comment by Roadshr** [comment]
项目设置中没有，然后在设置和在系统中也看不到具体的版本。
