### ISSUE TITLE
查看不了目前部署的版本？

### ISSUE THREAD

**Issue by Roadshr** [lifei6671/mindoc#193]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.6

2. 你当前使用的是什么操作系统?
mac

3. 你是如何操作的？

4. 你期望得到什么结果?
能够查看部署的mindoc的版本

5. 当前遇到的是什么结果?
没有地方查看目前的版本号

**Comment by lifei6671** [comment]
https://github.com/lifei6671/mindoc/wiki/MinDoc-%E4%B8%AD%E7%9A%84%E5%91%BD%E4%BB%A4
