### ISSUE TITLE
在centos7无图形化下启动的服务无法导出PDF报Could not connect to display

### ISSUE THREAD

**Issue by nbczw8750** [lifei6671/mindoc#194]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64  v0.6

2. 你当前使用的是什么操作系统?
centos7 无GUI模式下

3. 你是如何操作的？
配置好了wkhtmltopdf  导出pdf时报错 QXcbConnection: Could not connect to display
在图形窗口下开启服务，新增一页后再导出也报错
![image](https://user-images.githubusercontent.com/299441/34712216-0ae0702c-f55d-11e7-829d-9556f748e7d0.png)

4. 你期望得到什么结果?
正确导出pdf文件
PDF排版和网页一致

5. 当前遇到的是什么结果?
导出失败 报QXcbConnection: Could not connect to display，
应该是没图形界面的情况下报错了
  
![image](https://user-images.githubusercontent.com/299441/34712216-0ae0702c-f55d-11e7-829d-9556f748e7d0.png)

PDF的排版和网页上不一致，标题就没居中

**Comment by lifei6671** [comment]
这个您最好看下wkhtmltopdf 的官方文档。
PDF导出功能完全靠的就是这个工具的导出功能。
