### ISSUE TITLE
Markdown的样式如何修改

### ISSUE THREAD

**Issue by moyanyuansu** [lifei6671/mindoc#197]
比如代码块，默认背景颜色是黑色的，能否改成其他颜色

**Comment by lifei6671** [comment]
请自行阅读源码修改。系统没有提供修改功能。

**Comment by ywz978020607** [comment]
> 比如代码块，默认背景颜色是黑色的，能否改成其他颜色

https://github.com/ywz978020607/mindoc/tree/changetheme
写了一个默认黑色，增加一个按键可以临时切换主题的
