### ISSUE TITLE
邮箱格式中不能用“-”符号

### ISSUE THREAD

**Issue by Roadshr** [lifei6671/mindoc#199]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.6

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
注册 XXX@a-bc.com

4. 你期望得到什么结果?
可以注册成功

5. 当前遇到的是什么结果?
反馈邮箱格式不正确。“-”在邮箱格式非常常见

**Comment by lifei6671** [comment]
是的，邮箱校验的正则不够全面。下个版本修复。
