### ISSUE TITLE
提个新需求

### ISSUE THREAD

**Issue by Zorion-zozo** [lifei6671/mindoc#200]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
V0.6

2. 你当前使用的是什么操作系统?
windows+linux

3. 你是如何操作的？
  (1) 希望英文化；
  (2) 没有php原版安装

4. 你期望得到什么结果?
  (1) 除了自己写的文章外，其他界面上的内容，可以通过设置，切换中英文版本；
  (2) 希望提供原始php包与安装方法

5. 当前遇到的是什么结果?
  (1) 全都是中文，外语为主的企业使用不便；
  (2) 因为是go语言，不会操作，如果是原始laravel开发包，我可以自行定义操作了

**Comment by lifei6671** [comment]
1、本人英文不太好，所以无法提供英文版。
2、这个项目本身就是go开发的。
