### ISSUE TITLE
为什么有些文档在查看的时候不会展示文件内容？

### ISSUE THREAD

**Issue by BeginVic** [lifei6671/mindoc#201]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64

2. 你当前使用的是什么操作系统?
win64

3. 你是如何操作的？
我现在是直接在你们的测试demo上面 http://doc.iminho.me/book
![image](https://user-images.githubusercontent.com/25980683/35031848-a32906c6-fb9f-11e7-9e6a-e65ae1740b84.png)
点击查看文档，选中具体文档，有内容，但是查看的时候却不展示
![image](https://user-images.githubusercontent.com/25980683/35031949-fd85d626-fb9f-11e7-81b0-10db8ca3923c.png)

4. 你期望得到什么结果?
我希望可以展示文档的内容

5. 当前遇到的是什么结果?
文档内有内容，但查看文档的时候不展示，只展示标题（PS：但是别人建的项目，文档内容还是可以显示的，不知道是什么原因？有格式限制？）

**Comment by lifei6671** [comment]
保存问文档后，请点击发布文档。
