### ISSUE TITLE
html编辑格式面板没有“返回”交互

### ISSUE THREAD

**Issue by BeginVic** [lifei6671/mindoc#202]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？
http://doc.iminho.me/api/q123/edit/

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
![image](https://user-images.githubusercontent.com/25980683/35032206-071c284c-fba1-11e7-86f9-3e871d28f872.png)

**Comment by lifei6671** [comment]
本来就没设计返回。。

**Comment by BeginVic** [comment]
没设计返回是忘记设计？还是特地不设计“返回”交互，有什么用意吗？

**Comment by lifei6671** [comment]
下一个版本会重新实现富文本编辑器，会加上返回按钮
