### ISSUE TITLE
项目导出PDF时，每次导出都会先安装wkhtmltox

### ISSUE THREAD

**Issue by BeginVic** [lifei6671/mindoc#203]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64

2. 你当前使用的是什么操作系统?
win64

3. 你是如何操作的？
点击“项目导出PDF”

4. 你期望得到什么结果?
直接导出生成PDF文件

5. 当前遇到的是什么结果?
每次导出pdf之前都会先安装wkhtmltox，然后才生成PDF文件

**Comment by lifei6671** [comment]
确定是每次吗？

**Comment by BeginVic** [comment]
是的,下面是我连续两次导出的截图
![image](https://user-images.githubusercontent.com/25980683/35088596-3b9d03d8-fc6f-11e7-99c5-ca7f3c1a84ab.png)
![image](https://user-images.githubusercontent.com/25980683/35088625-51faae32-fc6f-11e7-9bd1-e4a23184d049.png)

**Comment by lifei6671** [comment]
这不是MinDoc的问题，是你本地计算机的问题。
