### ISSUE TITLE
导出的PDF使用浏览器查看报错

### ISSUE THREAD

**Issue by BeginVic** [lifei6671/mindoc#204]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64

2. 你当前使用的是什么操作系统?
win64

3. 你是如何操作的？
点击项目导出pdf，使用pdf阅读器和浏览器查看均报错
![image](https://user-images.githubusercontent.com/25980683/35079933-702c0a88-fc45-11e7-81b7-3e5ef646447c.png)

4. 你期望得到什么结果?
导出的pdf文件可以正常阅读

5. 当前遇到的是什么结果?
![image](https://user-images.githubusercontent.com/25980683/35079901-2cf3b91e-fc45-11e7-9a40-dcebe4f517cc.png)

**Comment by moyanyuansu** [comment]
这是你浏览器问题
