### ISSUE TITLE
绑定域名后首次登录成功跳转到127.0.0.1:8181

### ISSUE THREAD

**Issue by XuYS** [lifei6671/mindoc#208]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v07;

2. 你当前使用的是什么操作系统?
centso

3. 你是如何操作的？

用Apache做了反向代理，将域名转发到了127.0.0.1:8181.
4. 你期望得到什么结果?

登录的时候提交登录成功后页面跳转到http://127.0.0.1:8181. 再返回域名首页就能正常访问了。
5. 当前遇到的是什么结果?

我希望的结果是跳转到我绑定的域名的首页，不是http://127.0.0.1:8181。

**Comment by zhangxiangfeng** [comment]
反向代理 ,配置的有问题,目测 你的反向代理 没有告诉mindoc 你的所在访问的域名。mindoc自然取访问的ip。
