### ISSUE TITLE
文档附件上传返回链接和插不进文档里面。

### ISSUE THREAD

**Issue by XuYS** [lifei6671/mindoc#209]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

v7;
2. 你当前使用的是什么操作系统?

服务器centso6 ； 客户端是：macOS chrome浏览器。
3. 你是如何操作的？

多个文档节点、上传附件，插不进文档里面， 返回的链接是127.0.0.1:8080 不是绑定的域名。
4. 你期望得到什么结果?
期望能够上传后能插到当前编辑的页面。

5. 当前遇到的是什么结果?
插不进

**Comment by lifei6671** [comment]
附件本身就不能插入到文档中。
