### ISSUE TITLE
邮件发不出！25端口 系统默认屏蔽

### ISSUE THREAD

**Issue by zhangxiangfeng** [lifei6671/mindoc#210]
![_20180130002620](https://user-images.githubusercontent.com/10842186/35521306-5e3a89e0-0554-11e8-8780-d086a458e40b.jpg)

请问是否支持465ssl发送邮件？ 阿里云新发售的机器，25端口被默认屏蔽,25端口 由内->外网 无法访问

**Comment by lifei6671** [comment]
这个你应该找阿里云，找我没用啊。

**Comment by zhangxiangfeng** [comment]
不应该支持 使用465端口  ssl加密 发送邮件吗? @lifei6671

**Comment by lifei6671** [comment]
因为目前这个功能用的人比较少，所以没有优化，下个版本优化下吧。

**Comment by zhangxiangfeng** [comment]
ok

**Comment by zhangxiangfeng** [comment]
等待这个功能加入后,我们公司内部再从0.6开始升级

**Comment by lifei6671** [comment]
新版本v0.8已实现
