### ISSUE TITLE
附件显示的 逻辑有问题。

### ISSUE THREAD

**Issue by cyooleoo** [lifei6671/mindoc#211]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
        0.7版 源代码win10下编译。

2. 你当前使用的是什么操作系统?
        win server 2008R2

3. 你是如何操作的？
        当文档只有标题和附件时，点击左边目录--文档标题，只显示标题，附件没显示；
        点首行“编辑”后，左边目录收起，又需要点击 文档标题，才会出现 附件个数链接。

4. 你期望得到什么结果?
         查看目录，点击文档时，附件链接也显示出来。         

5. 当前遇到的是什么结果?
         查看目录，点击文档时，附件链接显示不出来。

**Comment by lifei6671** [comment]
请发布你的项目。
