### ISSUE TITLE
希望能增加目录功能, 哪怕是一级目录也好

### ISSUE THREAD

**Issue by lvbuwei** [lifei6671/mindoc#212]
您好，因为我们的API较多，分为登录的、业务的、权限的、通用的，如果能增加一个分类目录就十分方便了，即使是只有一级，查看起来也比较方便，显的有层次，现在一大堆文档平铺在左侧，看起来感觉有些乱。

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.7.3 

2. 你当前使用的是什么操作系统?
mac os x 

3. 你是如何操作的？
点击创建文档,创建后都在同一级。

4. 你期望得到什么结果?
带一个上级文件夹，可以选择把文档归类到哪个文件夹中。

5. 当前遇到的是什么结果?
当前只有平铺的文档。

mindoc很方便，界面也很大方，希望能越做越好。

**Comment by lifei6671** [comment]
您需要在文档上右键。

**Comment by nightwind27** [comment]
能否提供多级目录结构？ 这个十分必要 目前项目多了特别混乱
