### ISSUE TITLE
无法备份和恢复、删除某个项目，希望有这几个功能

### ISSUE THREAD

**Issue by sosize** [lifei6671/mindoc#213]
希望有以下三个功能：
1、备份和恢复功能，最好是项目导入和导出功能，用于从一个地方移植到另一个地方（目前直接导出导入数据库，有问题，打开具体项目会提示500）
2、管理员可以删除具体某个项目（目前找不到删除的地方）
3、模版那个希望是可以编辑的，目前是固定写死，除非后台修改对应的模版

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.7.3

2. 你当前使用的是什么操作系统?
Ubuntu 16.04 64位

3. 你是如何操作的？
没有该功能

4. 你期望得到什么结果?
拥有该功能

5. 当前遇到的是什么结果?
没有该功能

**Comment by lifei6671** [comment]
1、项目目前不支持备份功能。导出依赖于第三方组件，具体配置可参考wiki。
2、管理员是可以删除其他人的项目的。
3、模板是内置的参考，一般不会变动。如果客户有需求，只需要修改对应tpl文件即可。感觉做成功能有点浪费。

**Comment by sosize** [comment]
目前试了下
1、项目暂时可以通过mysql备份和导入方式来实现，导入mysql后再mindoc_linux_amd64 install就好了
2、管理员在项目管理->项目列表，直接点要删除的项目，进去后就可以删除（不好意思，之前没认真研究）
3、模块这个暂时可以修改tpl替代，这个暂时不是强需求

@lifei6671  谢谢答复
