### ISSUE TITLE
修改密码页面css文件路径404

### ISSUE THREAD

**Issue by MyLeoLan** [lifei6671/mindoc#214]
![_ _20180205120256](https://user-images.githubusercontent.com/18298528/35787902-8902baea-0a6c-11e8-93bf-52cf04c0a571.png)
![_ _20180205120340](https://user-images.githubusercontent.com/18298528/35787914-9e2bf8a0-0a6c-11e8-86e7-d3d638f384ec.png)

**Comment by lifei6671** [comment]
已修复
