### ISSUE TITLE
1.登录的时候有问题，有登录不了重定向过多的问题

### ISSUE THREAD

**Issue by jacklovebella** [lifei6671/mindoc#216]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
我测试没发现这个问题，能够详细描述下使用场景呢？

**Comment by jacklovebella** [comment]
http://doc.repaiapp.com/login  我今天一早上登录的时候就是登录不了的状态

**Comment by jacklovebella** [comment]
现在好了  刚刚是我数据库磁盘满了
