### ISSUE TITLE
升级后附件下载链接，地址错误

### ISSUE THREAD

**Issue by xshagua** [lifei6671/mindoc#220]
版本：Windows 系统 0.7.3 、 0.8.1版本 ，新上传的附件下载链接错误。

![snipaste_2018-02-24_16-36-10](https://user-images.githubusercontent.com/1492406/36627701-b085a75c-1981-11e8-87b2-0466b482e094.png)

数据表：md_attachment  字段：http_path，升级前后内容差异：

![snipaste_2018-02-24_16-44-31](https://user-images.githubusercontent.com/1492406/36627724-0972d740-1982-11e8-931d-1b462e8e0dd7.png)

**Comment by lifei6671** [comment]
你前端用的是nginx吗？如果是nginx需要配置host传递到后端，可以看看wiki里面nginx的配置。

**Comment by xshagua** [comment]
用的 IIS 出现此问题

**Comment by lifei6671** [comment]
@xshagua 使用代理需要将前端的域名和协议发送到后端，需要传递的请求头有：`X-Forwarded-For` 远端IP、`Host` 站点域名、`X-Forwarded-Proto` 使用协议是http还是https。
