### ISSUE TITLE
邮箱地址不能用 “-”

### ISSUE THREAD

**Issue by Roadshr** [lifei6671/mindoc#221]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？
我们公司邮箱地址有个“ -“ ，
4. 你期望得到什么结果?

希望能收到邮件和使用邮箱
5. 当前遇到的是什么结果?
邮箱无法使用和注册，比如 a@a-b.com
但这是合法的

**Comment by lifei6671** [comment]
你用的是哪个版本的mindoc？最新版是支持这种邮箱的。
