### ISSUE TITLE
MacOS上编译出错

### ISSUE THREAD

**Issue by imzye** [lifei6671/mindoc#222]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
latest

2. 你当前使用的是什么操作系统?
MacOS

3. 你是如何操作的？
go build -ldflags "-w"

4. 你期望得到什么结果?
编译通过

5. 当前遇到的是什么结果?
<img width="1439" alt="screen shot 2018-03-02 at 00 05 55" src="https://user-images.githubusercontent.com/9260235/36855135-c24dd7c2-1dad-11e8-8c8f-9adc6d68a059.png">

**Comment by lifei6671** [comment]
自己编译，请先恢复包依赖。

**Comment by imzye** [comment]
不太明白，已经用 glide update 下载了依赖包

**Comment by lifei6671** [comment]
模板master分支包依赖切换为官方的dep工具。你下载后尝试执行`dep ensure`恢复依赖。再编译试试。
部分依赖是需要自备梯子。

**Comment by imzye** [comment]
编译成功了，谢谢～ @lifei6671
