### ISSUE TITLE
0.6更新到0.8后，登录成功后出现白屏

### ISSUE THREAD

**Issue by imrememberlee** [lifei6671/mindoc#223]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

0.8
2. 你当前使用的是什么操作系统?
ubuntu14.04

3. 你是如何操作的？
nohup ./mindoc_linux_amd64
4. 你期望得到什么结果?
更新成功

5. 当前遇到的是什么结果?
命令行显示更新成功，主要可以登录，登录成功后出现白屏
![image](https://user-images.githubusercontent.com/8325671/36895325-7c1f70f2-1e49-11e8-822e-f536aac1e9ea.png)

**Comment by lifei6671** [comment]
清空下你的浏览器缓存施食。看看控制台上有没有异常信息。

**Comment by imrememberlee** [comment]
清理过还是一样

**Comment by lifei6671** [comment]
@imrememberlee 看看控制台上有没有异常错误。配置文件是不能替换的。

**Comment by imrememberlee** [comment]
我把0.8版本的配置文件替换成0.6版本的，这样是不行的吗？

**Comment by lifei6671** [comment]
是的，配置文件有升级。

**Comment by imrememberlee** [comment]
我改0.8版本的配置文件一样是打不开，登录页面正常，一旦登录成功我转向http://wiki.a-bianli.com/undefined页面，重新注入http://wiki.a-bianli.com，是空白页面，console没有任何信息

**Comment by imrememberlee** [comment]
thinks，现在解决了，使用nohup ./mindoc_linux_amd64 后台部署，要先kill掉原来的进程再安装更新，和重新部署
