### ISSUE TITLE
导出功能报错，请问怎么解决

### ISSUE THREAD

**Issue by yemengge** [lifei6671/mindoc#224]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

0.8
2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？

新建一个文本文档，ebook-convert 111.txt test.pdf后报错
4. 你期望得到什么结果?
正常导出文档

5. 当前遇到的是什么结果?
![tim 20180305193244](https://user-images.githubusercontent.com/37070681/36972934-05d495fc-20ac-11e8-8a91-7bc2d7c7f4cb.png)
不知道怎么解决了，求大神解答！！！

**Comment by lifei6671** [comment]
看错误应该是libGL的问题，建议你去官网查查。
