### ISSUE TITLE
文档导出错误

### ISSUE THREAD

**Issue by alley9469** [lifei6671/mindoc#226]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.9

2. 你当前使用的是什么操作系统?
centos 7

3. 你是如何操作的？
文档页面-下载-pdf

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

点了下载之后等了一段时间报出500，跟踪了下 uploads/books/{id} 目录、始终没发现生成配置文件

**Comment by lifei6671** [comment]
请参考手册 [https://github.com/lifei6671/mindoc/wiki](https://github.com/lifei6671/mindoc/wiki)
