### ISSUE TITLE
如何把编辑器设置为wangEditor？

### ISSUE THREAD

**Issue by pipiluhua** [lifei6671/mindoc#227]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.9

2. 你当前使用的是什么操作系统?
win10

3. 你是如何操作的？
配置管理里面 没有呀

4. 你期望得到什么结果?
把markdown 编辑器换成wangeditor

5. 当前遇到的是什么结果?

**Comment by pipiluhua** [comment]
找到了 在项目设置里面

**Comment by 941477276** [comment]
@pipiluhua 在哪个地方配置？请指点一下
