### ISSUE TITLE
在win7上部署后，打开浏览器不能访问mindoc

### ISSUE THREAD

**Issue by sunGunx** [lifei6671/mindoc#228]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
 mindoc_windows_amd64.7z 
2. 你当前使用的是什么操作系统?
win7

3. 你是如何操作的？
按照部署说明
进行到
#在MinDoc跟目录下新建一个slave.vbs文件：

Set ws = CreateObject("Wscript.Shell") 
ws.run "cmd /c start.bat",vbhide 

#再建一个start.bat文件：
@echo off

mindoc_windows_amd64.exe
这一步时，没有生成install。lock文件，之后运行exe文件，可以运行，数据库链接正常，
显示正running http://:8181,打开浏览器，输入localhost：8181浏览时不能访问mindoc，且后台程序退出
4. 你期望得到什么结果?
访问mindoc

5. 当前遇到的是什么结果?
不能访问

**Comment by lifei6671** [comment]
请按照这里的文档部署： https://github.com/lifei6671/mindoc/wiki

**Comment by sunGunx** [comment]
您好
是按这篇文档部署的

您方便留个微信吗


发送自 Windows 10 版邮件应用

发件人: Minho
发送时间: 2018年3月8日 15:31
收件人: lifei6671/mindoc
抄送: sunGunx; Author
主题: Re: [lifei6671/mindoc] 在win7上部署后，打开浏览器不能访问mindoc (#228)

请按照这里的文档部署： https://github.com/lifei6671/mindoc/wiki

**Comment by lifei6671** [comment]
这个教程里面没有用到vbs脚本。直接在控制台上操作就行。操作完了安装成服务，开机启动。

**Comment by sunGunx** [comment]
* body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }你好，经过部署mindoc及操作一段时间后遇到几个问题，如下:1. 退出管理员账号时，登陆一般用户时，提示没有权限，表明退出登陆后，再次登陆账号时，默认加载界面是上次退出前的页面，因此会报错。
2. 在编辑页面，点击浏览器“”“回退”建时，所编辑内容不能保存。
3.数据库移植问题，请问在不同服务器部署时，如何同步数据库数据。
4.当前在浏览器中访问mindoc时是
127.0.0.1:8181/login?url
请问能否
更改成127.0.0.1:8181/mindoc/login?url
加一级子目录望回复* body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; } * body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }

**Comment by lifei6671** [comment]
没太明白你遇到的具体问题是什么？
部署到二级子目录目前是没办法实现的。

**Comment by sunGunx** [comment]
发自坚果 Pro
* body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }christ <sunliangchrist@163.com>
于 2018年3月21日 下午3:08写道：你好是这样的部署到我们公司的服务器上服务器上有防火墙只开了一个80端口但是这个端口有别的东西在用因此想mindoc是都可以在80端口下建立一个检索路径，这样端口不会冲突发自坚果 Pro
* body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }Minho <notifications@github.com>
于 2018年3月21日 下午3:02写道：没太明白你遇到的具体问题是什么？
部署到二级子目录目前是没办法实现的。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lifei6671/mindoc","title":"lifei6671/mindoc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lifei6671/mindoc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lifei6671 in #228: 没太明白你遇到的具体问题是什么？\r\n部署到二级子目录目前是没办法实现的。\r\n"}],"action":{"name":"View Issue","url":"https://github.com/lifei6671/mindoc/issues/228#issuecomment-374848381"}}}

**Comment by sunGunx** [comment]
你好建议添加模板编辑功能能够自定义模板发自坚果 Pro

**Comment by sunGunx** [comment]
你好部署到服务器上从其他计算机上不能下载附件，默认访问的127.0.0.1发自坚果 Pro

**Comment by sunGunx** [comment]
你好附件不能下载，访问的是127.0.0.1而不是服务器地址请问如何配置发自坚果 Pro

**Comment by sunGunx** [comment]
你好
更新最新程序后
以前的账号能够登录
但是之前的项目不能打开了

**Comment by lifei6671** [comment]
@sunGunx 看看是不是项目没有设置标识。

**Comment by sunGunx** [comment]
有的项目没有标示，没有标示就不能打开吗




在2018年10月10日 17:59，Minho 写道：

@sunGunx 看看是不是项目没有设置标识。

**Comment by sunGunx** [comment]
所有项目都不能打开




在2018年10月10日 18:00，sunGunx 写道：
有的项目没有标示，没有标示就不能打开吗




在2018年10月10日 17:59，Minho 写道：

@sunGunx 看看是不是项目没有设置标识。

**Comment by lifei6671** [comment]
看看控制台的日志吧。
