### ISSUE TITLE
自动登陆不生效

### ISSUE THREAD

**Issue by fyobe** [lifei6671/mindoc#230]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
godoc_linux_amd64 version

2. 你当前使用的是什么操作系统?
mac os

3. 你是如何操作的？
登陆勾选记住

4. 你期望得到什么结果?
以后每次打开不需要登陆自己验证

5. 当前遇到的是什么结果?
每次都需要登陆输入用户名和密码验证

**Comment by lifei6671** [comment]
v0.10已修复
