### ISSUE TITLE
糊涂搜索

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#231]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

9.0
2. 你当前使用的是什么操作系统?

Windows
3. 你是如何操作的？
搜索关键字

4. 你期望得到什么结果?
比如搜索一个东西，叫法不一，如“妹子”在录入资料时可能输入“萌妹子”，也可能输入“萌妹”
我能不能搜索时候用两个条件来搜索呢？一个“萌”一个“妹”格式如：萌%妹
相当于糊涂查找

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
你这属于智能搜索的功能。这个需要依靠第三方搜索引擎来解决。
