### ISSUE TITLE
希望作者增加一个　markdown 导出的功能

### ISSUE THREAD

**Issue by jannson** [lifei6671/mindoc#232]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.9

2. 你当前使用的是什么操作系统?
ubuntu

3. 你是如何操作的？
无

4. 你期望得到什么结果?
有点像导出　word，希望能导出一个项目的整个　markdown。
场景：大多时候用　MinDoc，但偶尔需要把　markdown 提交到　gitlab，不够方便。

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
v0.10 已实现

**Comment by jannson** [comment]
感谢，当时第一时间使用了。只是没过来回复。感谢作者。
