### ISSUE TITLE
 在编辑过程中，应该有保存craft和上传两个不同的功能，不然编辑过程中多次点Ctrl+S保存会出现多个相近的历史版本

### ISSUE THREAD

**Issue by naivefeng** [lifei6671/mindoc#233]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
godoc_linux_amd64

2. 你当前使用的是什么操作系统?
Ubuntu,客户端Windows

3. 你是如何操作的？
编辑一个文件过程中，多次Ctrl+S保存

4. 你期望得到什么结果?
多次保存后，再点提交，正式保存为一个历史提交记录

5. 当前遇到的是什么结果?
多次Ctrl+S保存后，出现很多个历史记录，这些记录都是不必要的，希望能在保存时加入草稿功能，完成后提交，生成一次修改历史记录

**Comment by lifei6671** [comment]
一角整已修复
