### ISSUE TITLE
建议将BookStack在minidoc中未有的功能整合进来

### ISSUE THREAD

**Issue by MetSystem** [lifei6671/mindoc#234]
https://github.com/TruthHun/BookStack

**Comment by lifei6671** [comment]
这是两个系统。不兼容。没办法合并。

**Comment by MetSystem** [comment]
评论
一键导入markdown项目
一键拉取markdown项目

这几个可以集成进来

**Comment by MetSystem** [comment]
不然会被BookStack给超越了

**Comment by lifei6671** [comment]
方向不同。如果你是公司内部用，可以用mindoc。如果你是想自己搭建公开运营，可以选择bookstack。
导入功能，后面会加入。

**Comment by TruthHun** [comment]
1. BookStack是基于Mindoc做二次开发的，基本上每个给BookStack进行star的人都会顺着链接过来给Mindoc一个star，所以超越与不超越，这个不好说。
1. BookStack和Mindoc的定位不同，BookStack定位于运营，Mindoc定位于企业内的使用。
1. 项目一键导入和一键拉取、文档批量创建和一键排序等功能，都是在对Mindoc的表结构进行了一些变更之后才得以实现的。BookStack和Mindoc的不兼容，主要是因为数据表的差异导致的，所以当时没进行pr，而是重新开了一个坑。
1. 两套程序都是基于同样的开源协议提供给每个人免费使用，并且根据用户的意见和建议，不断升级和强化功能体验。
