### ISSUE TITLE
下载文档遇到500错误

### ISSUE THREAD

**Issue by 451311824** [lifei6671/mindoc#235]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
是的

2. 你当前使用的是什么操作系统?
centos

3. 你是如何操作的？
下线文档

4. 你期望得到什么结果?
正常下载

5. 当前遇到的是什么结果?
下载任何类型的文档时后台日志最后输出以下内容
[E] [book_result.go:345] 转换文件错误：接口文档 => exit status 1 
[E] [document.go:897] 转换文档失败：接口文档 -> exit status 1

**Comment by lifei6671** [comment]
https://github.com/lifei6671/mindoc/wiki/%E5%9F%BA%E4%BA%8Ecalibre%E7%9A%84%E5%A4%9A%E6%A0%BC%E5%BC%8F%E5%AF%BC%E5%87%BA%E5%8A%9F%E8%83%BD%E9%85%8D%E7%BD%AE

**Comment by vindell** [comment]
CentOS 7 安装 Calibre


第一步：设置阿里云镜像源（https://opsx.alibaba.com/mirror）
1、备份
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
2、下载新的CentOS-Base.repo 到/etc/yum.repos.d/
CentOS 5
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-5.repo
或者
curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-5.repo
CentOS 6
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo
或者
curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo
CentOS 7
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
或者
curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
3、之后运行yum makecache生成缓存


第二步：下载安装 Python 2.7.x 最新版本


第三步：下载 Calibre 3.x 

Solution:
You will need to install the redhat-lsb library by running this command as root:
 **yum -y install redhat-lsb**

https://calibre-ebook.com/download_linux

在线安装：
wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

离线安装：
mkdir -p /opt/calibre && rm -rf /opt/calibre/* && tar xvf /calibre-3.19.0-x86_64.txz -C /opt/calibre && /opt/calibre/calibre_postinstall
