### ISSUE TITLE
markdowm文档的目录显示

### ISSUE THREAD

**Issue by chengaomin** [lifei6671/mindoc#236]
能否在下一个版本，增加markdowm文档的目录显示在右侧呢，类似下面的截图

![image](https://user-images.githubusercontent.com/4586906/37563556-4becb56c-2abe-11e8-9375-7be5df411823.png)

**Comment by lifei6671** [comment]
没找到可以实现这种效果的插件。我对前端不是很熟。

**Comment by chaofen** [comment]
首先非常感谢作者的付出。
这个功能在 dokuwiki 有用过，自动把标题提取出来生成目录。
期待能加上这个功能。

**Comment by lifei6671** [comment]
v1.0版本已增加
