### ISSUE TITLE
用户注册后,没有自动发送邮箱确认邮件?

### ISSUE THREAD

**Issue by zhangxiangfeng** [lifei6671/mindoc#237]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.8.1

2. 你当前使用的是什么操作系统?

linux
3. 你是如何操作的？

注册
4. 你期望得到什么结果?

注册后,给邮箱发送确认邮件
5. 当前遇到的是什么结果?

没有发送确认邮件

**第二个问题,用户中心可以随便修改个人邮箱(哪怕是其它人的邮箱都可以!)**

`如果邮箱存在,提示不优雅`

![_ _20180322113030](https://user-images.githubusercontent.com/10842186/37749764-7f528d10-2dc4-11e8-862a-b48430e6876c.png)

**Comment by lifei6671** [comment]
1、目前不支持注册发邮件。
2、提示文案会在下个版本优化。

**Comment by zhangxiangfeng** [comment]
@lifei6671  嗯。 登陆成功后也不能随意修改成别人的邮箱吧。最少需要验证之类的操作吧？

**Comment by zhangxiangfeng** [comment]
现在0.10 版本都发了  这个优化 在里面了吗？

**Comment by lifei6671** [comment]
0.10版本是以前就开发好的。所以这个功能没加进来。

**Comment by zhangxiangfeng** [comment]
注册能发邮件了，登录后也有验证了？  体验地址 就是0.10版本 是吧？是的话，我去体验下
