### ISSUE TITLE
文档唯一标识为空时保存失败

### ISSUE THREAD

**Issue by abowu** [lifei6671/mindoc#238]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新的，用master分支docker部署（2018.3.28部署）

2. 你当前使用的是什么操作系统?
win10

3. 你是如何操作的？
新建文档，填了文档名，没有填文档标识

4. 你期望得到什么结果?
保存成功

5. 当前遇到的是什么结果?
保存失败

**Comment by abowu** [comment]
![image](https://user-images.githubusercontent.com/6102417/38009152-4048d82a-3285-11e8-87d4-88593ac0c030.png)

**Comment by lifei6671** [comment]
我这边测试是可以的。你看看控制台有没有错误日志？

**Comment by abowu** [comment]
找到原因了，是因为md_documents这个表把`book_id`, `identify`设置成了唯一索引，所以每个项目最多只能插一条空的标识到数据库。

**Comment by Macfee** [comment]
目前怎么解决？？

**Comment by lifei6671** [comment]
@abowu 您这边使用的是mysql数据库吗？

**Comment by lifei6671** [comment]
@Macfee 您可以先手动命名，我这边找下原因，再修复。

**Comment by Macfee** [comment]
@lifei6671 对的，我用的mysql数据库

**Comment by abowu** [comment]
@lifei6671 我用的是mysql数据库，我现在直接把那个唯一索引删除了。

**Comment by lifei6671** [comment]
v0.10.1已修复这个问题
