### ISSUE TITLE
makedown标签兼容性问题

### ISSUE THREAD

**Issue by Macfee** [lifei6671/mindoc#239]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新编译版

2. 你当前使用的是什么操作系统?
Mac OS

3. 你是如何操作的？
在firefox下，markdown的一些 按钮不兼容，比如保存，发布等等

4. 你期望得到什么结果?
希望能解决兼容性问题

5. 当前遇到的是什么结果?
不兼容

**Comment by lifei6671** [comment]
能说下火狐的浏览器版本吗？我这边测试没问题。
推荐使用chrome试下。

**Comment by Macfee** [comment]
firefox是59最新版本。
![qq20180329-143726](https://user-images.githubusercontent.com/1618484/38073717-c91ca2ce-335e-11e8-9f98-ae7019e3f6bf.png)
![qq20180329-143704](https://user-images.githubusercontent.com/1618484/38073718-ca308bd0-335e-11e8-8c0c-50d9b9060f94.png)

**Comment by lifei6671** [comment]
测试没发现你的这个问题，你尝试刷新几次呢？
