### ISSUE TITLE
建议在首页放置一个最新文章列表

### ISSUE THREAD

**Issue by sundraya-app** [lifei6671/mindoc#242]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

0.10
2. 你当前使用的是什么操作系统?
ubuntu 16.04

3. 你是如何操作的？

在项目中新增文章

4. 你期望得到什么结果?
新增的文章可以在首页某个地方特别提示出来，哪些文档是最近添加的，像一些博客一样有个最近文章列表

5. 当前遇到的是什么结果?
当项目比较多的情况下，不知道都有哪些新增文档

**Comment by lifei6671** [comment]
这个没必要吧。假如，你对接一个接口，肯定只看这个接口的项目。不可能看最新的文章吧。
