### ISSUE TITLE
calibre导出pdf错误

### ISSUE THREAD

**Issue by zhashuyu** [lifei6671/mindoc#245]
环境
    mindoc 0.9 / 0.10
    calibre 3.19.0 / 3.20.0
    centos 7.4

问题描述
由于老版本（0.6）导出的pdf文档顺序是乱的且没有层次结构，所以我升级了一下，结果都出现了下面两个问题
１. 当我的文档不多，如10个以下页面的时候，**导出pdf（包括导出word等）是正常的**，但pdf里面没有了汉字，我试过将simsun.ttf传入linux系统里，但结果相同。由于mindoc没有报错，这里就不显示错误了
2. 当页面多的时候，在页面上点击下载pdf，**经过长时间的等待都没有生成pdf，其它导出格式如word同样无法使用**，mindoc显示如下信息
```
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/META-INF
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/css
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/editor.md
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/editor.md/css
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/highlight
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/highlight/styles
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/katex
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/prettify
/tmp/8829bf2cbfd6ab8d65df8ce7d04aed80/newcomer/styles/prettify/themes
171.html
173.html
174.html
175.html
176.html
177.html
178.html
207.html
208.html
209.html
210.html
211.html
212.html
214.html
215.html
216.html
217.html
218.html
219.html
220.html
221.html
222.html
223.html
224.html
225.html
226.html
227.html
228.html
229.html
230.html
231.html
232.html
233.html
234.html
235.html
236.html
237.html
238.html
239.html
240.html
241.html
242.html
243.html
245.html
246.html
247.html
248.html
250.html
251.html
252.html
253.html
254.html
255.html
256.html
257.html
258.html
259.html
260.html
261.html
262.html
263.html
264.html
265.html
266.html
267.html
META-INF
META-INF/container.xml
content.epub
2018/04/02 15:50:15.876 [D] [server.go:2694] 10.94.20.50 - - [02/Apr/2018 03:50:15] "GET /docs/tutem HTTP/1.1 200 0" 0.073661 http://mindoc.skyinno.com/ Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

2018/04/02 15:50:16.132 [D] [server.go:2694] 10.94.20.50 - - [02/Apr/2018 03:50:16] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1 304 0" 0.002135 http://mindoc.skyinno.com/docs/tutem Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

```
一直卡在这里，当我点击其它页面的时候日志又是接着刷新的，并不没有新的报错。同时发现在生成pdf过程中程序内存率在上升，可以占用到16G之多（最后还是没有生成pdf）。
另外，我发现在页面点击生成pdf时，程序日志会先生成epub，但我直接用ebook-convert加html是可以直接使用的，不知道这个有没有关系。

最后，我换过mindoc 0.9和0.10，calibre也换过3.19.0和3.20.0，都是这个问题，而单独使用calibre生成pdf又没有问题，所以我也不知道是mindoc的问题还是calibre的问题了，帮忙看看，谢谢。

**Comment by lifei6671** [comment]
是的，新版本生成文档有个BUG，导致无法生成文档。
Calibre有个问题就是转换文档时会CPU升高。

**Comment by zhashuyu** [comment]
那我应该再降几个版本, 用3.16？

**Comment by lifei6671** [comment]
@zhashuyu 是mindoc的BUG。。

**Comment by zhashuyu** [comment]
我用0.10.1的，可以正常导出PDF了，但有个小bug，如下

`2018/04/08 14:43:58.709 [E] [book_result.go:374] 复制CSS样式出错 => static/css/markdown.preview.css open /opt/mindoc/static/css,/markdown.preview.css: no such file or directory `

应该是book_result.go 373行多了一个","

`373     if err := filetil.CopyFile(filepath.Join(conf.WorkingDirectory, "static", "css", "markdown.preview.css"), filepath.Join(tempOut    putPath, "styles", "css,", "markdown.preview.css")); err != nil {`

我删除试了运行了下没有这个报错了

**Comment by lifei6671** [comment]
嗯，确实是有个BUG。

**Comment by baojian0504** [comment]
我从0.10更新到0.10.1，还是不能导出啊报500错；如下


正在转换 PDF 文件 C:\Users\ADMINI~1\AppData\Local\Temp\fd0426bc0f6ba5b450983aa7541b39a3\a123\output\content.epub
转换PDF文档失败：exec: "ebook-convert": executable file not found in %PATH%
2018/04/10 08:56:08.431 [E] [book_result.go:393] 转换文件错误：Demo2 => exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%
2018/04/10 08:56:08.445 [E] [DocumentController.go:863] 转换文档失败：Demo2 -> exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%

是什么情况呢

**Comment by baojian0504** [comment]
没有啊，干什么用的，下载直接安装就可以了吗要配置什么东西吗

**Comment by baojian0504** [comment]
大神怎么弄得，calibre下载安装了，还是报500

**Comment by lifei6671** [comment]
@baojian0504 请自行查阅手册 https://github.com/lifei6671/mindoc/wiki
