### ISSUE TITLE
產生 PDF  發生問題

### ISSUE THREAD

**Issue by lamb-mei** [lifei6671/mindoc#247]
请按照一下格式提交issue，谢谢！

FROM golang:1.10-alpine3.7
自掛 GLIBC calibre 3.20

直接點匯出PDF 顯示
···
convert to epub
[ebook-convert /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/content.epub /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/output/book.epub]
convert to mobi
[ebook-convert /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/content.epub /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/output/book.mobi]
convert to pdf
[ebook-convert /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/content.epub /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/output/book.pdf --paper-size a4 --pdf-default-font-size 14 --pdf-header-template <p style='color:#8E8E8E;font-size:12px;'>_SECTION_</p> --pdf-footer-template <p style='color:#8E8E8E;font-size:12px;'>本文档使用 <a href='https://www.iminho.me' style='text-decoration:none;color:#1abc9c;font-weight:bold;'>MinDoc</a> 构建 <span style='float:right'>- _PAGENUM_ -</span></p> --pdf-page-margin-left 72 --pdf-page-margin-top 72 --pdf-page-margin-right 72 --pdf-page-margin-bottom 72]
convert to docx
[ebook-convert /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/content.epub /tmp/a06614972fcb89f5f71909a1576a024d/mindoc/output/book.docx --docx-no-toc --docx-page-size a4 --docx-page-margin-left 72 --docx-page-margin-top 72 --docx-page-margin-right 72 --docx-page-margin-bottom 72]
2018/04/03 08:34:28.065 [I] [book_result.go:378] 文档转换完成：MinDoc演示项目 
···

網頁畫面顯示
404 page not found
200

但當再產生的時候，檔案還沒從 /tmp/ 刪除前
有順利複製出
book.epub 
book.mobi
book.pdf
轉換的檔案都是正常的

不知道是什麼問題?

**Comment by lifei6671** [comment]
你是MinDoc哪个版本？

**Comment by lamb-mei** [comment]
前天(4/2 從master clone 下來的沒仔細看版本

使用 docker builder 
我後來在 dockerfile 加上了 glibc 和 calibre 重新做了一個 image
https://github.com/lamb-mei/docker-golang-alpine-glibc-calibre/blob/master/Dockerfile


dockerHub來源是 lambmei/golang-alpine-glibc-calibre
往下加上版主原本 dockerfile 內容應該就可以build 一樣的環境了

**Comment by lifei6671** [comment]
你这个镜像可以实现导出吗？
