### ISSUE TITLE
上传附件类型未说明，且CSV格式不能上传

### ISSUE THREAD

**Issue by zhupaizhang** [lifei6671/mindoc#249]
请在上传福建弹窗中说明具体能上传哪些文件类型。

能否增加Excel类型的上传。

谢谢

**Comment by lifei6671** [comment]
https://github.com/lifei6671/mindoc/wiki/MinDoc-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%A6%E8%A7%A3
