### ISSUE TITLE
匿名访问可具体配置到项目

### ISSUE THREAD

**Issue by qrqhuang** [lifei6671/mindoc#250]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64.zip v0.10.1 

2. 你当前使用的是什么操作系统?
Red Hat

3. 你是如何操作的？
~

4. 你期望得到什么结果?
普通用户可以对具体的项目设置可否匿名访问

5. 当前遇到的是什么结果?
管理员可以全局设置可否匿名访问。
但普通用户不能选择是否公开某个项目。

**Comment by qrqhuang** [comment]
看到创建项目时可以选择是否公开，但创建后未看到可以修改的地方。

**Comment by qrqhuang** [comment]
问题整理一下：
1. 匿名 无法对某个项目单独配置。
2. 是否公开 只在创建时可以选择， 后期无地方修改。

**Comment by lifei6671** [comment]
项目设置里面有设置按钮。
