### ISSUE TITLE
密码忘记了咋办？

### ISSUE THREAD

**Issue by helloxz** [lifei6671/mindoc#252]
未启用邮件服务，因此在线找回密码不可用。想直接修改数据库字段，但是不清楚是怎样加密的。

**Comment by lifei6671** [comment]
去数据库找一个知道密码的密文，更新到数据库就行了。

**Comment by helloxz** [comment]
好吧，也只能这样了，我先在测试环境装一个，把md5复制出来替换，打扰了。
