### ISSUE TITLE
项目文档标识生成有误

### ISSUE THREAD

**Issue by qrqhuang** [lifei6671/mindoc#253]
请按照一下格式提交issue，谢谢！

    - 你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
    mindoc_linux_amd64.zip v0.10.1

    - 你当前使用的是什么操作系统?
    Red Hat

    - 你是如何操作的？
    ~

    - 你期望得到什么结果?
    新项目生成的URL链接中， IDENDITIFY字段使用当前项目的BOOK ID生成。

    - 当前遇到的是什么结果?
    使用的为上一个项目的ID， 用SQL说明问题：

```sql
SELECT
       mb.book_id,
       mb.identify book_identify,
       md.document_id,
       md.identify doc_idendity
FROM
       md_books mb,
       md_documents md
WHERE
       md.book_id = mb.book_id
AND md.book_id = 5;
```

![image](https://user-images.githubusercontent.com/17166063/38747085-3b760d1e-3f7c-11e8-90a4-fd942c6c2cfa.png)

**Comment by lifei6671** [comment]
确实是个BUG，获取项目标识时少传递了一个参数。

**Comment by lifei6671** [comment]
#308
