### ISSUE TITLE
是否有计划支持git？

### ISSUE THREAD

**Issue by ferocknew** [lifei6671/mindoc#255]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
你的意思是用git储存文档吗？
暂时没有这个计划。

**Comment by ferocknew** [comment]
我的建议是，以 git 仓库的方式存储文件，这样，某个项目可以 checkout 出来，本地编辑，然后 push 上去以后，用钩子发布。
类似于，gitbook，这样。那就不仅仅局限于 web 方式编辑和操作了

Minho <notifications@github.com>于2018年4月15日周日 上午11:06写道：

**Comment by lifei6671** [comment]
你可以直接用gitlab，没必要再用其他的了。

**Comment by ferocknew** [comment]
gitlab 是一个专门的 git 服务器。。。我以上的建议是由于使用了 gitbook 和
https://www.kancloud.cn，mindoc 做的很棒，特别是  kancloud 很多功能都实现了，所以才建议，如果能加上 git
，那就相当完美了。

Minho <notifications@github.com>于2018年4月15日周日 下午12:03写道：

**Comment by 120011676** [comment]
+1

**Comment by 596868636** [comment]
+1
