### ISSUE TITLE
导出PDF、DOC等提示：HTTP 500 ： 服务器异常

### ISSUE THREAD

**Issue by gougliang** [lifei6671/mindoc#256]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1

2. 你当前使用的是什么操作系统?
ubuntu 16.04 LTS，手工更新内核到版本：v4.15.13-041513-generic

3. 你是如何操作的？
1）、进入/www/web/mindoc，下载mindoc_linux_amd64.zip，运行unzip解压，./mindoc_linux_amd64 install，提示成功了。
2）、用apt install ebook-convert安装了ebook-convert，运行ebook-convert --version，显示：ebook-convert (calibre 2.55.0)。ebook-convert test.txt test.pdf可以在服务器生成对应pdf。
3）、下载并安装wkhtmltopdf，同时在conf/app.conf设置：wkhtmltopdf=/www/web/mindoc/wkhtmltox/bin/wkhtmltopdf，运行./wkhtmltopdf baidu.com baidu.pdf 可以生成对应pdf。
4）、mindoc网站用IP:8181能访问，用nginx做反向代理也能访问。
5）、看mindoc目录的logs日志文件为0，nginx的错误日志也为0，只有访问日志有记录。
6）、我看演示站点（doc.iminho.me）的导出pdf也是提示HTTP500：服务器异常。

4. 你期望得到什么结果?
我希望在mindoc上面新建的项目，点击下载-导出（/export/mindoc?output=pdf）可以导出pdf、docx。

5. 当前遇到的是什么结果?
现在导出提示：HTTP 500 ： 服务器异常。

**Comment by lifei6671** [comment]
看下控制台导出文档时显示什么错误。

**Comment by hexyi** [comment]
安装 yum install libXcomposite

mkdir css,
cp css/ css,/

2018/04/26 08:37:51.726 [E] [book_result.go:374] 复制CSS样式出错 => static/css/markdown.preview.css open /xxx/mindoc_linux_amd64/static/css,/markdown.preview.css: no such file or directory

**Comment by nic-luo** [comment]
我也遇到了相似的错误，安装calibre之后，将mindoc演示项目能导出PDF格式，但自己的项目就报错，错误信息如下：
正在转换 DOCX 文件 /tmp/985cabfd5cdd0a43e0d97bdf0ab25bbf/rax-arch-doc/output/content.epub
[ebook-convert /tmp/985cabfd5cdd0a43e0d97bdf0ab25bbf/rax-arch-doc/output/content.epub /tmp/985cabfd5cdd0a43e0d97bdf0ab25bbf/rax-arch-doc/output/output/book.mobi]
正在转换 MOBI 文件 /tmp/985cabfd5cdd0a43e0d97bdf0ab25bbf/rax-arch-doc/output/content.epub
[ebook-convert /tmp/985cabfd5cdd0a43e0d97bdf0ab25bbf/rax-arch-doc/output/content.epub /tmp/985cabfd5cdd0a43e0d97bdf0ab25bbf/rax-arch-doc/output/output/book.pdf --paper-size a4 --pdf-default-font-size 14 --pdf-header-template <p style='color:#8E8E8E;font-size:12px;'>_SECTION_</p> --pdf-footer-template <p style='color:#8E8E8E;font-size:12px;'>本文档使用 <a href='https://www.iminho.me' style='text-decoration:none;color:#1abc9c;font-weight:bold;'>MinDoc</a> 构建 <span style='float:right'>- _PAGENUM_ -</span></p> --pdf-page-margin-left 72 --pdf-page-margin-top 72 --pdf-page-margin-right 72 --pdf-page-margin-bottom 72]
正在转换 PDF 文件 /tmp/985cabfd5cdd0a43e0d97bdf0ab25bbf/rax-arch-doc/output/content.epub
转换WORD文档失败：exit status 127
转换MOBI文档失败：exit status 127
转换PDF文档失败：exit status 127
2018/05/08 18:27:35.058 [E] [book_result.go:393] 转换文件错误：RAX1技术架构说明书 => exit status 127
exit status 127
exit status 127 
2018/05/08 18:27:35.059 [E] [DocumentController.go:863] 转换文档失败：RAX1技术架构说明书 -> exit status 127
exit status 127
exit status 127

**Comment by lifei6671** [comment]
安装完了，自己手动执行转换命令看看是不是缺少组件：`ebook-convert test.txt test.pdf`

**Comment by liuyunfeng2017** [comment]
2018/07/06 17:10:05.195 [E] [book_result.go:374] 复制CSS样式出错 => static/css/markdown.preview.css open /usr/local/mindoc/static/css,/markdown.preview.css: no such file or directory

[E] [book_result.go:393] 转换文件错误：myproject => signal: aborted

我也是这个错

**Comment by liuyunfeng2017** [comment]
KiB Mem :  1867048 total,   817244 free,   358488 used,   691316 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  1315112 avail Mem

内存应该够啊，我ebook-convert test.txt test.pdf没有报错
![image](https://user-images.githubusercontent.com/18526469/42372588-302451a4-8145-11e8-8085-dd9a23c61393.png)

**Comment by liuyunfeng2017** [comment]
我能导出了，但是导出的样式变形了
![image](https://user-images.githubusercontent.com/18526469/42373594-fc540f10-8147-11e8-8325-adcc9a553a7e.png)
![image](https://user-images.githubusercontent.com/18526469/42373605-05a0205e-8148-11e8-92b9-e986aaf0b9fb.png)

**Comment by lifei6671** [comment]
@liuyunfeng2017   你的插件应该有问题。升级到最新版试试。
