### ISSUE TITLE
Bug，v0.10.1 添加用户按钮消失

### ISSUE THREAD

**Issue by MyLeoLan** [lifei6671/mindoc#259]
请按照一下格式提交issue，谢谢！

1. 版本：v0.10.1 ?

2. centos7系统，在旧版本的基础上进行升级操作，结果后台用户管理添加用户的按钮消失了！
![image](https://user-images.githubusercontent.com/18298528/38937365-9f24bb3a-4355-11e8-9cf1-e30092f2e667.png)

**Comment by lifei6671** [comment]
没重新你说的BUG。

**Comment by MyLeoLan** [comment]
♪(^∇^*)，我的问题，要用超管登录才行，才发现管理员无法新建用户。
