### ISSUE TITLE
如何手动更改管理员密码

### ISSUE THREAD

**Issue by jxcia** [lifei6671/mindoc#261]
Linux centos 
当前最新版
用的阿里云服务器，无法通过邮件找回密码，是否可以通过手动修改数据库重置管理员密码；

**Comment by jxcia** [comment]
自己解决了，直接去数据库里update，找一个知道密码的其他账号，把他的密码密文直接update给管理员，登陆管理员账号成功；

**Comment by lifei6671** [comment]
邮件找回密码，是需要配置邮件服务器的。

**Comment by jxcia** [comment]
所以我想了一个骚操作，直接在数据库里update密码；



在 2018-04-20 13:26:33，"Minho" <notifications@github.com> 写道：


邮件找回密码，是需要配置邮件服务器的。

**Comment by lifei6671** [comment]
新版本支持通过命令行修改用户密码
