### ISSUE TITLE
希望支持https

### ISSUE THREAD

**Issue by rentaiduo** [lifei6671/mindoc#263]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
没太懂你的意思。
如果想支持HTTPS的话，可以用nginx代理来支持。
如果想使用MinDoc来支持https的话，请参考beego的配置文档 ： https://beego.me/docs/mvc/controller/config.md

**Comment by rentaiduo** [comment]
谢谢！
