### ISSUE TITLE
希望持续发布docker镜像版本并推送官方仓库

### ISSUE THREAD

**Issue by 120011676** [lifei6671/mindoc#266]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
还未使用

2. 你当前使用的是什么操作系统?
还linux

3. 你是如何操作的？
想docker部署

4. 你期望得到什么结果?
持续发布docker镜像版本并推送官方仓库

5. 当前遇到的是什么结果?
docker镜像版本是很久以前的了

**Comment by lifei6671** [comment]
官方仓库国内无法访问。项目已提供Dockerfile文件，建议使用阿里云或者daocloud服务自行编译。
