### ISSUE TITLE
HTTP 500 ： 服务器异常

### ISSUE THREAD

**Issue by xfBryant** [lifei6671/mindoc#267]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1     mindoc_windows_386.7z

2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？
按照安装文档进行安装的，然后配置了导出pdf
配置wkhtmltopdf

导出报错：控制台日志如
[ebook-convert C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277eb9d8a17aebbce38ed3a9f\mindoc\output\content.epub C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277
eb9d8a17aebbce38ed3a9f\mindoc\output\output\book.mobi]
正在转换 MOBI 文件 C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277eb9d8a17aebbce38ed3a9f\mindoc\output\content.epub
转换MOBI文档失败：exec: "ebook-convert": executable file not found in %PATH%
[ebook-convert C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277eb9d8a17aebbce38ed3a9f\mindoc\output\content.epub C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277
eb9d8a17aebbce38ed3a9f\mindoc\output\output\book.pdf --paper-size a4 --pdf-default-font-size 14 --pdf-header-template <p style='color:#8E8E8E;font-size:12px;'>
_SECTION_</p> --pdf-footer-template <p style='color:#8E8E8E;font-size:12px;'>本文档使用 <a href='https://www.iminho.me' style='text-decoration:none;color:#1abc
9c;font-weight:bold;'>MinDoc</a> 构建 <span style='float:right'>- _PAGENUM_ -</span></p> --pdf-page-margin-left 72 --pdf-page-margin-top 72 --pdf-page-margin-r
ight 72 --pdf-page-margin-bottom 72]
正在转换 PDF 文件 C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277eb9d8a17aebbce38ed3a9f\mindoc\output\content.epub
[ebook-convert C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277eb9d8a17aebbce38ed3a9f\mindoc\output\content.epub C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277
eb9d8a17aebbce38ed3a9f\mindoc\output\output\book.docx --docx-no-toc --docx-page-size a4 --docx-page-margin-left 72 --docx-page-margin-top 72 --docx-page-margin
-right 72 --docx-page-margin-bottom 72]
正在转换 DOCX 文件 C:\Users\XF_BRY~1\AppData\Local\Temp\f469653277eb9d8a17aebbce38ed3a9f\mindoc\output\content.epub
转换PDF文档失败：exec: "ebook-convert": executable file not found in %PATH%
转换WORD文档失败：exec: "ebook-convert": executable file not found in %PATH%
2018/04/27 14:44:15.791 [E] [book_result.go:393] 转换文件错误：演示项目 => exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%
2018/04/27 14:44:15.804 [E] [DocumentController.go:863] 转换文档失败：演示项目 -> exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%
exec: "ebook-convert": executable file not found in %PATH%                                                                                                   ent.epub转换PDF文档失败：exec: "ebook-convert": executable file not found in %PATH%转换WORD文档失败：exec: "ebook-convert": executable file not found in %PATH%2018/04/27 14:44:15.791 [E] [book_result.go:393] 转换文件错误：演示项目 => exec: "ebook-convert": executable file not found in %PATH%exec: "ebook-convert": executable file not found in %PATH%exec: "ebook-convert": executable file not found in %PATH%2018/04/27 14:44:15.804 [E] [DocumentController.go:863] 转换文档失败：演示项目 -> exec: "ebook-convert": executable file not found in %PATH%exec: "ebook-convert": executable file not found in %PATH%exec: "ebook-convert": executable file not found in %PATH%D:\a\mindoc_windows_386>dir驱动器 D 中的卷是 WORKS卷的序列号是 EE80-55FED:\a\mindoc_windows_386 的目录2018/04/26  16:28    <DIR>          .2018/04/26  16:28    <DIR>          ..2018/04/26  16:28    <DIR>          static2018/04/26  16:28    <DIR>          viewscutable file not found in %PATH%D:\a\mindoc_windows_386>
 
4. 你期望得到什么结果?
导出pdf、doc等

5. 当前遇到的是什么结果?
HTTP 500 ： 服务器异常

**Comment by lifei6671** [comment]
请看下wiki中的说明文档。安装说明来配置。
