### ISSUE TITLE
最新mysql数据库也连不上，mysql_native_password认证方式，配置文件修改了，其他地方能连接成功

### ISSUE THREAD

**Issue by 120011676** [lifei6671/mindoc#269]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
linux启动

4. 你期望得到什么结果?
正常

5. 当前遇到的是什么结果?
2018/04/27 19:06:58.975 [I] [command.go:32] 正在初始化数据库配置. 
[ORM]2018/04/27 19:07:07 register db Ping `default`, this user requires mysql native password authentication.
2018/04/27 19:07:07.126 [E] [command.go:54] 注册默认数据库失败: register db Ping `default`, this user requires mysql native password authentication. 
[fl@localhost mindoc]$ [ORM]2018/04/27 19:07:07 register db Ping `default`, this user requires mysql native password authentication.
-bash: default: command not found
-bash: [ORM]2018/04/27: No such file or directory
[fl@localhost mindoc]$ 2018/04/27 19:07:07.126 [E] [command.go:54] 注册默认数据库失败: register db Ping `default`, this user requires mysql native password authentication.

**Comment by lifei6671** [comment]
我是用mysql8测试，是可以通过`mysql_native_password`方式登录成功的。

**Comment by 120011676** [comment]
那可能是我这边问题，我使用都不是用最新官方镜像，希望支持docker镜像二进制方式发布
