### ISSUE TITLE
希望能在页面上显示每篇文档最后更新的作者名字

### ISSUE THREAD

**Issue by abowu** [lifei6671/mindoc#273]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.10.1

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
增加新文档

4. 你期望得到什么结果?
因为一个同一本书是由几个人共同完成的，特别是写API文档的时候，希望能在页面上加上文档
是由谁写的，前端对接的时候能找到对应的人。
5. 当前遇到的是什么结果?
没有显示文档的作者

**Comment by lifei6671** [comment]
这个功能建议在文档中以表格的形式列举文档对接人。
实际应用中，写文档的有时候不一定是接口开发人。
