### ISSUE TITLE
希望有单个页面分享的功能

### ISSUE THREAD

**Issue by lovesuri** [lifei6671/mindoc#274]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
    最新版本

2. 你当前使用的是什么操作系统?
   win7

3. 你是如何操作的？
   正常操作   

4. 你期望得到什么结果?
   支持单页分享。也就是项目是私密的，我写了些内容，我只想分享当前的某个页面给其他人看。或者是多个界面，支持同一个访问密钥，这样就不用建很多的项目分享给人了

5. 当前遇到的是什么结果?
  没法分享单个页面

**Comment by lifei6671** [comment]
新版本可以用文章管理文档来实现单页分享。
