### ISSUE TITLE
数据库是否支持MariaDB Galera Cluster

### ISSUE THREAD

**Issue by yzp920626** [lifei6671/mindoc#277]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
 v0.10

2. 你当前使用的是什么操作系统?
CentOS release 6.7 (Final)

3. 你是如何操作的？
当前配置的是单台mysql. 为了高可用以及担心数据库数据丢失，想改为配置MariaDB Galera Cluster，现在有两个节点如10.168.74.10，10.168.74.9。数据库应该怎么配置。

4. 你期望得到什么结果?
支持配置数据库集群。db_host支持多主机，这样一个数据库挂了，其他节点还可用.

5. 当前遇到的是什么结果?
db_host只支持单主机配置。

**Comment by lifei6671** [comment]
目前还不支持您说的集群。
MinDoc是小型项目，还达不到使用集群的地步。

**Comment by yzp920626** [comment]
恩 感谢 ! 暂时通过在集群前加HAProxy实现了配置集群。
