### ISSUE TITLE
mindoc上传图片能否支持保存到数据库

### ISSUE THREAD

**Issue by yzp920626** [lifei6671/mindoc#278]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10

2. 你当前使用的是什么操作系统?
CentOS release 6.7 (Final)

3. 你是如何操作的？
----

4. 你期望得到什么结果?

mindoc图片文件也支持保存到数据库，而不是只能保存在/uploads，该目录可以作为缓存目录。

5. 当前遇到的是什么结果?

mindoc图片文件不能保存到数据库，担心目录误删。

**Comment by lifei6671** [comment]
目前没有任何系统会将图片变成到数据库。

**Comment by iHTCboy** [comment]
也不是没有办法，图片转Base64就可以，但是这不合适，有需要的朋友自己做吧。
