### ISSUE TITLE
文章有特殊符号会保存失败

### ISSUE THREAD

**Issue by DariusG4** [lifei6671/mindoc#279]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
版本比较老，201801月份的版本，程序不支持查看版本，无法给出具体版本

2. 你当前使用的是什么操作系统?
CentOS6.5

3. 你是如何操作的？
正常编辑，添加sql或者文档中出现*  ~ 等符号后，保存失败，所有编辑数据全部丢失

4. 你期望得到什么结果?
希望修复该bug

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
请升级到最新版本试试。

**Comment by DariusG4** [comment]
已升级到最近文档，使用中发现，如果输入from单词，保存的时候就会出问题。旧版本会一直加载。新版本的会提示 “ 服务器错误：Method Not Allowed ” ，console中会报错： POST  http://****/api/yw/content/  405 （Method Not Allowed ） jquery.min.js:4 。
怪异的是：第一篇文档可以保存并发布出去，但是再次修改该文档或者新建文档编辑保存同样的sql就会报错。
是想保存sql的时候发现的问题，from用代码块引起来也报错。

**Comment by lifei6671** [comment]
能不能将你出错的文档内容发一下呢？我测试试试。

**Comment by DariusG4** [comment]
```sql
select * from abc;
```
或者文档中任何位置有from 这个单词，就会出现问题。

**Comment by lifei6671** [comment]
你试试演示站会出现这个问题吗？我测试没发现您说的这个问题。
或者看看你的服务器是不是使用了某些安全软件呢？

**Comment by DariusG4** [comment]
演示站不会出这个问题，真奇怪。。。

**Comment by lifei6671** [comment]
猜测是你的服务器安装了某种安全拦截软件，拦截了指定关键字。
