### ISSUE TITLE
再次编辑文档（目录）后，顺序与编辑时不一致

### ISSUE THREAD

**Issue by longxi** [lifei6671/mindoc#280]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1

2. 你当前使用的是什么操作系统?
Windows 7

3. 你是如何操作的？
新建项目并创建一些文档后，再次编辑此项目，新增一些文档。

4. 你期望得到什么结果?
目录顺序与编辑时保持一致

5. 当前遇到的是什么结果?
文档顺序乱了。官网测试，存在同样BUG：
![2018-05-17_1](https://user-images.githubusercontent.com/252003/40162897-df58757c-59e7-11e8-853b-2e8711052e9c.png)

经检查是再次编辑项目时，新增的文档数据库中 “order_sort” 为 0 ，导致排序不正常。

**Comment by lifei6671** [comment]
您的意思是说编辑的排序和阅读的顺序不一致吗？

**Comment by longxi** [comment]
没有同时操作
你可以看看官网这个项目：[http://doc.iminho.me/docs/itloginid?token=5OE99Nmc6B0w](http://doc.iminho.me/docs/itloginid?token=5OE99Nmc6B0w)，顺序测试、666、777 是后来加的，在最下面，但阅读时，位置却在中间。
你也可以找一个其他项目新增几个文档试试看。

**Comment by lifei6671** [comment]
新版修复了这个问题，请升级后尝试。
