### ISSUE TITLE
编辑文档界面中文乱码

### ISSUE THREAD

**Issue by vlanif** [lifei6671/mindoc#281]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by vlanif** [comment]
1.版本：v0.10.1.7
2.系统：centos7.5
3.首页-点击项目-点击编辑
4.中文格式正常显示
5.中文格式乱码

**Comment by lifei6671** [comment]
请问是中文格式乱码还是不乱吗？

**Comment by Ken-Liu-1986** [comment]
我这里也是碰到中文乱码问题，最新版本的，linux编译后的版本，mysql是utf-8编码

**Comment by lifei6671** [comment]
wiki中已经明确说明的mysql的数据库编码必须是**utf8mb4**。

**Comment by vlanif** [comment]
我的的utf8mb4也不行，应该是js报错了

**Comment by lifei6671** [comment]
能发个截图吗？

**Comment by Ken-Liu-1986** [comment]
![image](https://user-images.githubusercontent.com/8413489/40302005-65b1598c-5d20-11e8-965e-755d90d189f1.png)

**Comment by lifei6671** [comment]
有没有试过演示站是否乱码？或者尝试清空下浏览器缓存。另外，你的项目部署再什么服务器下？有没有使用代理？

**Comment by lifei6671** [comment]
Nginx中加上 `charset utf-8;`配置试试。

**Comment by vlanif** [comment]
加过此配置还是没解决

**Comment by vlanif** [comment]
谢谢，现在已经解决了，是代理的配置问题

**Comment by Ken-Liu-1986** [comment]
恭喜解决了，我这边没用任何代理，就是直接启动自带的服务器脚本，系统版本也是 centos7.5

**Comment by lifei6671** [comment]
@Ken-Liu-1986 你访问演示站会乱码吗？

**Comment by Ken-Liu-1986** [comment]
@lifei6671 演示站不会是乱码，目前我这边的环境参数我汇总一下：
系统：centos7.5
MinDoc ：昨天下载的最新编译后的版本

发现问题及安装过程：
1、下载压缩包
2、解压
3、配置conf里的数据库地址
4、将数据库改为utf8mb4并重启
5、运行解压后文档里的 mindoc_linux_amd64
6、编写中文文档，保存刷新后发现是乱码

**Comment by lifei6671** [comment]
@Ken-Liu-1986 你看下你的数据库表是不是utf8mb4格式的。或者访问静态文件看看是不是乱码？

**Comment by Ken-Liu-1986** [comment]
@lifei6671 哥们，谢谢提醒，真的是表的编码的问题，修改数据库编码而表的编码居然没有跟着变。非常感谢，你分享的wiki项目非常棒，虽然小但是简单实用，很好。谢谢
