### ISSUE TITLE
权限控制失效 和 连续创建项目无法提交

### ISSUE THREAD

**Issue by Ken-Liu-1986** [lifei6671/mindoc#282]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

mindoc_linux_amd64.zip v0.10.1

2. 你当前使用的是什么操作系统?

centOs 7.5

3. 你是如何操作的？
1、创建了5个项目，创建2个账号，其中一个是访客账，仅开发其中一个项目给访客账号访问，并设置为观察者，结果访客账号可以看到所有的项目。

2、连续创建项目时，无法提交新的项目，点击提交按钮无效

3、希望设置项目的人员可以更方便一点，比如左边是人右边是项目，相互打勾勾的方式来设定

4. 你期望得到什么结果?

 解决遇到的BUG

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
访客可以看到什么项目取决于项目的权限设置。

**Comment by Ken-Liu-1986** [comment]
是的，但是请仔细看我的描述 

“创建了5个项目，创建2个账号，其中一个是访客账号，仅开放其中一个项目给访客账号访问，并设置为观察者，结果访客账号可以看到所有5个项目。”

**Comment by lifei6671** [comment]
你的访客账户是管理员权限还是普通用户权限？

**Comment by Ken-Liu-1986** [comment]
普通用户

**Comment by lifei6671** [comment]
我测试没发现您说的这个问题。

**Comment by Ken-Liu-1986** [comment]
这么神奇，我删掉重建一个看看，那连续创建项目也是一个问题，麻烦您检查看看

**Comment by lifei6671** [comment]
连续创建项目确实是一个BUG，之前有人提出了。

**Comment by lifei6671** [comment]
连续创建项目的问题新版已修复。
