### ISSUE TITLE
是否支持配置指定的图片存储目录

### ISSUE THREAD

**Issue by yzp920626** [lifei6671/mindoc#283]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
   v1.0
2. 你当前使用的是什么操作系统?
centos6.5
3. 你是如何操作的？
/
4. 你期望得到什么结果?
上传的图片文件可以通过配置指定上传到特定的存储目录，比如存储到共享磁盘。
5. 当前遇到的是什么结果?
当前上传的图片都是保存在/uploads目录下，能否支持配置。

**Comment by lifei6671** [comment]
目前支持指定项目的工作目录，但是无法单独指定uploads目录。您可以用软连接来实现转移到其他磁盘上。

**Comment by yzp920626** [comment]
谢谢！再请教下，指定项目的工作目录要怎么指定的？

**Comment by lifei6671** [comment]
https://github.com/lifei6671/mindoc/wiki/MinDoc-%E4%B8%AD%E7%9A%84%E5%91%BD%E4%BB%A4
