### ISSUE TITLE
Html编辑器中的内容太大无法保存

### ISSUE THREAD

**Issue by wivd** [lifei6671/mindoc#284]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  v0.10.1
MinDoc last version =>  v0.10.1

2. 你当前使用的是什么操作系统?
Debian 4.15.17-1

3. 你是如何操作的？
我有两个html文件 ，aaaa.html和bbb.html 两个文件的大小不一样
-rw-r--r-- 1 root root 861K 5月  27 01:27 /root/下载/aaaa.html
-rw-r--r-- 1 root root 7.7M 5月  27 01:34 /root/下载/bbb.html
使用Html编辑器复制bbb.html文件的内容时，编辑器中内容可见，在保存的时候，保存失败
估计程序对文件的大小做了限制，所以文件内容无法保存
4. 你期望得到什么结果?
能保存的文件大小做成配置项在app.conf中，大小可以自定义

5. 当前遇到的是什么结果?
Html编辑器中的内容太大无法保存

**Comment by lifei6671** [comment]
这是golang语言的一个限制，对post编码后的值大于10M的解析会被截断，导致后台的数据有问题。
建议你将大文件分开多个小文件吧。
