### ISSUE TITLE
希望增加文章自动采集功能

### ISSUE THREAD

**Issue by wivd** [lifei6671/mindoc#285]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version => v0.10.1
MinDoc last version => v0.10.1

2. 你当前使用的是什么操作系统?
Debian 4.15.17-1

3. 你是如何操作的？

4. 你期望得到什么结果?
希望增加文章自动采集功能，可以根据url自动采集文章的内容，可以下载图片。
现在很多开源的云笔记、知识管理系统等都没有这个功能，而这个功能是很多人希望有的。如果实现此功能后，相信mindoc适用的场景将会更多。（beibq实现了此功能）

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
如果您需要采集功能可以使用BookStack，这个是基于mindoc二次开发，适合公司运营。
MinDoc是针对公司内部文档管理开发的。

**Comment by wivd** [comment]
谢谢
