### ISSUE TITLE
Markdown编辑器中复制粘帖图片时，图片的地址是完成url

### ISSUE THREAD

**Issue by wivd** [lifei6671/mindoc#286]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version => v0.10.1
MinDoc last version => v0.10.1

2. 你当前使用的是什么操作系统?
Debian 4.15.17-1

3. 你是如何操作的？
Markdown编辑器中复制粘帖图片时，图片的地址是完整的url，
http://192.168.1.109:8181/uploads/201805/intranet/attach_15324501eeecffc1.png

4. 你期望得到什么结果?
图片的地址取uri部分，使用相对路径
/uploads/201805/intranet/attach_15324501eeecffc1.png
5. 当前遇到的是什么结果?
Markdown编辑器中复制粘帖图片时，图片的地址是完整的url，
http://192.168.1.109:8181/uploads/201805/intranet/attach_15324501eeecffc1.png
图片地址为完整的url，当服务器地址有变更时，图片将无法显示

**Comment by lifei6671** [comment]
你可以在配置文件配置完整的`baseurl`值为域名。
