### ISSUE TITLE
支持项目的直接复制.

### ISSUE THREAD

**Issue by yzp920626** [lifei6671/mindoc#289]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.10

2. 你当前使用的是什么操作系统?
centos 6.7

3. 你是如何操作的？
将项目以Markdown形式导出，再导入，目录结构会乱。

4. 你期望得到什么结果?
支持项目的复制，比如我一个项目文档需存在两个版本，V1.0和V1.1。直接复制一个V1.0的文档，命名为V1.1，在此上修改。这样两个版本都可以存在。

5. 当前遇到的是什么结果?
使用导入导出的方式复制，新导入的文档的层级目录会乱。

**Comment by lifei6671** [comment]
新版本已支持复制项目。
