### ISSUE TITLE
导出时能否选择只导出单个文档，而不是整个项目呢

### ISSUE THREAD

**Issue by llxssfm** [lifei6671/mindoc#290]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1
2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
导出操作

4. 你期望得到什么结果?
希望不仅导出整个项目，而且可以导出单个文档。

5. 当前遇到的是什么结果?
导出时只能导出整个项目。

**Comment by lifei6671** [comment]
目前功能是导出整个项目，不是的单个文档额。

**Comment by lifei6671** [comment]
新版本增加了打印功能，可通过Chrome的打印功能导出PDF单页文档。
