### ISSUE TITLE
公开项目进行分享时不需要他人登录也可以查看功能

### ISSUE THREAD

**Issue by BoomManPro** [lifei6671/mindoc#296]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

MinDoc current version =>  v0.10.1
MinDoc last version =>  v0.10.1

2. 你当前使用的是什么操作系统?

Windows7

3. 你是如何操作的？

chrome在公开项目页面 点击分享;复制链接到fireFox 需要进行登录操作
4. 你期望得到什么结果?

不需要登录也可以查看；因为我认为是公开项目

5. 当前遇到的是什么结果?

需要进行登录才可以查看

**Comment by lifei6671** [comment]
需要将系统设置为匿名访问才可以。否则不行。

**Comment by BoomManPro** [comment]
问题已解决，perfect

**Comment by igo9go** [comment]
@lifei6671  建议在新增一种文档类型可以任意登陆的人一起编辑，现在要能实现只能每个人一个个添加到项目成员

**Comment by lifei6671** [comment]
@igo9go 你这个需求太小众。
