### ISSUE TITLE
希望可以集成ldap

### ISSUE THREAD

**Issue by feiyan35488** [lifei6671/mindoc#3]
这样能方便的接入公司的员工系统

**Comment by lifei6671** [comment]
不太明白集成ldap是什么意思。能详细说说吗？

**Comment by feiyan35488** [comment]
在后台管理那里添加ldap配置，这样ldap中的用户就可以直接登录godoc。这样只需要维护一份用户信息及可

**Comment by feiyan35488** [comment]
比如 gitlab、mediawiki 都可以支持ldap

**Comment by feiyan35488** [comment]
这样的产品肯定是为中小企业服务的，因此支持ldap应该是标配。企业不会为多个系统维护多份用户信息的，肯定要统一维护

**Comment by naokij** [comment]
[LDAP有关的资料](http://blog.csdn.net/xufaxi/article/details/5703516)

下面是一段ldap登录的验证代码

`func validLDAPLogin(form *AdminLoginForm) (result bool, err error) {
	result = false
	err = nil
	lc, err := ldap.Dial("tcp", fmt.Sprintf("%s:%d", config.Config.LDAP.Host, config.Config.LDAP.Port))
	if err != nil {
		return
	}
	defer lc.Close()
	err = lc.Bind(config.Config.LDAP.User, config.Config.LDAP.Password)
	if err != nil {
		return
	}
	searchRequest := ldap.NewSearchRequest(
		config.Config.LDAP.Base,
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		fmt.Sprintf("(&(objectClass=User)(%s=%s))", config.Config.LDAP.Attribute, form.Email),
		[]string{"dn"},
		nil,
	)
	searchResult, err := lc.Search(searchRequest)
	if err != nil {
		return
	}
	if len(searchResult.Entries) != 1 {
		err = errors.New("ldap.no_user_found_or_many_users_found")
	}
	userdn := searchResult.Entries[0].DN

	err = lc.Bind(userdn, form.Password)
	if err == nil {
		result = true
	} else {
		err = nil
	}
	return
}`

**Comment by naokij** [comment]
@lifei6671 更新了gist，有需要帮助可以跟我讲

**Comment by lifei6671** [comment]
请教下，怎么搭建ldap服务？我尝试搭建，发现不成功。

**Comment by feiyan35488** [comment]
https://github.com/osixia/docker-openldap  ldap的docker镜像

**Comment by naokij** [comment]
@lifei6671 还有一个办法是用windows建一个域控制器
http://jingyan.baidu.com/article/3c48dd3491921fe10be35839.html

**Comment by lifei6671** [comment]
@naokij 请问下你的gist代码里面第 38 行，我这么用为啥一直报错呢？

```
err = lc.Bind("CN=ldap helper,OU=minho.com,DC=minho.com,DC=com", "123456")
```
密码是我初始化的LDAP_ADMIN_PASSWORD密码。用的是 https://github.com/osixia/docker-openldap  这个镜像。

一直报 ： `LDAP Result Code 49 "Invalid Credentials":`

**Comment by naokij** [comment]
@lifei6671 应该是login dn的部分错了，如果是这个镜像，安装出来的admin login dn应该是
`cn=admin,ou=minho.com,dc=mingho,dc=com`，正式环境不推荐这样用，admin的权限很大，应该再单独建立一个小一点权限的用户来做第一次绑定

**Comment by naokij** [comment]
请问测试顺利么？是否需要其他帮助？

**Comment by lifei6671** [comment]
@naokij 能够访问，但是对ldap的整体结构不了解。
我不太清楚，是不是就算每个公司的组织结构不一样，我也能通过一个公共的dn来查找用户呢？

**Comment by naokij** [comment]
@lifei6671 一般的Active Directory或者openLDAP，用户是可以看到其他用户的基本资料的(email, 名字等），这就是第一次验证的目的，要去AD/LDAP里面找到用户输入的用户名对应的LDAP用户，再进行第二次验证。所以是这种做法是比较通用的方式。很多年前学的AD，不确定是否会有用户A看不到用户B的情况，如果有，那这公司的IT一定知道要用哪一个用户做第一次验证。

**Comment by lifei6671** [comment]
@naokij 也就是说，只要我第二次验证通过，就表示存在这个用户是吧。那么，DN中的ou和dc部分是必须的吗？

**Comment by naokij** [comment]
@lifei6671 第一次验证通过之后，进行的那次查询，确认存在用户输入的用户名，第二次验证确认输入的密码正确。DN中的CN,OU,DC是必须的

**Comment by lifei6671** [comment]
@naokij 如果是必须的话，怎么才能写出通用的代码呢？我赶紧不同公司的OU可能都不一样，或者一个公司可能有多个OU吧。

**Comment by naokij** [comment]
@lifei6671 第一步验证的DN是在配置文件或者系统管理界面里面设定的，直接设定DN，这样避免不同公司AD/LDAP结构不一样的问题，第二步验证的DN是直接从LDAP的搜索结果里面取的，不必担心DN有错误

**Comment by naokij** [comment]
@lifei6671 等不及你的更新，我自己实现了这个功能，#39  可是godeps跟 vendor的部分搞不定 
请看一下

**Comment by lifei6671** [comment]
@naokij 太感谢啦，最近一直忙着适配sqlite，没来得及开发ldap。明天上班了我合并代码。

**Comment by naokij** [comment]
@lifei6671 你 还需要更新下godeps 跟vendor，我不熟悉godeps，所以没有更新

**Comment by naokij** [comment]
@lifei6671 增加了LDAP认证之后，还需要额外的改动
*  LDAP认证的用户，不应允许修改密码，密码应从LDAP那边修改
*  找回密码功能，不应该对LDAP认证用户开放

**Comment by lifei6671** [comment]
@naokij 好的。
