### ISSUE TITLE
linux 下运行，无法添加项目

### ISSUE THREAD

**Issue by yangyufans** [lifei6671/mindoc#300]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
按照以下文档操作的
https://github.com/lifei6671/mindoc/wiki/Linux-下安装和配置-MinDoc

4. 你期望得到什么结果?
可以正常添加项目

5. 当前遇到的是什么结果?
保存项目失败，后端报错
2018/06/24 22:06:47.532 [E] [asm_amd64.s:573] Insert =>  Error 1210: Incorrect arguments to mysqld_stmt_execute

**Comment by lifei6671** [comment]
去演示站测试下能够添加？
看看你的数据库编码是不是utf8mb4格式。
