### ISSUE TITLE
关于：数据库升级命令： migrate

### ISSUE THREAD

**Issue by viaco2ove** [lifei6671/mindoc#301]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
 godoc_windows_amd64 0.10.1

2. 你当前使用的是什么操作系统?
 godoc_windows_amd64  windows7

3. 你是如何操作的？
 godoc_windows_amd64.exe migrate

4. 你期望得到什么结果?
更新数据库

5. 当前遇到的是什么结果?
goroutine 1 [running]:
container/list.(*List).Front(...)
        C:/go/src/container/list/list.go:70
github.com/lifei6671/mindoc/commands/migrate.RunMigration()
        c:/gopath/src/github.com/lifei6671/mindoc/commands/migrate/mig
 +0x16a
github.com/lifei6671/mindoc/commands.RegisterCommand()
        c:/gopath/src/github.com/lifei6671/mindoc/commands/command.go:

main.main()
        c:/gopath/src/github.com/lifei6671/mindoc/main.go:29 +0x104

6.建议
这行代码请问有什么用的
//migrate.RegisterMigration()
去掉注释就可以运行了

**Comment by lifei6671** [comment]
这个命令是老版本合并数据使用的，目前的版本是弃用的。

**Comment by viaco2ove** [comment]
好的谢谢

**Comment by qrqhuang** [comment]
> 本次更新修改了数据库结构，升级前请先备份原程序和数据库。

请问该类升级， 也可以直接通过install更新吗？
