### ISSUE TITLE
建议增加个开启目录自动暂开的功能，有些情况下需要

### ISSUE THREAD

**Issue by blackboar** [lifei6671/mindoc#302]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
v0.13版本支持设定自动展开。
