### ISSUE TITLE
请问分享的时候，可以让用户不登陆久看到分享的页面么

### ISSUE THREAD

**Issue by yuedingwangji** [lifei6671/mindoc#303]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1

2. 你当前使用的是什么操作系统?
win10

5. 当前遇到的是什么结果?
我希望点击分享之后，生成的url，任何人都可以打开查看文档内容，而不是需要在登陆一次

**Comment by lifei6671** [comment]
你需要将mindoc设置为匿名访问，同时项目也是公开的。
