### ISSUE TITLE
首页自定的封面地址未渲染？

### ISSUE THREAD

**Issue by jiaoshengkang** [lifei6671/mindoc#306]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1 更新日志
@lifei6671 lifei6671 released this on 3 Apr
Assets
14.4 MB mindoc_linux_amd64.zip
https://github.com/lifei6671/mindoc/releases/download/v0.10.1/mindoc_linux_amd64.zip

2. 你当前使用的是什么操作系统?
centos

3. 你是如何操作的？
编辑项目封面，返回首页，封面查看不了，显示默认封面。

4. 你期望得到什么结果?
首页封面也可以显示。

5. 当前遇到的是什么结果?
首页封面<img的src地址不是我自己上传之后的地址。

**Comment by lifei6671** [comment]
我测试没发现你说的问题。请尝试在演示站上重试下。

**Comment by jiaoshengkang** [comment]
我使用了项目前缀这个配置：例如：localhost/midoc，app.conf中配置：baseurl=/mindoc

**Comment by lifei6671** [comment]
baseurl需要填写完整的域名和二级目录。文档里面有说到的。

**Comment by jiaoshengkang** [comment]
好的，我试试，谢谢
