### ISSUE TITLE
mysql初始化数据库配置报错

### ISSUE THREAD

**Issue by xuanzebi** [lifei6671/mindoc#307]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.10.1

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
linux启动

4. 你期望得到什么结果?
正常

5. 当前遇到的是什么结果?
[hanyaopeng@localhost mindoc]$ ./mindoc_linux_amd64 install
2018/07/09 05:18:15.289 [I] [command.go:32] 正在初始化数据库配置. 
[ORM]2018/07/09 05:18:15 register db Ping `default`, this authentication plugin is not supported
2018/07/09 05:18:15.289 [E] [command.go:54] 注册默认数据库失败: register db Ping `default`, this authentication plugin is not supported

**Comment by lifei6671** [comment]
mysql数据库只支持mysql5.7版本，且数据库编码必须是utf8mb4，认证方式只支持本地密码认证。

**Comment by xuanzebi** [comment]
好的 谢谢了
