### ISSUE TITLE
请问添加文档功能中的文档标识默认以什么生成的

### ISSUE THREAD

**Issue by blackboar** [lifei6671/mindoc#308]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc version => v0.10.1

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？

4. 你期望得到什么结果?
以项目标识加时间戳或者随机字符

5. 当前遇到的是什么结果?
现在遇到比较奇怪的情况，比如前几天加了个叫做centos笔记的，项目标识是 cenots-note ，今天又加了个项目叫windows手册，项目标识windows，但是这个windows项目建立的文档系统默认都会把标识成 cenots-note-31530869377 这样，即使刷新缓存（chrome隐身模式）也同样不会变掉，很奇怪

**Comment by lifei6671** [comment]
这是个BUG。下个版本会修复。

**Comment by blackboar** [comment]
@lifei6671  下个版本预计什么时候发布，我这批文档栏目太多，改起来工作量比较大，要么我等到更新

**Comment by lifei6671** [comment]
如果工作不忙的话这周吧，还有一个项目复制功能没开发完。

**Comment by xuanzebi** [comment]
顺便问一下下个版本能支持mysql最新版本吗

**Comment by lifei6671** [comment]
@xuanzebi 连接MySQL的库是第三方提供的，目前这个库没有支持8.0的正式版。

**Comment by lifei6671** [comment]
新版本已发布，请升级到最新版本。
