### ISSUE TITLE
怎么配置让用户登录永不超时

### ISSUE THREAD

**Issue by yuedingwangji** [lifei6671/mindoc#309]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新的

2. 你当前使用的是什么操作系统?
win7

3. 你是如何操作的？

4. 你期望得到什么结果?
怎么配置让用户登录永不超时

**Comment by lifei6671** [comment]
只要session不过期，用户cookie不过期，就永不超时。

**Comment by yuedingwangji** [comment]
我现在是浏览器登录，  几个小时后，又得重新登录了

**Comment by lifei6671** [comment]
很正常，浏览器不保证你的cookie永不过期。而且，服务器端的session也可能丢失。

**Comment by yuedingwangji** [comment]
那我这边能做什么让 cookie永不过期么

**Comment by yuedingwangji** [comment]
是不是可以在头部配置浏览器缓存cookies 的时间？

**Comment by lifei6671** [comment]
理论上在代码中可以设置cookie超长过期时间。

**Comment by yuedingwangji** [comment]
请问这个理论具体怎么实现

**Comment by lifei6671** [comment]
请自行去看源码。

**Comment by yuedingwangji** [comment]
大佬，我不是开发， 能指导一下么
