### ISSUE TITLE
用户注册提示“注册失败请联系管理员”

### ISSUE THREAD

**Issue by jiangtao007** [lifei6671/mindoc#310]
请按照一下格式提交issue，谢谢！
1.你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
最新的
2.你当前使用的是什么操作系统?
centos6
3.你期望得到什么结果?
 目前开放用户注册。但是在大概有20多个用户注册后，发现再进行注册时会提示“注册失败请联系管理员”。请问这个问题我可以从哪块来查log。或者是哪个地方出现了问题。多谢！

**Comment by lifei6671** [comment]
看看注册失败的用户日志提示什么异常。

**Comment by jiangtao007** [comment]
请问一下在哪里可以看相关日志，我找很久没找到

**Comment by lifei6671** [comment]
可以从控制台上看，也可以从runtime/logs目录中看。

**Comment by qrqhuang** [comment]
注册返回`6006-注册失败，请联系系统管理员处理`

日志级别为`Debug`,  但只有如下输出

> 2018/11/02 11:26:20.844 [I] [asm_amd64.s:2361]  http server Running on http://:8181
