### ISSUE TITLE
讨论：为什么不做成"保存即发布"

### ISSUE THREAD

**Issue by leofantast** [lifei6671/mindoc#311]
目前线上版本是0.11，使用Mindoc已有一年。

经过我的测试：
1. 如果不"保存"，直接点"发布"，下次打开是没有内容的
2. "保存"后，下次打开要进入编辑页面才看到上次保存的内容
3. "发布"没有快捷键，为了不丢失文档，导致我现在养成了经常点击发布按钮的强迫症，很痛苦。。。

我的疑惑是为什么不做成"保存即发布"，是出于产品还是技术的考量？就我个人的体验，
"保存即发布"是最简单最直接的方式，换句话说"发布"这个功能完全不需要存在。

如果你也有和我一样的疑惑，欢迎讨论~

**Comment by lifei6671** [comment]
请在项目设置中设置为自动发布。
另外，发布功能是为了减少大批量操作数据对数据库的压力。如果你的文档很少，用户很少可以自动发布。

**Comment by leofantast** [comment]
@lifei6671 Thanks! 

没注意更新日志，之前用的版本没有自动发布功能，刚测试了新版好用，感谢~
