### ISSUE TITLE
v0.11 升级后，项目导出功能无效

### ISSUE THREAD

**Issue by yrr626** [lifei6671/mindoc#312]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64.7z v0.11

2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？
点击下载word,页面显示 HTTP 200 ： 文档正在后台转换，请稍后再下载
，隔了一段时间，
再刷新页面，提示HTTP 500 ： 导出失败，请查看系统日志 无法下载

4. 你期望得到什么结果?
能够下载，现回退版本到v0.10版本

5. 当前遇到的是什么结果?
HTTP 500 ： 导出失败，请查看系统日志 无法下载

**Comment by yrr626** [comment]
@lifei6671 如上，新建的空文档，然后点下载，隔一段时间点刷新或者重新点下载均显示500

**Comment by lifei6671** [comment]
是提示的文本问题，等后台导出执行完成了就可以下载了。下个版本会优化这个提示。

**Comment by yrr626** [comment]
@lifei6671 你好，是这样的，我同样的内容 用旧版可以很快导出，但是新版本导出之后，后台日志并不会转换，很奇怪，登陆5-10分钟任然导不出，还是提示500。空文档应该导出速度很快才对的。
