### ISSUE TITLE
Mac OS怎样以服务的方式运行MinDoc

### ISSUE THREAD

**Issue by sonwa** [lifei6671/mindoc#313]
请问Mac OS怎样以服务的方式运行MinDoc？我已经编译成功可以正常运行，但我现在想以服务方式在后台自运行，请问要怎样设？

**Comment by lifei6671** [comment]
目前暂时不支持Mac OS系统。

**Comment by sonwa** [comment]
已经可以了，用LaunchRocket加入服务就可以实现开机自运行了
