### ISSUE TITLE
外链图片无法加载

### ISSUE THREAD

**Issue by heruigit** [lifei6671/mindoc#314]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.11
2. 你当前使用的是什么操作系统?
Ubuntu 16.04.3 LTS
3. 你是如何操作的？
markdown文档中插入图片外链
4. 你期望得到什么结果?
正常显示图片
5. 当前遇到的是什么结果?
图片无法加载

**Comment by lifei6671** [comment]
请检查您的图片是否正常访问。
