### ISSUE TITLE
问下 为什么用python做pdf导出,而不是用go做导出呢?

### ISSUE THREAD

**Issue by kasnet** [lifei6671/mindoc#315]

**Comment by kasnet** [comment]
是, 如果有精力可以尝试写这个类库, 我看有个类库https://github.com/janczer/htmlPDF   在做这个, 但是不支持中文,  大致的原理是差不错的

**Comment by lifei6671** [comment]
支持的有限，根本没办法导出符合网页看到的样式。
一般HTML转PDF会采用Chrome来处理，但是这个在linux比较复杂。
