### ISSUE TITLE
附近大小

### ISSUE THREAD

**Issue by 596868636** [lifei6671/mindoc#317]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新版

2. 你当前使用的是什么操作系统?
centos7.4 docker

3. 你是如何操作的？
编辑-》附件（或者粘贴大一点的截图）
4. 你期望得到什么结果?
能正确上传

5. 当前遇到的是什么结果?

提示413 Request Entity Too Large

我不知道是docker nginx配置限制来大小还是go语言上有限制？需要哪里配置？

**Comment by lifei6671** [comment]
Nginx的限制。请自行百度或谷歌。
