### ISSUE TITLE
go菜鸟新人提问

### ISSUE THREAD

**Issue by xinli1234** [lifei6671/mindoc#318]
Windows系统，用的是godoc64的版本
我想在controller中打日志，但是运行编译后的.exe文件没有显示，改为fmt输出也不行
还有我直接go run main.go 的时候会报这个错误  读取字体文件时出错 -> open C:\Users\admin\AppData\Local\Temp\go-build963970958\b001\exe\static\fonts: The system cannot find the path specified
还有在查看附件的时候会报500

以上，主要是日志和printf 不能打印，这个怎么解决

**Comment by xinli1234** [comment]
Windows系统，用的是godoc64的版本
我想在controller中打日志，但是运行编译后的.exe文件没有显示，改为fmt输出也不行
还有我直接go run main.go 的时候会报这个错误 读取字体文件时出错 -> open C:\Users\admin\AppData\Local\Temp\go-build963970958\b001\exe\static\fonts: The system cannot find the path specified
还有在查看附件的时候会报500

以上，主要是日志和printf 不能打印，这个怎么解决

**Comment by lifei6671** [comment]
请自行百度学习golang的基础知识。
