### ISSUE TITLE
0.12版本，快速连续点击显示“加载失败”

### ISSUE THREAD

**Issue by wakahuala** [lifei6671/mindoc#319]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？
升级到最新0.12版本，单次慢速单击一个文档的章节链接可以正常加载文字，但当快速连续点击连接时加载不出文字，显示“加载失败”

4. 你期望得到什么结果?
正常加载文字

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
为什么要快速点击呢？
文章加载是需要时间的。

**Comment by wakahuala** [comment]
@lifei6671   意思是鼠标点击的速度快了些那种，不是有意没事就快速点击。不过之前旧版本是不会报错的，点击再快也会慢慢加载出来。另外加载有问题的文档，只要重新创建粘贴文字过去，就正常了，再怎么快速点击也不会报错。

**Comment by lifei6671** [comment]
我没重现你说的问题，能详细描述下怎么重现的吗？

**Comment by lizhisen** [comment]
我来补充一下，基本情况是，刚打开文档时候是正常的，快速在一个多层文档及子目录切换后，浏览器会提示404 not found，类似：

Request URL: http://1.1.1.1:8088/docs/mindoc/13
Request Method: GET
Status Code: 404 Not Found

后台运行窗口显示类似如下信息：
2018/08/13 10:52:54.178 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0
2018/08/13 10:52:54.481 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0
2018/08/13 10:52:54.646 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0


只能重启应用后才能正常，快速点击后重新出现

**Comment by lifei6671** [comment]
@lizhisen @wakahuala 看看这些文档是不是没有设置唯一标识？目前发现一个BUG是没有设置唯一标识的文档在第二次访问的时候会报错。

**Comment by lizhisen** [comment]
唯一标识符的我查查。

另我发现，我conf中
#是否开启缓存，true 开启/false 不开启
cache=false

但是在runtime的log中有如下日志：

2018/08/13 10:16:11.065 [I] [asm_amd64.s:2361]  http server Running on http://:8088
2018/08/13 10:16:36.567 [I] [asm_amd64.s:2361]  http server Running on http://:8088
2018/08/13 10:17:13.844 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:17:26.050 [I] [BookResult.go:468]  文档转换完成：防火墙策略提取及测试程序 
2018/08/13 10:17:59.832 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:18:01.913 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:18:03.322 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:18:08.349 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:18:10.857 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:18:18.592 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:18:37.282 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:31:07.157 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:33:59.201 [E] [Blog.go:284]  获取文章列表时出错 -> <nil> 
2018/08/13 10:35:18.499 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:35:30.749 [I] [BookResult.go:468]  文档转换完成：网管平台辅助提醒工具 
2018/08/13 10:36:07.565 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:36:27.512 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:36:28.631 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:02.341 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:05.066 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:19.795 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:20.912 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:31.072 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:34.784 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:36.153 [E] [BookResult.go:229]  将导出任务加入任务队列失败 ->  指定的键已存在 
2018/08/13 10:37:46.179 [I] [BookResult.go:468]  文档转换完成：网络智能E管家项目文档 
2018/08/13 10:40:01.501 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:04.123 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:08.985 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:13.930 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:14.847 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:16.188 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:16.898 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:17.556 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:18.293 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:18.790 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:19.192 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:19.964 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:23.702 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0 
2018/08/13 10:40:24.195 [I] [DocumentModel.go:185]  从缓存中获取文档信息成功 0

**Comment by lizhisen** [comment]
您好，唯一表示的设置在哪？我在项目的设置中找了半天没找到。

**Comment by lifei6671** [comment]
@lizhisen 编辑文档时右键编辑。

**Comment by lizhisen** [comment]
您好，在配置unique id后问题解决。之前的现象是，没有配置id（非必须项），在应用启动时可以使用的，进行项目章节切换后文章找不到，这个原因未知，还得麻烦您排查了。

**Comment by lifei6671** [comment]
新版本已修复这个问题。
