### ISSUE TITLE
无法保存复制粘贴的内容

### ISSUE THREAD

**Issue by aveyuan** [lifei6671/mindoc#320]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

v0.12
2. 你当前使用的是什么操作系统?

win7
3. 你是如何操作的？
1.在填充文档内容的时候我选择复制其他地方的内容粘贴到文本中
2.我发现保存按钮居然是灰色的，没有检测到文本框的内容已经被通过复制粘贴的方式填充
3.我选择发布，然后打开文件看为空白，看来是真的没有保存。
4.如果我在文本框敲一个空格保存按钮就检测到了可以保存，且发布能看到

4. 你期望得到什么结果?
修复

5. 当前遇到的是什么结果?
无法保存复制粘贴的内容

**Comment by lifei6671** [comment]
浏览器问题。粘贴到文本框中的文本无法触发编辑器的change事件。

**Comment by aveyuan** [comment]
OK，谢谢
