### ISSUE TITLE
图片全部都为默认封面了

### ISSUE THREAD

**Issue by aveyuan** [lifei6671/mindoc#321]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.12

2. 你当前使用的是什么操作系统?
win7

3. 你是如何操作的？

在 #316 的Issues中解决了连续添加封面图片不会刷新的前情况。虽然现在添加项目的时候虽然正常，但是点击保存之后封面全是默认封面了。我看了后台也没有上传封面。
4. 你期望得到什么结果?
修复

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
我测试是正常的。
你看看是不是配置有问题或者是浏览器有缓存？

**Comment by aveyuan** [comment]
换了一个浏览器正常了，应该是缓存。
