### ISSUE TITLE
更新V12版本之前的项目加载失败？

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#322]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
V12

2. 你当前使用的是什么操作系统?
Windows64

3. 你是如何操作的？

![image](https://user-images.githubusercontent.com/28562551/43691733-37e973e4-9953-11e8-86b0-284f26d2200a.png)

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
你去演示站上看看有没有这个问题。
