### ISSUE TITLE
docker镜像无法使用mysql数据库

### ISSUE THREAD

**Issue by maoxuner** [lifei6671/mindoc#323]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
主分支docker构建版本，commit [b50d39f690ea9074c4ce5928f687d2348ac9e854](https://github.com/lifei6671/mindoc/tree/b50d39f690ea9074c4ce5928f687d2348ac9e854)

2. 你当前使用的是什么操作系统?
debian7.2

3. 你是如何操作的？
docker build + docker-compose的方式

4. 你期望得到什么结果?
使用mysql数据库连接

5. 当前遇到的是什么结果?
无论如何都是使用sqlite本地数据库

---

出现bug的原因是，3天前修改的`start.sh`文件中，删除了mysql adapter相关的环境变量代码。而现有的逻辑是，不管有没有adapter相关的环境变量，都将 `app.conf`中的adapter替换成`sqlite3`

`start.sh`第8-9行，不论有没有设置相关环境变量，最终都会使用sqlite3
```
if [ ! -f "/mindoc/conf/app.conf" ] ; then
    cp /mindoc/conf/app.conf.example /mindoc/conf/app.conf
	sed -i "s#^db_adapter=.*#db_adapter=sqlite3#g" conf/app.conf
	sed -i "s#^db_database.*#db_database=./database/mindoc.db#g" conf/app.conf
fi
```

修复该bug时不能单纯删除这两行代码，要加入一定的判断逻辑，或者修改`conf/app.conf.example`内的相关逻辑、配置顺序

另外，mindoc文档中关于环境变量的使用也要更新

**Comment by lifei6671** [comment]
请使用releases中的发布版。
master仓库中不是发布版本。
