### ISSUE TITLE
web页面里附件管理or标签管理打开报错

### ISSUE THREAD

**Issue by liziker** [lifei6671/mindoc#325]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.12

2. 你当前使用的是什么操作系统?
ubuntu14， nginx/1.4.6， mysql-5.5.49

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
管理后台-附件管理or标签管理打开失败，报错找不到文件
`HTTP 50001 ： <QuerySeter> no row found` 
`HTTP 500 ： 服务器异常`

**Comment by lifei6671** [comment]
先添加一个标签就可以了。下个版本修复这个问题。
