### ISSUE TITLE
HTTP 500 ： 导出失败，请查看系统日志

### ISSUE THREAD

**Issue by DonalLiu** [lifei6671/mindoc#326]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.12

2. 你当前使用的是什么操作系统?
centos6.9 

3. 你是如何操作的？
点击文档导出，随便选中任何格式都是这个错误

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
请查看日志。
