### ISSUE TITLE
ldap 账号登录失败

### ISSUE THREAD

**Issue by kaishidongle90** [lifei6671/mindoc#328]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

daocloud.io/lifei6671/docker-mindoc:develop-b732cbb2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？

web页面登录
4. 你期望得到什么结果?
使用ldap账号登录

5. 当前遇到的是什么结果?
2018/08/15 08:51:11.515 [I] [AccountController.go:65]  转入LDAP登陆
2018/08/15 08:51:11.524 [E] [asm_amd64.s:573]  用户登录 => 第一次LDAP绑定失败

**Comment by lifei6671** [comment]
我对LDAP不熟，这块是网友提供的代码。

**Comment by kaishidongle90** [comment]
嗯 好的
