### ISSUE TITLE
评论功能

### ISSUE THREAD

**Issue by ljt000046** [lifei6671/mindoc#329]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
V12

2. 你当前使用的是什么操作系统?
Linux centos

3. 你是如何操作的？
新建项目,没有开发评论的功能

4. 你期望得到什么结果?

可以使用评论功能
5. 当前遇到的是什么结果?
没有看到评论功能

**Comment by lifei6671** [comment]
没有评论功能
