### ISSUE TITLE
HTML编辑器项目无法识别HTML语法

### ISSUE THREAD

**Issue by Nidhoggur1993** [lifei6671/mindoc#330]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64_v0.12

2. 你当前使用的是什么操作系统?
CentOS release 6.5 (Final)

3. 你是如何操作的？
1）项目设置为HTML编辑器
![image](https://user-images.githubusercontent.com/12947582/44389951-c7a83a80-a55e-11e8-9174-aa00d991d6d1.png)
2）进入该项目的任意页面使用HTML语言进行编辑
![image](https://user-images.githubusercontent.com/12947582/44390350-aac03700-a55f-11e8-9492-9704987726b9.png)
3）保存并发布
4）返回阅读界面

4. 你期望得到什么结果?
正常的HTML格式应该展示的内容，比如这样
![image](https://user-images.githubusercontent.com/12947582/44390078-0807b880-a55f-11e8-86ef-729273e12537.png)

5. 当前遇到的是什么结果?
![image](https://user-images.githubusercontent.com/12947582/44390115-1fdf3c80-a55f-11e8-9844-61c7b318e348.png)

**Comment by lifei6671** [comment]
HTML编辑器是富文本编辑器，不支持直接输入HTML标签。

**Comment by Nidhoggur1993** [comment]
> HTML编辑器是富文本编辑器，不支持直接输入HTML标签。

是否能够增加这一功能？HTML表格比Markdown原生的功能更丰富
0.60版本的mindoc是支持这种写法的

**Comment by lifei6671** [comment]
@Nidhoggur1993 HTML编辑器不再提供新功能。你可以将表格代码直接嵌入到markdown编辑器中。
