### ISSUE TITLE
修改的内容没有更新

### ISSUE THREAD

**Issue by shenlanchenwei** [lifei6671/mindoc#332]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
  godoc_amd64 最新版本

2. 你当前使用的是什么操作系统?
 windows

3. 你是如何操作的？
1.对随便一个已经建好的文章进行编辑,**完成后点保存,再点发布**
2.前台点击这个文章发现还是原来的老内容,然后点下刷新就马上变成新的内容,然后其他页面跳转过来又是老内容,老是要点刷新才能看到新内容 

ps:我用的Chrome浏览器,发现url地址变了,但是没有请求任何服务器

4. 你期望得到什么结果?

 希望文章显示我修改后的内容

5. 当前遇到的是什么结果?

显示的是老的内容,需要点刷新后才能正常显示,线上的演示系统同样存在这个问题

**Comment by lifei6671** [comment]
为了加快也没响应速度，使用了缓存。你可以清空缓存再打开。

**Comment by shenlanchenwei** [comment]
能改哪行代码关掉缓存吗?本人不太熟悉Go语言,谢谢
