### ISSUE TITLE
项目编辑无法查阅现有项目资料。

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#333]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
V13.3
2. 你当前使用的是什么操作系统?

windows

3. 你是如何操作的？
以前项目需要修改，编辑进去什么都没，
没编辑状态
![image](https://user-images.githubusercontent.com/28562551/44699702-076ba680-aab8-11e8-9145-34ee5f2ed453.png)
编辑状态
![image](https://user-images.githubusercontent.com/28562551/44699725-25390b80-aab8-11e8-8f57-c1edc3f834fc.png)

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

编辑没问题

**Comment by lifei6671** [comment]
演示站上没有重现。
清空浏览器缓存试试。

**Comment by gdlaoqiang** [comment]
没效果，依然是这样

**Comment by lifei6671** [comment]
没重现你的问题。
