### ISSUE TITLE
如图，有的项目有下载选项，有的没呢？

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#334]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？
![image](https://user-images.githubusercontent.com/28562551/44765429-3b61cd00-ab87-11e8-9207-e1049edb6bd7.png)
![image](https://user-images.githubusercontent.com/28562551/44765439-44eb3500-ab87-11e8-9d2d-57a30a99a983.png)

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
请在项目设置中开启。
