### ISSUE TITLE
增强markdown功能

### ISSUE THREAD

**Issue by Robynkhan** [lifei6671/mindoc#335]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
godoc_linux_amd64 version

2. 你当前使用的是什么操作系统?
centos 7 64bit

3. 你是如何操作的？
- xxx
	- xxx
		| 1 | 1 |
		|--|--|
		| 1 | 1 |
	- ccc
	- dddd

4. 你期望得到什么结果?
参考网站：https://hackmd-ce.herokuapp.com/
![image](https://user-images.githubusercontent.com/35448191/44943177-9a784980-adf4-11e8-82f5-f77c9dae77a0.png)

5. 当前遇到的是什么结果?
![image](https://user-images.githubusercontent.com/35448191/44943179-a9f79280-adf4-11e8-8803-aca939e98d3e.png)

**Comment by lifei6671** [comment]
不太明白你具体想要什么效果？

**Comment by ugrg** [comment]
我猜他的问题是，表格没有被正确解析。
