### ISSUE TITLE
内容修改后的不能正常更新到页面

### ISSUE THREAD

**Issue by ugrg** [lifei6671/mindoc#336]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
    mindoc_windows_amd64.7z
    0.13.4

2. 你当前使用的是什么操作系统?
   windows

3. 你是如何操作的？
　在项目中，  新建一篇内容，更新好文本后，查看一次。再编辑一次，再来查看一下。
　打开的时候，内容是新的，但我再次在目录中点击这篇内容时，内容会还原为上次的内容。

4. 你期望得到什么结果?
　显示最新的内容

5. 当前遇到的是什么结果?
-----
好吧，你的格式有点累。
我追踪了一下你们的代码，你们在前端有一个events全局对象，是在loadDocument方法中使用的，这个对象中的data方法，会根据浏览器是否有sessionStorage来决定是使用浏览器的sessionStorage来缓存数据。这里我之前查看过一次，则会在这里新建出缓存，当我编辑完后，再来点击这个内容时，则会出现读取的是旧内容。

给你们的更新建议是，在目录上，增加一个属性，标记出这篇内容的版本号，然后在sessionStorage缓存内容时，也标记上一个版本号。在loadDocument时，如果这两个版本号不一至，则选择清除sessionStorage，再去服务器提取最新内容，重新构建缓存，并展示内容。

**Comment by lifei6671** [comment]
v1.0版本已修复
