### ISSUE TITLE
blog页面的js问题

### ISSUE THREAD

**Issue by ugrg** [lifei6671/mindoc#337]
我在打开blog页面时，总是能看到一些js错误。从功能上来分析，这个页面引用的`kancloud.js`貌似一点用都没有，建议在下个版本中把他删了吧。

views/blog/index.tpl
中的
<script src="{{cdnjs "/static/js/kancloud.js"}}" type="text/javascript"></script>

**Comment by lifei6671** [comment]
v1.0版本已增加
