### ISSUE TITLE
搜索功能无法索引到blog的内容

### ISSUE THREAD

**Issue by ugrg** [lifei6671/mindoc#338]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
mindoc_windows_amd64.7z
0.13.4

2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？
添加一篇“我的文章”，搜索blog中的内容。

4. 你期望得到什么结果?
像项目文档一样，被搜索收录。

5. 当前遇到的是什么结果?
没有被收录。

**Comment by lifei6671** [comment]
搜索用的是sql的like语法，暂时不支持博文的搜索。
