### ISSUE TITLE
多文件上传BUG

### ISSUE THREAD

**Issue by microlazy** [lifei6671/mindoc#341]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64 v0.13.4

2. 你当前使用的是什么操作系统?
windows10 版本 1607 OS内部版本 14393.2248
Google Chrome 68.0.3440.106（正式版本） （64 位）

3. 你是如何操作的？
点击附件按钮，同时选中两个上传文件，会出现第一个文件上传，第二个文件不上传的问题
![image](https://user-images.githubusercontent.com/11712986/45342517-ce135a80-b5d0-11e8-8aa0-51cdfc28cb66.png)

4. 你期望得到什么结果?
能同时完成多个文件上传或者只允许选一个吧

5. 当前遇到的是什么结果?
当前同时选中两个文件只能上传一个文件，另一外文件不会执行上传，也不会从队列移除。需要刷新页面才会消失

**Comment by lifei6671** [comment]
v1.0版本已修复
