### ISSUE TITLE
windows下部署完成报错

### ISSUE THREAD

**Issue by yangql1980** [lifei6671/mindoc#343]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.13.4 

2. 你当前使用的是什么操作系统?
windows 10

3. 你是如何操作的？
按照您提供的部署说明

4. 你期望得到什么结果?
正常访问

5. 当前遇到的是什么结果?
PS D:\Mindoc\mindoc_windows_amd64> .\mindoc_windows_amd64.exe
2018/09/11 19:20:05.236 [I] [command.go:32]  正在初始化数据库配置.
2018/09/11 19:20:05.258 [I] [command.go:83]  数据库初始化完成.
MinDoc version =>
build time =>
start directory => D:\Mindoc\mindoc_windows_amd64\mindoc_windows_amd64.exe

2018/09/11 19:20:05.345 [I] [asm_amd64.s:2361]  http server Running on http://:8181
[beego] 2018/09/11 - 19:20:27 |      127.0.0.1|2018/09/11 19:20:27.600 [D] [controller.go:264]  template Execute err: template: widgets/footer.tpl:12:13: executing "widgets/footer.tpl" at <ne .site_beian "">: error calling ne: invalid type for comparison
2018/09/11 19:20:27.600 [E] [server.go:2694]  template: widgets/footer.tpl:12:13: executing "widgets/footer.tpl" at <ne .site_beian "">: error calling ne: invalid type for comparison
 200 |     8.6843ms|   match| GET      /login   r:/login

**Comment by BiggerChina** [comment]
在目录中 搜索 footer.tpl;使用文本编辑器 打开它,
删除掉以下部分就好:
`       {{if ne .site_beian ""}}
        <div class="row text-center">
            <a href="http://www.miitbeian.gov.cn" target="_blank">{{.site_beian}}</a>
        </div>
        {{end}}`

也就是 第10行至第14行的代码,

重新运行或者重启服务.

@yangql1980

**Comment by qwishes** [comment]
刚想提交这个问题，没想到有人提交了。这个问题太坑爹了，第一次用golang的项目，弄了3天，我还以为是服务器配置的问题，最后找到是这个footer.tpl的问题，删除这段搞备案的代码就好了，这时间浪费的太可惜了，建议直接作者把这个去了，免得小白用户遇到强烈的挫折感，期间我想自己用C#写一个的心都有了，哈哈
