### ISSUE TITLE
我想确定下当前已安装的版本号，请问如何查看。

### ISSUE THREAD

**Issue by asing** [lifei6671/mindoc#345]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

 mindoc_linux_amd64
2. 你当前使用的是什么操作系统?
Centos

3. 你是如何操作的？
无

4. 你期望得到什么结果?
我想确定下当前已安装的版本号，请问如何查看。

5. 当前遇到的是什么结果?
无法确定当前版本号

**Comment by lifei6671** [comment]
https://www.iminho.me/wiki/docs/mindoc/mindoc-command.md

**Comment by qrqhuang** [comment]
@lifei6671 命令报错
```
[root@CNSH042923 mindoc]# ./mindoc_linux_amd64 version
2018/11/02 11:37:53.390 [E] [update.go:20]  CheckUpdate =>  Get https://api.github.com/repos/lifei6671/mindoc/tags: dial tcp: lookup api.github.com on 10.11.86.15:53: server misbehaving 
```
另外希望在网页上直接可以查看当前版本，比如加到页脚
