### ISSUE TITLE
是否可以在树莓派3上部署

### ISSUE THREAD

**Issue by dxl3811051** [lifei6671/mindoc#346]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最后更新的那个版本

2. 你当前使用的是什么操作系统?
安装了64位linux系统

3. 你是如何操作的？
直接从源码下载 部署

4. 你期望得到什么结果?
希望可以部署成功

5. 当前遇到的是什么结果?
当前是不能部署成功，./mindoc_linux_amd64: cannot execute binary file: Exec format error，希望可以得到您的指点

**Comment by lifei6671** [comment]
目前发布的二进制文件只支持linux 64，window x32， windows x64，其他版本请自行编译。golang本身支持树莓派，但是需要自行编译。
