### ISSUE TITLE
项目文件修改并发布后，阅读时还是显示原来没修改前的样子

### ISSUE THREAD

**Issue by boy002** [lifei6671/mindoc#347]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

       registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc   v0.13.4

2. 你当前使用的是什么操作系统?

     Linux localhost.localdomain 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

3. 你是如何操作的？

     1. 先建立项目，后编辑文章保存并文章发布，项目发布。（文章内写文字和图片）
     2. 阅览项目看到建立的文件内容“AAA”
     3. 修改项目中的文章内容为“BBB”
     4. 阅读项目时点击左边的菜单右边页面显示还是“AAA”
     5. 刷新浏览器(F5),显示内容“BBB”
     6. 再点左边菜单显示内容"AAA"

4. 你期望得到什么结果?

     文章发布后点击左边菜单右边应该显示已修改后的内容“BBB”

5. 当前遇到的是什么结果?

    刷新整个浏览器显示“BBB”，点击左边的导航右边显示“AAA”

**Comment by lifei6671** [comment]
#337

**Comment by lifei6671** [comment]
#336

**Comment by ugrg** [comment]
给你个临时修复的办法。
找到项目中/static/js/kanclound.js，把从第25行前后的一个`if(window.sessionStorage)`修改为`if(false)`,这样可以禁用掉本地缓存，我现在就是这么解决的，等作者更新了。
