### ISSUE TITLE
首页错别字修改

### ISSUE THREAD

**Issue by zhangyq1011** [lifei6671/mindoc#349]
安装与使用

如果你的服务器上没有安装golang程序请手动设置一个环境变量如下：键名为 ZONEINFO，值为MinDoc跟目录下的/lib/time/zoneinfo.zip 。

值为MinDoc跟目录下的/lib/time/zoneinfo.zip 。  应该为 根目录 。哈哈^_^

**Comment by lifei6671** [comment]
谢谢。
