### ISSUE TITLE
0.13.4版本，mermaid语法无效

### ISSUE THREAD

**Issue by max-gui** [lifei6671/mindoc#351]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.12到0.13.4

2. 你当前使用的是什么操作系统?
docker

3. 你是如何操作的？
未做特殊配置，直接启动的镜像

4. 你期望得到什么结果?
mermaid支持如何启用

5. 当前遇到的是什么结果?
``` mermaid
graph TB
    id1(圆角矩形)--普通线-->id2[矩形]
    subgraph 子图表
        id2==粗线==>id3{菱形}
        id3-.虚线.->id4>右向旗帜]
        id3--无箭头---id5((圆形))
    end
```

显示为
graph TB
    id1(圆角矩形)--普通线-->id2[矩形]
    subgraph 子图表
        id2==粗线==>id3{菱形}
        id3-.虚线.->id4>右向旗帜]
        id3--无箭头---id5((圆形))
    end

**Comment by lifei6671** [comment]
v0.13.4不支持该语法。

**Comment by max-gui** [comment]
煩請告知哪個版本支持，謝謝。
我希望使用和demo一樣的版本。
