### ISSUE TITLE
mindoc安装报错

### ISSUE THREAD

**Issue by fanjie1225** [lifei6671/mindoc#352]
1. 当前MiDoc版本V1.0
2. Os版本Centos7.5
3. 数据库mysql
4. 操作 
 ./mindoc_linux_amd64 install
2018/09/18 17:24:35.725 [I] [command.go:32]  正在初始化数据库配置. 
[ORM]2018/09/18 17:24:35 register db Ping `default`, invalid DSN: did you forget to escape a param value?
2018/09/18 17:24:35.725 [E] [command.go:55]  注册默认数据库失败-> register db Ping `default`, invalid DSN: did you forget to escape a param value?
请问知道原因么?

**Comment by lifei6671** [comment]
目测你的配置文件配置的有问题

**Comment by fanjie1225** [comment]
db_adapter=mysql
db_host=xx.xx.xx.xx
db_port=3306
db_database="${MINDOC_DB_DATABASE||./database/mindoc.db}"
db_username=root
db_password=xxx
只配了数据库这几条，数据库通过命令行可以访问的

**Comment by lifei6671** [comment]
db_database配置成MySQL的表名。

**Comment by fanjie1225** [comment]
太感谢了 ，果然是这个问题，下次瞧仔细了，
