### ISSUE TITLE
在线演示的导出功能报500错误。我用的是V1.0.1Linux版本，部署运行后文档的导出功能也是报500错误

### ISSUE THREAD

**Issue by mameng1992** [lifei6671/mindoc#354]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
请看官方手册，谢谢！
