### ISSUE TITLE
Calibre 导出 PDF 汉字模糊，不清晰

### ISSUE THREAD

**Issue by asing** [lifei6671/mindoc#356]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  v1.0.1
MinDoc last version =>  v1.0.1

2. 你当前使用的是什么操作系统?
Centos 7.2

3. 你是如何操作的？
安装教程安装Calibre，使用Mindoc可以正常导出，但是汉字不清晰

4. 你期望得到什么结果?
汉字清晰

5. 当前遇到的是什么结果?
汉字不清晰

**Comment by lifei6671** [comment]
测试发现是因为一个CSS样式导致的，你可以尝试在本地修改`static/css/export.css`来解决，加一行：

```
.markdown-body{
    -webkit-backface-visibility: inherit !important;
    backface-visibility: inherit !important;
}
```

**Comment by asing** [comment]
收到谢谢

下个版本会修复么？

**Comment by lifei6671** [comment]
<https://github.com/lifei6671/mindoc/releases/tag/v1.0.2>
