### ISSUE TITLE
Dockfile安装报错

### ISSUE THREAD

**Issue by boy002** [lifei6671/mindoc#357]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
    
   master源代码

2. 你当前使用的是什么操作系统?
  
   CentOS7

3. 你是如何操作的？

    docker build -t mindoc:1.01 .

报错：Sending build context to Docker daemon 141.1 MB
Step 1/32 : FROM golang:1.10.3-alpine3.7 AS build
Error parsing reference: "golang:1.10.3-alpine3.7 AS build" is not a valid repository/tag: invalid reference format

修改Dockerfile 为：1.10.4-alpine3.8 上述错误没有了，但又出现以下问题：

Step 10/32 : RUN go get -u github.com/golang/dep/cmd/dep && dep ensure  &&      CGO_ENABLE=1 go build -v -a -o mindoc_linux_amd64 -ldflags="-w -s -X main.VERSION=$TAG -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'" &&     rm -rf commands controllers models modules routers tasks vendor docs search data utils graphics .git Godeps uploads/* .gitignore .travis.yml Dockerfile gide.yaml LICENSE main.go README.md conf/enumerate.go conf/mail.go install.lock simsun.ttc
 ---> Running in cbeaf6705e18

Solving failure: No versions of github.com/kardianos/service met constraints:
        master: unable to deduce repository and source type for "golang.org/x/sys/windows/registry": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sys/windows/registry?go-get=1": Get http://golang.org/x/sys/windows/registry?go-get=1: dial tcp 216.239.37.1:80: i/o timeout
The command '/bin/sh -c go get -u github.com/golang/dep/cmd/dep && dep ensure  &&       CGO_ENABLE=1 go build -v -a -o mindoc_linux_amd64 -ldflags="-w -s -X main.VERSION=$TAG -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'" &&     rm -rf commands controllers models modules routers tasks vendor docs search data utils graphics .git Godeps uploads/* .gitignore .travis.yml Dockerfile gide.yaml LICENSE main.go README.md conf/enumerate.go conf/mail.go install.lock simsun.ttc' returned a non-zero code: 1
请帮忙看一下如何解决，谢谢。

**Comment by lifei6671** [comment]
如果是在本地编译镜像，请自行搬梯子。
