### ISSUE TITLE
反馈个多人编辑时的bug

### ISSUE THREAD

**Issue by tiny99** [lifei6671/mindoc#360]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc  v1.0

2. 你当前使用的是什么操作系统?
windows 10

3. 你是如何操作的？
两个用户同时编辑同一篇文章的时候容易出现覆盖的情况：
a. 两个人同时打开一篇文档并进行编辑
b. 用户A完成编辑并完成发布，此时用户B尚未完成编辑
c. 用户B完成编辑时点保存，会提示“文档被其他人修改是否要覆盖当前文档”
d. 此时，用户B不管是点直接覆盖，还是用修改历史里面的“合并”功能，都无法将自己当前编辑但未保存的文档与用户A保存的最新文档进行合并

4. 你期望得到什么结果?
用户B编辑完但未保存的文档，可以与用户A进行合并，而不是直接覆盖用户A的劳动成果

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
目前不支持合并操作。仅支持覆盖。
