### ISSUE TITLE
附件上传的 PDF 不能直接浏览器打开吗？

### ISSUE THREAD

**Issue by asing** [lifei6671/mindoc#362]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version => v1.0.1
MinDoc last version => v1.0.1

2. 你当前使用的是什么操作系统?
Centos 7.2

3. 你是如何操作的？
编辑文章，附件上传

4. 你期望得到什么结果?
PDF 附件通过浏览器在线预览，无需下载

5. 当前遇到的是什么结果?
PDF 附件会进行下载动作

**Comment by lifei6671** [comment]
MinDoc 不支持在线预览任何上传的附件。
