### ISSUE TITLE
增加创建表格功能

### ISSUE THREAD

**Issue by Yashonlin** [lifei6671/mindoc#364]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc-1.0.1

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
插入表格

4. 你期望得到什么结果?
创建文章增加创建表格功能

5. 当前遇到的是什么结果?
只能在markdown中编辑表格，行政人员等无法友好使用

**Comment by lifei6671** [comment]
不清楚你具体要什么功能。目前文章只支持 Markdown 编辑器。
项目也会逐渐不在维护 富文本编辑器 。
