### ISSUE TITLE
导出失败提示exit status 2

### ISSUE THREAD

**Issue by liminghui2011** [lifei6671/mindoc#365]
请按照一下格式提交issue，谢谢！

你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
github 上的最新版 mindoc_linux_amd64.zip

你当前使用的是什么操作系统?
centos6.9

你是如何操作的？
正常下载项目并部署启动，已正常安装wkhtmltox、calibre

你期望得到什么结果?
希望能正常导出文档文件

当前遇到的是什么结果?
convert to epub
convert to mobi
convert to pdf
convert to docx
[ebook-convert /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/content.epub /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/output/book.mobi]
正在转换 MOBI 文件 /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/content.epub
2018/10/10 18:37:41.461 [D] [server.go:2694]  |202.104.136.205| 200 |    279.408µs|   match| GET      /static/fonts/lato-100.css
2018/10/10 18:37:41.478 [D] [server.go:2694]  |202.104.136.205| 200 |    386.901µs|   match| GET      /static/fonts/lato/v11/GtRkRNTnri0g82CjKnEB0Q.woff2
[ebook-convert /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/content.epub /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/output/book.pdf --paper-size a4 --pdf-default-font-size 14 --pdf-header-template <p style='color:#8E8E8E;font-size:12px;'>_SECTION_</p> --pdf-footer-template <p style='color:#8E8E8E;font-size:12px;'>本文档使用 <a href='https://www.iminho.me' style='text-decoration:none;color:#1abc9c;font-weight:bold;'>MinDoc</a> 构建 <span style='float:right'>- _PAGENUM_ -</span></p> --pdf-page-margin-left 72 --pdf-page-margin-top 72 --pdf-page-margin-right 72 --pdf-page-margin-bottom 72]
正在转换 PDF 文件 /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/content.epub
转换PDF文档失败：exit status 2
[ebook-convert /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/content.epub /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/output/book.docx --docx-no-toc --docx-page-size a4 --docx-page-margin-left 72 --docx-page-margin-top 72 --docx-page-margin-right 72 --docx-page-margin-bottom 72]
正在转换 DOCX 文件 /tmp/ee50f9b45d3983ef8a0e57e1cbed9013/mindoc/output/content.epub
转换WORD文档失败：exit status 2
2018/10/10 18:37:53.480 [E] [BookResult.go:475]  转换文件错误：MinDoc演示项目 -> exit status 2
exit status 2

**Comment by lifei6671** [comment]
请手动执行转换命令看看是否成功。

**Comment by liminghui2011** [comment]
手动执行转换是可以成功的，这个确认过了

**Comment by lifei6671** [comment]
看看是不是权限问题。你的MinDoc是以什么权限运行的？

**Comment by lifei6671** [comment]
先尝试以root用户运行，定位是不是权限问题。

**Comment by liminghui2011** [comment]
用root用户启动运行，导出还是提示[BookResult.go:475] 转换文件错误：MinDoc演示项目 -> exit status 2

**Comment by liminghui2011** [comment]
这个exit status 2状态的错误有具体原因描述嘛，试了好久还是没办法导出

**Comment by lifei6671** [comment]
这个错误不是MinDoc的，是calibre异常退出了。目测是你安装的这个组件有问题。

**Comment by jmccy** [comment]
convert to pdf
centos7.2
MinDoc current version =>  v1.0.1
[E] [BookResult.go:232]  检查转换程序失败 ->  exec: "ebook-convert": executable file not found i
n $PATH
