### ISSUE TITLE
希望添加附件支持.mp3等音频格式

### ISSUE THREAD

**Issue by yunchaolu** [lifei6671/mindoc#367]
1. 你当前使用的是什么操作系统?
  Windows10

2. 你是如何操作的？
  添加附件

3. 你期望得到什么结果?
   可以添加.mp3等音频文件

4. 当前遇到的是什么结果?
   添加附件不支持.mp3格式文件

**Comment by lifei6671** [comment]
请自行在配置文件中添加需要的附件后缀。
