### ISSUE TITLE
快速创建表格

### ISSUE THREAD

**Issue by Yashonlin** [lifei6671/mindoc#368]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc-1.0.1

2. 你当前使用的是什么操作系统?
Centos7

3. 你是如何操作的？
建表格

4. 你期望得到什么结果?
与"添加文章"功能并列可选择创建表格

5. 当前遇到的是什么结果?
只能markdown语法编辑表格，无法快速从office复制表格到mindoc

**Comment by lifei6671** [comment]
Markdown语法本身就和office无法兼容。
