### ISSUE TITLE
希望能够在复制word时复制图片

### ISSUE THREAD

**Issue by lxflxf56** [lifei6671/mindoc#370]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
在word复制，在页面粘贴

4. 你期望得到什么结果?
能够把图片也给复制粘贴进去，或者有office导入功能

5. 当前遇到的是什么结果?
仅有文字进去了

**Comment by lifei6671** [comment]
Markdown无法兼容office格式。

**Comment by lxflxf56** [comment]
不需要兼容格式，现在是单张单张图片复制能够粘贴进去，希望能够文字与图片一起复制时，图片也能粘贴进去

**Comment by lifei6671** [comment]
如果您能提供这样的代码的话，我可以加入，我没找到支持图片文粘贴的接口。
