### ISSUE TITLE
导出PDF 或world时非常慢，只有我这样吗？还大家都挺慢啊！

### ISSUE THREAD

**Issue by 18393419461** [lifei6671/mindoc#375]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.12

2. 你当前使用的是什么操作系统?
centos7.3

3. 你是如何操作的？
docker

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
导出的快慢取决于你的项目大小和服务器性能。
