### ISSUE TITLE
baseurl能配置多个地址吗

### ISSUE THREAD

**Issue by jcjview** [lifei6671/mindoc#376]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v1.0.2 
https://github.com/lifei6671/mindoc/releases/download/v1.0.2/mindoc_linux_amd64.zip

2. 你当前使用的是什么操作系统?
Ubuntu 14.04

3. 你是如何操作的？
服务在8181端口，baseurl 配置为http://test.testweb.com:9000/wiki nginx做相应配置 可以访问
但内网192.168.33.155:9000/wiki或者192.168.33.155:8181无法访问

baseurl改成http://test.testweb.com:9000/wiki||http://192.168.33.155:9000/wiki也不行
http://test.testweb.com:9000/wiki||http://192.168.33.155:8181也不行
4. 你期望得到什么结果?
希望配置的外网和内网可以同时访问

5. 当前遇到的是什么结果?
baseurl改成http://test.testweb.com:9000/wiki||http://192.168.33.155:9000/wiki

http://test.testweb.com:9000/wiki||http://192.168.33.155:8181也

内网访问报nomatch或404

谢谢

**Comment by lifei6671** [comment]
和baseurl配置无关，是你内网网络问题。
这个配置只是为了生成链接，图片等资源的完整路径。

**Comment by jcjview** [comment]
就我部署的结果看，如果baseurl和网页输入地址不一致（比如baseurl配置的是网址网页通过ip访问），则报nomatch错误，通过Nginx转发都不行，我是http非https连接。
