### ISSUE TITLE
添加到文章内的图片不能设置大小

### ISSUE THREAD

**Issue by zsinba** [lifei6671/mindoc#378]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
Linux版本最新2018-11-06更新

2. 你当前使用的是什么操作系统?
Ubuntu 18.04

3. 你是如何操作的？
发布新的文章

4. 你期望得到什么结果?
可以设置图片的大小、位置、显示比例
类似网易邮件添加图片时的快捷操作
![image](https://user-images.githubusercontent.com/890157/48056594-1031d480-e1ed-11e8-8a73-8672bebab978.png)

5. 当前遇到的是什么结果?
当添加一个比较大的图片时，现在就显示一个大图，不能缩放，也不能修改

**Comment by lifei6671** [comment]
Markdown编辑器已经支持调整图片大小了，请自行阅读手册。
HTML编辑器不再添加新功能。

<https://www.iminho.me/wiki/docs/mindoc/markdown-basic.md>
