### ISSUE TITLE
标签统计数量不自动刷新

### ISSUE THREAD

**Issue by wakahuala** [lifei6671/mindoc#379]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？
标签页面中，每个标签的项目数量统计，当删除或新增一个项目，数量不变，只有选择该标签中某一个项目进行设置并保存后，数量才会刷新

4. 你期望得到什么结果?
对项目进行增删操作时，标签数量统计自动刷新

5. 当前遇到的是什么结果?
需要进行项目设置保存，才能触发数量刷新

**Comment by lifei6671** [comment]
标签是跟项目关联的。不清楚你具体是什么问题？

**Comment by lifei6671** [comment]
标签跟项目时弱关联的，删除项目无法刷新标签数量。这块将来会重新。
