### ISSUE TITLE
请教一下如何配置局域网和外网都可访问

### ISSUE THREAD

**Issue by wakahuala** [lifei6671/mindoc#380]
如题，

一、希望达到的效果是：
外网访问时用域名访问（绕公网），服务器本地局域网访问时用 ip 访问（不绕公网），该如何配置 ？

二、测试了一下，当前结果是：
1、app.conf 文件的 baseurl 如果配置为域名，则只能域名访问，局域网用 ip 访问时，会被自动强制转化跳转成域名访问

2、app.conf 文件的 baseurl 注释掉不配置，则只能局域网 ip 访问，用域名访问就会显示不正常

**Comment by lifei6671** [comment]
不支持你说的这种访问方式。
