### ISSUE TITLE
点击Markdown编辑器使用 [TOC] 生成的导航链接，刷新页面后状态丢失

### ISSUE THREAD

**Issue by devin87** [lifei6671/mindoc#381]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
官网演示版本

2. 你当前使用的是什么操作系统?
官网演示服务器

3. 你是如何操作的？
Markdown编辑器使用 [TOC] 生成的导航链接，点击后刷新页面。
https://doc.iminho.me/docs/simon/simon-1ap8gmamcdg20#924lmc

4. 你期望得到什么结果?
能定位到对应内容，链接不变，右边状态能正常显示。

5. 当前遇到的是什么结果?
无法定位到对应内容，链接中锚点部分丢失了，右边高亮变成了第1项。

**Comment by lifei6671** [comment]
不明白你说的点击刷新后消失时什么意思？

**Comment by devin87** [comment]
1. 链接中 `#di33zt` 刷新后没了
https://doc.iminho.me/docs/simon/simon-1ap8gmamcdg20#di33zt
https://doc.iminho.me/docs/simon/simon-1ap8gmamcdg20
2. 刷新后滚动条也没有滚动到 `#di33zt` 对应的内容区域
3. 刷新后右边的导航也没有选中默认的项，而始终选中的是第1项

**Comment by lifei6671** [comment]
滚动条需要达到可视区域的最上部才会选中下一个即将到达的标题位置。这个文章过短，所以无法跟随滚动条来选中。
滚动定位和浏览器分辨率有关，因为浏览器以及客户端的复杂性，不可能像你想象中的那么精确。
