### ISSUE TITLE
如何修改《HTTP 200 ： 文档正在后台转换，请稍后再下载》为英文？

### ISSUE THREAD

**Issue by Daidaiduo** [lifei6671/mindoc#382]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64.zip
v1.0.2

2. 你当前使用的是什么操作系统?
ubantu 16.04

3. 你是如何操作的？
..

4. 你期望得到什么结果?
修改提示文字为英文

5. 当前遇到的是什么结果?
不知道文档路径。

**Comment by lifei6671** [comment]
暂不提供二次开发的技术支持，谢谢.
