### ISSUE TITLE
脚本注入错误

### ISSUE THREAD

**Issue by fachilles** [lifei6671/mindoc#383]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
新建文档时，名称可以输入<script> 脚本，存入数据库中。新建完成后，页面是不显示标题的，且每次都会执行此脚本；

**Comment by jcjview** [comment]
xss

**Comment by lifei6671** [comment]
已修复
