### ISSUE TITLE
登录问题，一直提示账号或密码错误

### ISSUE THREAD

**Issue by qll3609120** [lifei6671/mindoc#386]
版本：v0.12

系统环境：liunx环境

运行环境：docker环境下运行mindoc，数据库为mysql，无法正常登陆，一直提示账户或者密码错误。数据库md_members,存储的password是经过加密后的数据，看了加密的源码，无法破解，按照官方文档给的是：默认登陆用户名和密码：admin/123456。

系统能够返回用户名或密码错误，说明系统能够正常运行，数据库正常，而且我在后台有看到数据库的数据：密码加密结果：
M9xcs7uFd4z0RfV1M8TpFBKBj_2Kh2eJmXBTX7haVVRGCYOZ7r-d0KUw5v6dNtHMAA2O$15$e0849dd7d3c029963bea260ed231c97b10cf01afa0558d346e68b0f6$6658f50e729692488e9d59a0425d1a11a7fa43319b2ddc6ca0cd90da5091d0f9
能否解密看下这个对应的明文是啥。

**Comment by wzkun** [comment]
@qll3609120 你的问题解决了吗？
