### ISSUE TITLE
修改一个 editormd 参数，除了修改 static 或 views 以外有没有更好的方法？

### ISSUE THREAD

**Issue by ztj1993** [lifei6671/mindoc#387]
我想配置一个 editormd 编辑器插件参数，我简单看了一下代码，可能要修改 static/js/markdown.js 文件，或者修改模板文件。

请问有没有其他的更好的方式，而不用修改 mindoc 文件，比如引入一个可以自定义的 js 脚本 (这样方便以后升级)

**Comment by lifei6671** [comment]
你可以去editor.md的官网看看，获取去他的github上看看。
