### ISSUE TITLE
pdf 导出文件过大

### ISSUE THREAD

**Issue by wakahuala** [lifei6671/mindoc#389]
测试了一下，一个项目仅有几个文字，导出 pdf 文件就有十几M大小。三四页的那种导出更是有几十M的大小

**Comment by lifei6671** [comment]
MinDoc 导出用的是Calibre，大小不是我可以控制的。

**Comment by wakahuala** [comment]
> MinDoc 导出用的是Calibre，大小不是我可以控制的。

去了 converter 模块作者的官网尝试导出下载 pdf ，是正常的几百 K 的大小。这里几个文字就十几 M 大小，有没有可能是哪里出现了问题。
