### ISSUE TITLE
修改文档时文档标题的修改功能比较隐藏，建议挪出来更直观一些

### ISSUE THREAD

**Issue by wangbaike** [lifei6671/mindoc#390]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
挪到哪去？

**Comment by wangbaike** [comment]
编辑状态下目前不是有个创建文档的+号图标吗，把另外两个“删除和编辑”图标跟这个放在一起，这样一目了然，我第一次找编辑标题的时候找了好久，无意间点了下右键才看到的！

**Comment by lifei6671** [comment]
放不了，一是空间有限，而是这个插件不支持复杂的设置。右键创建和修改功能我的文档上已经有维护了。

**Comment by wangbaike** [comment]
嗯，估计也有好多像我一样没仔细看文档的，文档标题加个title提示怎么样？

**Comment by lifei6671** [comment]
嗯，我在创建文档的页面加个小提示吧。

**Comment by wangbaike** [comment]
这样会不会破坏整个页面的简洁性啊？
1、加个title属性提示“右键点击可操作”；
2、双击可快捷修改；
3、加个小提示

你都试试看哪个效果好一些

**Comment by lifei6671** [comment]
加个提示吧，双击会和现有功能冲突。title不通浏览器显示效果不一致。

**Comment by wangbaike** [comment]
嗯嗯，可以哈~
