### ISSUE TITLE
导出 pdf 文件过大的问题

### ISSUE THREAD

**Issue by wakahuala** [lifei6671/mindoc#391]
一、看了一下 convert.go ，有一个 content.epub 文件，所有导出的其他格式的文件(pdf ,epub,mobi,word)，都是  calibre 基于这个 content.epub 进行转换的。目前 epub，mobi，word 三种格式导出文件大小正常，只有 pdf 导出即使没几个文字也要十几M大小。两三页文字的甚至都达到好几十M。

分析了一下原因，epub 本质上是一个 zip 包，可以先随便导出一个 epub 文件，然后将后缀 epub 改为 zip 并解包后有多个文件，其中包含了一个 style 文件夹，是最大的（里面有一些css文件和font字体），calibre 在转换 content.epub 成一个 pdf 文件时，content.epub 可能不是一个纯文本的文件，因而在转换时有可能是当成图片进行转换的，这些是在 calibre 作者论坛中了解到的可能的情况。

zip 解包之后尝试删除了 style 文件夹，再压缩成 zip，然后再后缀改为 epub，这时转换成 pdf 文件大小就相对正常了，没图片的就几百k，有图片的也不会特别大。但问题是剔除了样式，字体上就没那么美观了，不过格式不会错乱，看起来是正常的。

虽然在 convert.go 中 os.RemoveAll()  函数去掉 style 这个文件夹可能会改善这个问题，但是不知道有没有什么更好的不影响字体美观度的解决思路，如果这样转换出来的 pdf 文件动不动就几十上百M，且不是纯文本的话，这样的 pdf 意义不是很大，还不如以前的 wkhtmltopdf 转换来的实在一些。
<br>
二、 pdf ，epub，mobi，word，这四种格式的导出，实际上只有 epub 在展示上是比较原汁原味，没有太多格式错乱问题，其他的 pdf 就太大，mobi 和 word 是基于 epub 进行 calibre 转换的，都存在或多或少的格式错乱问题，要么字体太大左偏移右偏移，反正其他三种格式导出后二次修改的工作量挺大。

**Comment by lifei6671** [comment]
把你本地的版本缓存v1.0.2吧，1.0.1的CSS样式问题会导致生成的PDF大部分都变成了图片。

**Comment by wakahuala** [comment]
> 把你本地的版本缓存v1.0.2吧，1.0.1的CSS样式问题会导致生成的PDF大部分都变成了图片。

本地的版本缓存1.0.2指的是什么？现在测试的版本就是1.0.2的

**Comment by lifei6671** [comment]
styles中的文件是为了保证导出的文件跟实际浏览器看到的效果差别不大，你完全可以删了，但是转换后的会乱七八糟。
PDF本身就要比普通文本大，为什么因为大就没意义了？
然后你的意见呢？
