### ISSUE TITLE
zip 附件上传失败

### ISSUE THREAD

**Issue by asing** [lifei6671/mindoc#392]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  v1.0.2
MinDoc last version =>  v1.0.2

2. 你当前使用的是什么操作系统?
CentOS 7.2

3. 你是如何操作的？
修改app/conf配置，在前台上传zip文件
重启服务也不行
4. 你期望得到什么结果?
正常上传zip文件

5. 当前遇到的是什么结果?
{errcode: 6004, message: "不允许的文件类型"}

**Comment by lifei6671** [comment]
<https://www.iminho.me/wiki/docs/mindoc/mindoc-attach.md>

**Comment by asing** [comment]
明白的。。。看了。。。但是不行的。。能测试确认下么
