### ISSUE TITLE
【重要】希望可以多层目录结构，我们目前100多人的组织架构都放在一个界面比较混乱。

### ISSUE THREAD

**Issue by nightwind27** [lifei6671/mindoc#395]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
新版本

2. 你当前使用的是什么操作系统?
服务器LINUX  电脑 WINDOWS

3. 你是如何操作的？
**打开主界面展示几百个项目，十分混乱，眼花缭乱，十分不方便。**

4. 你期望得到什么结果?
**希望可以从用户体验上做一点小的改进，就能帮助WIKI系统更加实用。我理解作者的想法，文档就是目录。但是 以目前的展现形式，首页打开后，以看板形式展示的目录，应该是：例如 部门名称/产品线名称 等，这个层级。然后点进去，可以再是各种卡片，例如：产品需求，设计案例，运维部署，等等。
第三层，再点击去就是具体的文档编辑和查看界面了。
这样十分有必要。至少需要能够支持三级目录结构：部门 -- 产品/团队 -- 文档**

5. 当前遇到的是什么结果?

**Comment by nightwind27** [comment]
至少需要能够支持三级目录结构：部门 -- 产品/团队 -- 文档
否则 WIKI就只能在某一个团队层级内部使用，而无法统一部门的WIKI。
WIKI系统在我看来，应该是统一的知识库，整个技术部门应该是统一使用一套WIKI，而不应该是每个部门独立一套WIKI系统（这个行为的主要原因是 没有多级目录结构，导致多了以后十分混乱）

**Comment by nightwind27** [comment]
十分感谢作者做了这个好用的 系统，我希望可以稍作修改就能够把wiki应用范围扩展到 技术部门级别。

首页打开的卡片：对应一级目录  各个子部门（**相当于目前的卡片展示，可以支持2级即可**）
点进某一个部门：各个组/产品线
点击某一个组：是具体的内容 编辑文件/查看文件界面

**Comment by lifei6671** [comment]
不清楚你说的多及目录结构是什么意思？是指文档没有还是项目没有？

**Comment by nightwind27** [comment]
就是指 ：登陆后  首先看到的，卡片列表页面，这个目前只有一级。

希望：卡片列表页面点进去某个卡片，可以是另一个新的 卡片列表页面。

**Comment by nightwind27** [comment]
项目的  多级目录结构，和文档没有关系。

**Comment by nightwind27** [comment]
我们的问题是 公司有5个部门，每个部门下面有多个项目。 

目前的情况是5个部门的所有项目都混杂显示在卡片看板上，项目太多，混在一起十分混乱，看不到归属。

所以希望  项目可以有多级. 也就是目前登录进去看的的卡片界面，可以有2级。

**Comment by lifei6671** [comment]
能看到多少项目是根据你的权限来的，你不给被人分配权限，别人就看不到。

**Comment by nightwind27** [comment]
不是权限问题哦   目前主要的痛点就是  没有  **项目集管理**   的概念。
我是做项目管理的，同时也是敏捷教练。

**Comment by nightwind27** [comment]
目前所有的卡片都是一个 项目，项目多了就会很乱。看起来也不清晰，找起来也麻烦。

所以需要加上  项目集管理 的概念。所以需要项目维度有2层。

**Comment by nightwind27** [comment]
项目集管理
项目管理
具体卡片

**Comment by nightwind27** [comment]
目前只有 项目管理 -- 具体卡片。希望可以增加 项目集 的维度。就会清晰好用很多。

**Comment by lifei6671** [comment]
我明白的意思了，其实就是给项目加个分类对吧。

**Comment by nightwind27** [comment]
是的  项目集 的概念，引入了就可以让WIKI支持到大型企业。

**Comment by lifei6671** [comment]
嗯，之前有人提过这个问题，目前是用标签来识别的。只是不够强化，最新忙着开发团队功能，没来得及完善这块。

**Comment by nightwind27** [comment]
形式可以是  分类 或者 其他形式。这个没关系。只要能有 项目集的概念，简单清晰就好。

**Comment by nightwind27** [comment]
看到标签了。。。理解你的意思了。只是不够直观，很多人不理解标签的用途。

项目集 的概念，如果引入，可以在最顶部 有一层 项目集 标签。或者其他形式。
这个概念引入是很重要的，可以提升整个WIKI的产品理念和适用范围。

**Comment by nightwind27** [comment]
东西做的很好，我们会支持你的 赞！

**Comment by nightwind27** [comment]
这个问题在不改一下，就非常不利于这个项目的推广和使用。我们公司可能就会停止用此系统。
层级结构太不方便了。建议参考下conflunce的wiki。

**Comment by nightwind27** [comment]
你要考虑  项目集 管理的问题。而不是零散的单个项目管理和知识分享。东西一多了起来十分混乱。

**Comment by nightwind27** [comment]
我建议支持到3层目录结构，最里面才是目前的文档

**Comment by sotex** [comment]
> 
> 
> 不清楚你说的多及目录结构是什么意思？是指文档没有还是项目没有？

我希望项目里面的文档也可以分级，或者像folder一样可以使用颜色进行标记。我们一个项目涉及到的东西很多，没有分级只能使用文档标题进行区分。

**Comment by lifei6671** [comment]
@nightwind27 您可以根据贵司的实际需求来选择产品，而不是让别人的开源产品去适应贵司需求。
@sotex 不支持目录标识。目录就是文档，文档就是目录。
