### ISSUE TITLE
提个新需求(管理员可管理所有文章)

### ISSUE THREAD

**Issue by detoandy** [lifei6671/mindoc#397]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v1.0.2

2.场景及需求
目前准备在企业内部使用mindoc，用户接入LDAP。
目前超级管理员不能管理文章，若用户出现离职情况，则管理员不能通过界面去删除文章，可否在后台添加文章的管理功能？

**Comment by lifei6671** [comment]
文章的使用率比较低，你直接删除了用户，这个用户相关项目和文章都会转义到超级管理员身上。
