### ISSUE TITLE
docker中部署系统发送邮件出现异常：x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by detoandy** [lifei6671/mindoc#398]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
1.0.2

2. 你当前使用的是什么操作系统?
linux docker

3.场景
docker中部署系统发送邮件时出现异常 ：x509: certificate signed by unknown authority，，windows下正常

**Comment by lifei6671** [comment]
是你自己编译的镜像吗？
看错误是证书问题。

**Comment by lifei6671** [comment]
我是问你从哪pull下来的镜像！

**Comment by detoandy** [comment]
就文档里的这个registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc

**Comment by detoandy** [comment]
经验证，我用的公司邮箱账号才出现这个问题，163账户没有出现这种问题，您觉得可能是什么原因？

**Comment by detoandy** [comment]
经过我百度找到了个解决方案，http://blog.fatedier.com/2015/08/20/use-smtp-to-sendmail-in-go-and-some-problems-with-smtp/，说是重写下smtp的sendmail 方法即可。
因为我对GO语言不太熟，在mindoc里面是不是只需要改mail文件夹下的smtp.go文件即可。但是我改了发现没生效。

**Comment by detoandy** [comment]
已经解决了，我改用SSL认证就可以了

**Comment by detoandy** [comment]
发现个新的问题：通过找回密码链接设置完密码后跳到登录页面，但登录过后又跳到找回密码的链接了。该重定向应该到主页面。我用的版本是1.0.2，不知道现在修复没。

**Comment by lifei6671** [comment]
网上的这个解决方案不靠谱，企业很多是需要使用ssl加密邮件的，网上这个解决方案是全部明文，肯定不行的。
另外，mindoc 支持明文发送邮件，你尝试在配置文件中配置成明文呢？

**Comment by detoandy** [comment]
这个找回密码后的登录跳转，没有跳转到主页，不知这个问题可否修复下?
