### ISSUE TITLE
隔一段时间后再运行报错,错误读取文件字体时出错

### ISSUE THREAD

**Issue by xinli1234** [lifei6671/mindoc#399]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
我忘了是哪个版本的了，我记得是6月份从github上拉取的，dodoc_windows_amd64的

2. 你当前使用的是什么操作系统?
Windows

3. 你是如何操作的？
go run

4. 你期望得到什么结果?
正常运行

5. 当前遇到的是什么结果?
读取字体文件时出错 -> open C:\Users\admin\AppData\Local\Temp\go-build389345858\command-line-arguments\_obj\exe\static\fonts: The system cannot find the path specified.

**Comment by 3xxx** [comment]
这是什么原因，我今天也遇到了。golang v1.25版。之前还好好的。
