### ISSUE TITLE
2.01 升级后的功能使用

### ISSUE THREAD

**Issue by asing** [lifei6671/mindoc#400]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
![wx20181128-090221](https://user-images.githubusercontent.com/345259/49121685-5958de00-f2ec-11e8-8aef-a2a6e43bac99.png)
ge.png…]()

2. 你当前使用的是什么操作系统?
Centos 7

3. 你是如何操作的？
正常升级

4. 你期望得到什么结果?
项目空间管理
团队管理
两项新功能的使用
还需要做什么样的配置么？
5. 当前遇到的是什么结果?
空链接，点击后直接跳到首页

**Comment by asing** [comment]
个人项目的编辑功能也无法使用了，点击编辑后页面成空白的了。

**Comment by lifei6671** [comment]
使用问题请自行看手册。
