### ISSUE TITLE
升级新版本，空链接

### ISSUE THREAD

**Issue by asing** [lifei6671/mindoc#402]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  v2.0.1

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
![wx20181128-112801](https://user-images.githubusercontent.com/345259/49126989-b3fc3500-f300-11e8-9e71-766799162bed.png)

4. 你期望得到什么结果?

https://github.com/lifei6671/mindoc/issues/400
同一个问题，问题被关闭了
使用手册都看了，没有找到相应的说明
再来请教下。

5. 当前遇到的是什么结果?
功能健全。

**Comment by lifei6671** [comment]
请使用最新版。

**Comment by asing** [comment]
大哥，你为啥要 issue 关闭这边快？
我升级了。问题还存在。。

**Comment by lifei6671** [comment]
你们提的这些问题我自己会验证，如果没有重现就会关闭isuse。有问题先自己找找是不是配置或者自己使用的问题。
另外，isuse不是提使用相关问题的，是用来反馈BUG的。
