### ISSUE TITLE
复杂流程图（分支较多、总宽度较宽）不能完整展示

### ISSUE THREAD

**Issue by hollydragon** [lifei6671/mindoc#403]
![_mark](https://user-images.githubusercontent.com/12869713/49140656-cb064b80-f32f-11e8-8657-d0f8d2650a42.png)

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0-beta.1

2. 你当前使用的是什么操作系统?
CentOS 7.0 Linux

3. 你是如何操作的？
在Markdown编辑器中绘制流程图

4. 你期望得到什么结果?
复杂流程图（分支较多、总宽度较宽）可以完整展示（比如自动缩小框图和流程图文本）

5. 当前遇到的是什么结果?
  1.复杂流程图（分支较多、总宽度较宽）不能完整展示，**请见附件**，谢谢
  2.编辑页面实时预览、阅读模式、以及导出

文档都不能完整展示较宽的流程

图

**Comment by lifei6671** [comment]
请尝试将 [TOC] 放在文档的第一行。

**Comment by hollydragon** [comment]
![toc](https://user-images.githubusercontent.com/12869713/49141334-53d1b700-f331-11e8-8d12-2a71910dfc66.png)
[TOC]已调整，如图片1，不过效果依旧，如图2，谢谢回复
![issue_still](https://user-images.githubusercontent.com/12869713/49141442-8a0f3680-f331-11e8-9070-e51d3c2b33b9.png)

**Comment by hollydragon** [comment]
你好，入职前图片所示，流程图右侧没有完全显示。
完全显示的话右侧的连接线不会中断，如附图所示：
![full_flow](https://user-images.githubusercontent.com/12869713/49141617-f68a3580-f331-11e8-8492-0d95d779f6e2.jpg)
