### ISSUE TITLE
 template: book/setting.tpl:67:59: executing "book/setting.tpl" at <.Model.ItemId>: can't evaluate field ItemId in type interface {}

### ISSUE THREAD

**Issue by heibaikn** [lifei6671/mindoc#404]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0-beta.2 更新日志

2. 你当前使用的是什么操作系统?
macOs

3. 你是如何操作的？
```
git clone https://github.com/lifei6671/mindoc.git

#添加
cd mindoc

dep ensure

go build -ldflags "-w"

./mindoc install

./mindoc
```

4. 你期望得到什么结果?
进行添加项目 和 项目空间管理

5. 当前遇到的是什么结果?
无法添加项目
![image](https://user-images.githubusercontent.com/17714507/49224391-50ffc080-f41c-11e8-8123-f405ed65f797.png)
![image](https://user-images.githubusercontent.com/17714507/49224460-72f94300-f41c-11e8-90ae-96437eac2f32.png)

**Comment by lifei6671** [comment]
没重现你的问题。

**Comment by heibaikn** [comment]
![image](https://user-images.githubusercontent.com/17714507/49292221-9fc65c80-f4e7-11e8-94c1-ee1be6defbfe.png)
再次删除安装 ，还是如此 无法添加项目空间

**Comment by lifei6671** [comment]
自己按手册安装吧。感觉你安装的有问题。
