### ISSUE TITLE
Markdown Table 渲染问题“|--|”

### ISSUE THREAD

**Issue by qingwuh** [lifei6671/mindoc#407]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0 beta

2. 你当前使用的是什么操作系统?
Windows

3. 你是如何操作的？
插入表格时
之前的版本
`
|标题|内容|
|--|
|标题|内容|
`即可，
但是更新后，必须为
`
|标题|内容|
|--|--|
|标题|内容|
`
请问这个有办法恢复吗，因为之前编辑table时，都用的是第一种形式，现在都没法渲染了。

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
升级了md的渲染内核，有些不标准的格式会不支持。
