### ISSUE TITLE
账号密码被明文保存【bug】

### ISSUE THREAD

**Issue by icibaaaww** [lifei6671/mindoc#409]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
   v2.0-beta.2

2. 你当前使用的是什么操作系统? 
   centos7

3. 你是如何操作的？
   谷歌浏览器登录保存账号密码，进系统后发布文章后，在数据库md_bolgs表中password字段会自动填写为登录账号的明文密码。另外测试不保存密码登录系统发布文章，该字段不会有账号密码。

4. 你期望得到什么结果?
    密码不保存或者进行加密。

5. 当前遇到的是什么结果?
    账号密码被明文保存有安全隐患。

**Comment by lifei6671** [comment]
文章和项目的访问密码本身就是明文储存的，这个没有加密的必要性。没人会接触到你们的数据库。

**Comment by icibaaaww** [comment]
> 文章和项目的访问密码本身就是明文储存的，这个没有加密的必要性。没人会接触到你们的数据库。

谢谢回复！
反馈的问题主要还是 创建的不加密文章的密码字段会自动读取到浏览器保存的密码并保存到数据库中。这不影响文章的查看、编辑。不过管理员根据这个漏洞就可以看到用户的账号密码。

**Comment by lifei6671** [comment]
自动填充是你浏览器设置问题。
