### ISSUE TITLE
功能建议-点击自动展开下级文档

### ISSUE THREAD

**Issue by Daidaiduo** [lifei6671/mindoc#411]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64.zip     v2.0-beta.2

2. 你当前使用的是什么操作系统?
Ubuntu 16.04 x64

3. 你是如何操作的？
正常操作

4. 你期望得到什么结果?
如[Go语言标准库实例](https://www.iminho.me/wiki/docs/golang-standard-library-example/README.md)

我的想法是当我点击这其中的任何一个文档的标题，系统自动跳到该文档，并同时自动展开其中的下级文档。
比如点击“第九章 测试”标题，系统自动跳转到该文档，并自动展开所属的二级文档，再次点击“第九章 测试”标题则进行收缩。

5. 当前遇到的是什么结果?
点击一级文档后无法自动展开二级文档，需要点击左边的展开按钮才行

**Comment by lifei6671** [comment]
本身就是这么设计的。
