### ISSUE TITLE
注册默认数据库失败

### ISSUE THREAD

**Issue by zhujitop** [lifei6671/mindoc#414]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0-beta.2

2. 你当前使用的是什么操作系统?

centos7
mysq8.0
3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

[E] [command.go:57]  注册默认数据库失败-> register db Ping `default`, Error 1045: Acces
s denied for user 'root'@'127.0.0.1' (using password: YES) 

用的mysql8.0，数据结构utf8mb4_general_ci.

数据地址是localhost

我在app.conf里面都改成自己的了。

然后安装提示数据库不对，还是在读取127.0.0.1

**Comment by lifei6671** [comment]
英文提示已经很明确了。

**Comment by lifei6671** [comment]
英文提示已经很明确了。

**Comment by zhujitop** [comment]
> 英文提示已经很明确了。

这个提示是数据库连不上。

但是数据库用户名密码没有错，数据库连接是localhost。
在安装你这个的时候还在读取默认的说是127.0.0.1。
