### ISSUE TITLE
mindoc如何配置CDN加速

### ISSUE THREAD

**Issue by rumosky** [lifei6671/mindoc#416]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
1.0.2

2. 你当前使用的是什么操作系统?
cent7.5

3. 你是如何操作的？
在又拍云上配置CDN

4. 你期望得到什么结果?
可以正常加速

5. 当前遇到的是什么结果?

但是配置了CDN之后，登录时验证码无法刷新。CDN缓存是关闭的。配置文件里面的CDN缓存路径不知道怎么添写，我写了static文件夹里的静态文件路径，但是没用。验证码无法刷新。

（顺便问一下，那个付费群怎么解散了？问问题没人回就罢了，咋直接解散了？）

**Comment by lifei6671** [comment]
MinDoc不支持CDN，只支持回源的CDN，请自行查看手册，配置CDN地址。
开源产品没那么多精力服务大家，请谅解。

**Comment by simplove** [comment]
https://github.com/mindoc-org/mindoc/issues/880#issuecomment-1635896360
问题处理好了，详见上面
