### ISSUE TITLE
minidoc 支持黏贴word 的样式

### ISSUE THREAD

**Issue by yhh1234** [lifei6671/mindoc#419]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

Window X64
2. 你当前使用的是什么操作系统?
Window X64

3. 你是如何操作的？
像 有道云和 qq 的云文档 支持直接黏贴有颜色和格式的文档 

4. 你期望得到什么结果?
支持代码高亮的内容自动黏贴 

5. 当前遇到的是什么结果?
支持这种编排模式 提供paser 方面 缅怀 复制黏贴的发明开创者

**Comment by lifei6671** [comment]
不要再提word相关的issue了，mindoc不会支持word转markdown的，这根本是两个东西。
