### ISSUE TITLE
未被使用的附件(图片)如何清理？

### ISSUE THREAD

**Issue by sotex** [lifei6671/mindoc#420]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64

2. 你当前使用的是什么操作系统?
CentOS 7

3. 你是如何操作的？
在使用一段时间后，很多文章经过多次变更修改，导致一些图片文件不再被使用。进入附件管理中只能知道图片的大小等信息，无法知道其是否被使用，想要知道只能去对比文章。

4. 你期望得到什么结果?
如果能够后台运行一个任务去刷新附件（图片）的使用（引用）情况，以便能够方便的清理未使用的附件。或者有清理未被使用附件的接口也很好。

5. 当前遇到的是什么结果?
大量附件（图像）难以筛选出未被使用的部分。

**Comment by lifei6671** [comment]
图片和附件存在数据库中，你可以直接根据数据库清理。
