### ISSUE TITLE
docker 搭建镜像希望缩小体积

### ISSUE THREAD

**Issue by hlj1350** [lifei6671/mindoc#421]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
  v2.0-beta.2

2. 你当前使用的是什么操作系统?
docker 

3. 你是如何操作的？
使用dockerfile 创建docker镜像

4. 你期望得到什么结果?
创建镜像成功，并运行成功

5. 当前遇到的是什么结果?
创建镜像成功，运行失败，提示
/usr/local/bin/start.sh: line 11: /opt/mindoc/mindoc_linux_amd64: not found

```
FROM ubuntu:16.04

MAINTAINER fhzy

RUN mkdir -p /opt/mindoc

VOLUME ["/opt/mindoc/database","/opt/mindoc/uploads"]

ENV MINDOC_DB_ADAPTER=sqlite3 MINDOC_DB_HOST=127.0.0.1 MINDOC_DB_PORT=3306 MINDOC_DB_DATABASE=./database/mindoc.db MINDOC_DB_USERNAME=root MINDOC_DB_PASSWORD=123456



COPY mindoc /opt/mindoc
COPY start.sh /usr/local/bin/


WORKDIR /opt/mindoc

RUN chmod +x /opt/mindoc/mindoc_linux_amd64 \
&& chmod +x /usr/local/bin/start.sh


EXPOSE 8181

CMD ["start.sh"]

```
把 ubuntu:16.04 替换为 apline:3.8 后创建镜像成功，运行失败

**Comment by lifei6671** [comment]
两个系统不完全兼容。不能直接换个标签就可以的。
