### ISSUE TITLE
文档已备其他人修改确定覆盖已存在的文档吗？

### ISSUE THREAD

**Issue by kswen** [lifei6671/mindoc#422]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
beta-2

2. 你当前使用的是什么操作系统?
centos 7

3. 你是如何操作的？
保存文档

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

保存文档死循环，一直提示:
文档已备其他人修改确定覆盖已存在的文档吗？

点确定还是不断弹出来这个窗口

**Comment by lifei6671** [comment]
没重现你的问题。

**Comment by lifei6671** [comment]
你点确定就行了，或者取消了不覆盖。

**Comment by kswen** [comment]
额，是个死循环，不断的弹出来的。
我开始以为是缓存问题，清理了缓存还是一样。
换了不同的浏览器还是一样，我怀疑是我账号问题，换了台电脑登录编辑，一切正常。。。
切换回来，再在我的电脑上编辑，问题马上重现

**Comment by lifei6671** [comment]
看看是不是安装了什么插件，导致脚本执行出错。

**Comment by kswen** [comment]
cover: yes
version: 1547633118

理论上既然都确定不覆盖了那应该不会再弹出来了才对

**Comment by kswen** [comment]
![image](https://user-images.githubusercontent.com/4409710/51242313-9cfdc900-19ba-11e9-8903-7f43d01c0a01.png)

**Comment by kswen** [comment]
![image](https://user-images.githubusercontent.com/4409710/51242433-eea65380-19ba-11e9-9440-dbfbafaa7f38.png)

**Comment by kswen** [comment]
终于知道原因了，网卡MTU问题
