### ISSUE TITLE
希望增加和sosoapi 的一些功能 

### ISSUE THREAD

**Issue by yhh1234** [lifei6671/mindoc#423]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
window X64

2. 你当前使用的是什么操作系统?

WINDOW 2016 server 
3. 你是如何操作的？
直接增加 api 文档 
http://www.sosoapi.com/pass/help/manual.htm#sub-title-3.1

4. 你期望得到什么结果?
http://www.sosoapi.com/pass/help/manual.htm#sub-title-3.1 类似这种的功能提供对应一些工具 

5. 当前遇到的是什么结果?
更接近和更完善的API 接口文档管理系统

**Comment by lifei6671** [comment]
MinDoc 是专注于文档的，不是接口。
