### ISSUE TITLE
如何添加网站标签页ico

### ISSUE THREAD

**Issue by rumosky** [lifei6671/mindoc#426]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
1.0.2正式版

2. 你当前使用的是什么操作系统?
centOS7.6

3. 你是如何操作的？
在网站根目录放了favicon.ico文件

4. 你期望得到什么结果?
浏览器标签页正常显示ico图标

5. 当前遇到的是什么结果?
QQ浏览器，IE，edge都正常显示ico图标，但是谷歌浏览器不显示，想问问，mindoc官方网站的ico是怎么添加的？

**Comment by lifei6671** [comment]
覆盖根目录下的 favicon.ico 文件即可。不显示请清空浏览器缓存。

**Comment by sanqiushu-ns** [comment]
我这里是谷歌浏览器显示正常，然后其他浏览器不显示，不知道跟项目有关系没。
