### ISSUE TITLE
使用令牌访问显示403无权限

### ISSUE THREAD

**Issue by chukiller** [lifei6671/mindoc#427]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

v2.0-beta.2

2. 你当前使用的是什么操作系统?

CentOS7

3. 你是如何操作的？

使用令牌访问显示403无权限

4. 你期望得到什么结果?

可以正常访问

5. 当前遇到的是什么结果?

显示无权限
![image](https://user-images.githubusercontent.com/38487441/51159331-9dffff00-18c3-11e9-94c3-085d9bcf6d55.png)
匿名访问开启了
![image](https://user-images.githubusercontent.com/38487441/51159349-bbcd6400-18c3-11e9-9164-d864baf69821.png)

**Comment by lifei6671** [comment]
令牌之后的版本会删除该功能，建议用密码代替。

**Comment by chukiller** [comment]
> 令牌之后的版本会删除该功能，建议用密码代替。

那请问现在的2.0版本有办法解决吗，或者回退到之前的某个版本

**Comment by lifei6671** [comment]
升级后不支持退回。现在2.0版本就有密码功能，只是没关闭令牌。

**Comment by chukiller** [comment]
> 升级后不支持退回。现在2.0版本就有密码功能，只是没关闭令牌。

请问一下，我现在有个说明文档是在APP里面嵌入的，有办法不需要输入密码就可以访问的吗。除了公开。

**Comment by lifei6671** [comment]
如果只是一篇文章的话，可以直接发博文就行了。如果是项目中的一篇文章，也可以通过博文的链接功能链接过去。
如果是整个项目都需要访问，目前是没办法实现。

**Comment by chukiller** [comment]
> 如果只是一篇文章的话，可以直接发博文就行了。如果是项目中的一篇文章，也可以通过博文的链接功能链接过去。
> 如果是整个项目都需要访问，目前是没办法实现。

明白了，谢谢。不过真的无法退回吗，整个文件夹替换掉应该是可以的吧

**Comment by lifei6671** [comment]
数据库结构变了，如果你之前有备份还可以，如果没备份就无法退回了。
