### ISSUE TITLE
成员管理添加问题

### ISSUE THREAD

**Issue by yhh1234** [lifei6671/mindoc#432]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

MinDoc WindowX64  DB 为SQLlite
2. 你当前使用的是什么操作系统?
WindowX64

3. 你是如何操作的？
增加新成员  出现无法录入账号保存的情况

4. 你期望得到什么结果?
增加新成员 功能正常

5. 当前遇到的是什么结果?

无法正常使用此功能

**Comment by lifei6671** [comment]
请详细描述下是什么问题？不太明白什么叫无法录入账号保存的情况？
