### ISSUE TITLE
账号命名规则

### ISSUE THREAD

**Issue by qrqhuang** [lifei6671/mindoc#433]
目前账号只允许字母+数字

但我接入公司ldap后， 有部分人员其账号含特殊字符  `-`，登陆提示：自动注册LDAP用户错误 账号只能由英文字母数字组成，且在3-50个字符 ，  看能不能适当放开下

对应匹配正则 `RegexpAccount `  [enumerate.go](https://github.com/lifei6671/mindoc/blob/master/conf/enumerate.go)

**Comment by lifei6671** [comment]
可以按照贵司的需要修改正则后重新编译。不通公司的命名规则都不一致，这个无法保证适应所有公司。

**Comment by qrqhuang** [comment]
你这边简单放开下不就行了， 允许如`@-`等常见字符
手工编译我是不是还要搭建golang环境， 不会弄呢
