### ISSUE TITLE
请教一下如何支持latex公式

### ISSUE THREAD

**Issue by August-Ghost** [lifei6671/mindoc#436]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64 v2.0-beta.2

2. 你当前使用的是什么操作系统?
win10 + docker

3. 你是如何操作的？

4. 你期望得到什么结果?
支持解析markdown中的latex。或者告诉我如何在文章的html模板里插入Mathjax.js，该修改哪个文件

5. 当前遇到的是什么结果?
latex公式无法正常显示

**Comment by lifei6671** [comment]
编辑器是基于editor.md的，建议看editor.md的官方文档。

**Comment by thewon86** [comment]
http://editor.md.ipandao.com/examples/katex.html
这个吗？这个好像不支持多项式和矩阵。只能用图片替代了吗？

**Comment by thewon86** [comment]
> 编辑器是基于editor.md的，建议看editor.md的官方文档。

很多KaTex语法都不支持，是editor.md的原因吗？
