### ISSUE TITLE
建议优化图片粘贴部分

### ISSUE THREAD

**Issue by cnspray** [lifei6671/mindoc#439]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0-beta.2

2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？

正常编辑时，复制图片文件，进行粘贴，或word中包含了文字和图片复制后进行粘贴。
4. 你期望得到什么结果?

像看云一样，复制的图片文件，或复制的内容中包含了文本和图片，能实现图片的自动上传。
5. 当前遇到的是什么结果?
只能粘贴文字部分，图片部分不能粘贴，只能将图片打开后单独复制图片粘贴。

**Comment by lifei6671** [comment]
看云也不支持图片和文字混合上传。我测试的是文字和图片混合的时候只能转换成一张图片。

**Comment by cnspray** [comment]
现在是用typora这个工具来将word转换为MD。但就是导入的时候会提示有几张图片找不到。
