### ISSUE TITLE
同步预览错位

### ISSUE THREAD

**Issue by cnspray** [lifei6671/mindoc#442]
请按照一下格式提交issue，谢谢！

你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
v2.0-beta.2

你当前使用的是什么操作系统?
windows

你是如何操作的？

正常编辑时，预览与编辑同步。
4. 你期望得到什么结果?
正常编辑时，预览与编辑同步。
5. 当前遇到的是什么结果?
正常编辑时，预览与编辑不同步，在增加标题后，当标题过多时，右侧的预览区域与编辑区域错位。

**Comment by lifei6671** [comment]
这是正常现象，编辑的内容所占高度肯定要比语言的要少。尤其是加上图片以后，计算高度没那么精确。
