### ISSUE TITLE
配置了CDN但是没反应

### ISSUE THREAD

**Issue by rumosky** [lifei6671/mindoc#443]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`mindoc_linux_amd64 version`)?
1.0.2正式版

2. 你当前使用的是什么操作系统?
CentOS7.6 x64

3. 你是如何操作的？
在配置文件CDN内容上填写如下：
```text
cdn=https://cdn.rumosky.com/mindoc/
cdnjs=https://cdn.rumosky.com/mindoc/
cdncss=https://cdn.rumosky.com/mindoc/
cdnimg=https://cdn.rumosky.com/mindoc/
```

上述CDN地址mindoc文件夹内包含static和upload两个文件夹。

4. 你期望得到什么结果?
我期望网站调用的css和js是CDN地址上的资源，但是，F12查看之后，网站调用的是本地的资源，是网站域名之下的。不是cdn.rumosky.com下的。如果删除本地的static文件夹，就会导致网站样式丢失。

目前的问题是，配置文件上填写了CDN信息，但是没有生效。请问这是什么情况？

**Comment by rumosky** [comment]
注意到作者项目演示站点应该也是将css和js放在了CDN上，在F12上查看你的演示站点是正常的。能否提供一下你的配置文件是怎么填写的，cdn静态资源目录的路径是什么？谢谢！

**Comment by lifei6671** [comment]
配置为需要重启应用。
另外，这个配置不是将静态文件同步到CDN，只是将页面的文件地址改成CDN的链接。
具体的文件同步需要在CDN上配置源站。
