### ISSUE TITLE
导出生成的content.epub已损坏

### ISSUE THREAD

**Issue by thinwalk** [lifei6671/mindoc#444]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  
MinDoc last version =>  v2.0-beta.2

2. 你当前使用的是什么操作系统?

Linux version 4.4.0-112-generic (buildd@lgw01-amd64-010) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) )

3. 你是如何操作的？

当点击导出，跳转 http://192.168.5.100:8182/export/test001?output=epub
生成与下载的epub文件，打开之后显示已损坏，而且转出的PDF显示异常

4. 你期望得到什么结果?

epub正常打开，pdf正常显示

5. 当前遇到的是什么结果?

生成与下载的epub文件，打开之后显示已损坏，而且转出的PDF显示异常

**Comment by lifei6671** [comment]
导出功能用的事Calibre，请检查Calibre是否可以正常转换。

**Comment by thinwalk** [comment]
hi，我看了你的代码，转换成epub的过程，是将生产在、tmp/..../output的html文件进行zip打包，应该是不存在转换的，但是我打开这个生成的content.epub就是已经损坏的(用mac打开会有提示)，所以我下载了一个epub的工具，打开content.epub之后，会提示修复，修复之后可以正常打开，修复之后的文件目录已经改变了。
我觉得导出epub的功能非常重要，因为后面的PDF以及其他格式都是根据epub导出的，如果epub有问题，那个导出的PDF也会异常，并且在我本地确实发生了。
thx!

**Comment by lifei6671** [comment]
我Mac测试没问题。

**Comment by thinwalk** [comment]
@lifei6671  请问下，你有微信或者QQ吗？我们能交流下吗？我把有问题的epub发给你

**Comment by lifei6671** [comment]
QQ867-311-066

**Comment by thinwalk** [comment]
感谢作者~
