### ISSUE TITLE
目录的顺序

### ISSUE THREAD

**Issue by ghostry** [lifei6671/mindoc#445]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

docker

3. 你是如何操作的？
编辑文档的时候，右边的目录，我想要拖动改变顺序

4. 你期望得到什么结果?
能改变顺序

5. 当前遇到的是什么结果?
拖动没有反应，右键也没有上移下移。

**Comment by lifei6671** [comment]
拖动可以改变顺序。
