### ISSUE TITLE
如何去除标签页的Powered by mindoc字样（别生气，请看一下内容，谢谢）

### ISSUE THREAD

**Issue by rumosky** [lifei6671/mindoc#447]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
正式版1.0.2

2. 你当前使用的是什么操作系统?
CentOS7.6 x64

3.问题描述
删除了view文件夹里面所有文件的<title></title>标签中的Powered by mindoc版权信息，但是打开文档之后，只要点击左侧的目录，还是会出现Powered by mindoc，刷新一下页面就会消失。
起初以为是下载的发行版不能修改。后来自己编译了一下，在编译之前，已经删除了源码里的Powered by mindoc，具体路径是源代码controllers/DocumentController.go文件中第152行`data.Title = doc.DocumentName + " - Powered by MinDoc"`，删除了之后编译，结果还是在文档目录那里，有Powered by mindoc，不知道是为什么。
后来，我用notepad++打开编译好的mindoc_linux_amd64执行文件，搜索Powered by mindoc，发现还是有。明明源码里面已经删了。
对不起，不是不尊重版权，只是有强迫症，在自己站点的介绍上面已经说明了使用的是mindoc文档系统。之前编译mindoc，折腾了两天。纯小白。最后终于可以编译成功了。但是就是不知道问题出在什么地方。所以想问问作者。请不要生气。文档目录点击之后，就会出现Powered by mindoc版权信息。其他的界面都没有。这是在哪里控制的？view文件夹里的确定都删除了。

**Comment by lifei6671** [comment]
源码已提供，不再提供技术支持。
