### ISSUE TITLE
编译报错问题请教

### ISSUE THREAD

**Issue by athlonreg** [lifei6671/mindoc#448]
Hello! 
我从源码下载之后，在goland编译时遇到了问题，按照wiki里面说的先安装了dep包管理器，然后在GOPATH下创建了src/github.com/lifei6671，然后在新建的文件夹下执行了go get github.com/lifei6671/mindoc拉取下来了源码，然后配置好梯子之后，在源码目录运行dep ensure后执行go build，报错如下
![20190222152640](https://user-images.githubusercontent.com/28970198/53226544-5173c480-36b6-11e9-942b-fc51e7a0b2dd.png)

**Comment by lifei6671** [comment]
感觉你用的应该是go1.11并且强制开启了module功能。目前mindoc不支持module。

**Comment by athlonreg** [comment]
> 感觉你用的应该是go1.11并且强制开启了module功能。目前mindoc不支持module。

感谢回复解答，经过大量测试，最后发现将源码所有对blackfriday进行import的地方都改成了github后就没事了，可能是gopkg的问题
