### ISSUE TITLE
配合 Nginx 让 MinDoc 运行在二级子目录 部分功能异常

### ISSUE THREAD

**Issue by asdfhalkehflkajdhf** [lifei6671/mindoc#450]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  v2.0-beta.2
MinDoc last version =>  v2.0-beta.2

2. 你当前使用的是什么操作系统?
centos 7
Linux iZ2zeg8qx376d7t90qa8otZ 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

3. 你是如何操作的？
就是基本 配合 Nginx 让 MinDoc 运行在二级子目录 能不改的，就没改动。

4. 你期望得到什么结果?
基本功能可以二级代理

5. 当前遇到的是什么结果?

遇到的问题是uploads 数据加载失败。编译过程中上图片，链接等内容，失效

**Comment by lifei6671** [comment]
看手册 <https://www.iminho.me/wiki/docs/mindoc/mindoc-sub-dir.md>
