### ISSUE TITLE
导入和导出可以支持summary.md定义吗

### ISSUE THREAD

**Issue by hs7378** [lifei6671/mindoc#451]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

v2.0-beta.2 
2. 你当前使用的是什么操作系统?

Windows 2016
3. 你是如何操作的？
、、、

4. 你期望得到什么结果?
导出和导入支持类似其他开源平台通用的summary.md，左侧的目录能正确显示

5. 当前遇到的是什么结果?
目前我从github导出的书，导入后发现有点问题，你应该是按照文件名的排序来设置的吧？像2.11章节会排在2.2前面

**Comment by lifei6671** [comment]
左侧目录是根据导入文件的文件名或者是文件的第一个h标签来决定的。

**Comment by hs7378** [comment]
这个顺序就是按照文件名去排序是吧？  能不能和gitbook那样用summary.md文件来自定义左侧目录

**Comment by lifei6671** [comment]
左侧目录是根据文档查询出来生成的，不是自定义的。
