### ISSUE TITLE
请问如何支持 SVG 文件显示为图片？

### ISSUE THREAD

**Issue by woocatcat** [lifei6671/mindoc#452]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
   good_linux_amd64 v1.0.2

2. 你当前使用的是什么操作系统?
  Windows2008 R2

3. 你是如何操作的？
 在编辑环境下，点击“图片”，选择 SVG 格式文件，上传后无法显示图片内容。但是手工修改图片文件链接后，可以正常显示 SVG 图片内容。
![aedef7ffd42b513846fa8182ee0c2a69](https://user-images.githubusercontent.com/44799641/53461059-3b7d4f80-3a7a-11e9-8a55-62c7d06697ce.jpg)
![35733d5abfe94da097158928962c1020](https://user-images.githubusercontent.com/44799641/53461066-4c2dc580-3a7a-11e9-8275-ad1eac71ec28.jpg)
![5d7b7e34e46d6bcdcd099bdaeb621335](https://user-images.githubusercontent.com/44799641/53461114-75e6ec80-3a7a-11e9-9103-2f9e3af1cb55.jpg)

4. 你期望得到什么结果?
系统能够自动将SVG识别为图片文件显示

5. 当前遇到的是什么结果?
 点击“图片”，选择 SVG 格式文件，上传后无法显示图片内容。

**Comment by lifei6671** [comment]
目前上传是不支持穿svg格式，你可以将svg当做附件上传。
