### ISSUE TITLE
导出markdown时报错

### ISSUE THREAD

**Issue by starjoe** [lifei6671/mindoc#453]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

v2.0-beta.2

2. 你当前使用的是什么操作系统?

centos6

3. 你是如何操作的？

![image](https://user-images.githubusercontent.com/28501688/53482845-1e1ca580-3abb-11e9-835d-84a02e0c15ef.png)
导出功能已经开启，但是在导出的时候还是会显示系统没有开启导出功能。
![image](https://user-images.githubusercontent.com/28501688/53482897-3db3ce00-3abb-11e9-852a-1bc7d04dbb19.png)

**Comment by lifei6671** [comment]
请看手册。 <https://www.iminho.me/wiki/docs/mindoc/mindoc-summary.md>
