### ISSUE TITLE
如何写页面右边带导航

### ISSUE THREAD

**Issue by MetSystem** [lifei6671/mindoc#455]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0-beta.2 

2. 你当前使用的是什么操作系统?
windows
请问这个要这么写右边才会出现导航
![image](https://user-images.githubusercontent.com/7943054/53485189-8d48c880-3ac0-11e9-8bfd-5d9525bf41b1.png)

**Comment by lifei6671** [comment]
请看手册 <https://www.iminho.me/wiki/docs/mindoc/mindoc-summary.md>

**Comment by huangjun0124** [comment]
> 请看手册 https://www.iminho.me/wiki/docs/mindoc/mindoc-summary.md

你好，这个[TOC]好像只支持项目的文档，单独写的文章不支持右侧停靠呢。它显示在文章最开头了
