### ISSUE TITLE
项目空间管理 详情项目缺少封面图

### ISSUE THREAD

**Issue by MetSystem** [lifei6671/mindoc#456]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0-beta.2 

2. 你当前使用的是什么操作系统?
windows

3.如何操作
进入项目空间管理 -》详情
![image](https://user-images.githubusercontent.com/7943054/53485371-047e5c80-3ac1-11e9-9958-45a9376e457d.png)

**Comment by lifei6671** [comment]
没发现你的问题。请检查自己的服务器配置。
