### ISSUE TITLE
希望添加置顶功能

### ISSUE THREAD

**Issue by iamazy** [lifei6671/mindoc#457]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

godoc_linux_amd64_0.13.4
2. 你当前使用的是什么操作系统?

ubuntu16.04
3. 你是如何操作的？

部署到内部服务器使用
4. 你期望得到什么结果?
有文章，项目置顶功能，有全局置顶，和用户个人可见项目置顶

5. 当前遇到的是什么结果?
目前没找到该功能，希望开发团队可以考虑下，谢谢啦

**Comment by lifei6671** [comment]
可以用排序代替，感觉置顶用的地方不是很多。
