### ISSUE TITLE
Dockerfile时区不生效问题

### ISSUE THREAD

**Issue by ygqygq2** [lifei6671/mindoc#458]
Dockerfile编译出来的image缺少时区文件，安装时需要添加以下行解决此问题。
`apk add --no-cache tzdata`

**Comment by lifei6671** [comment]
我设置了好像没有效果

**Comment by ygqygq2** [comment]
@lifei6671 我fork了你的项目，在docker hub上这个，就是添加了这一行。只是在前面那个地方。可以用。你看看
`ygqygq2/mindoc:latest`

**Comment by lifei6671** [comment]
可以了，感谢。
