### ISSUE TITLE
建议优化和完善分词搜索

### ISSUE THREAD

**Issue by cnspray** [lifei6671/mindoc#459]
请按照一下格式提交issue，谢谢！

你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
v2.0-beta.2

你当前使用的是什么操作系统?
windows

你是如何操作的？
搜索时，使用空格分割关键字。
4. 你期望得到什么结果?
能搜索出包含所分割关键字的信息。
5. 当前遇到的是什么结果?
搜索结果不正确。

**Comment by lifei6671** [comment]
搜索用的是数据库的like语法，无法实现分词。
如果引入分词和搜索引擎又会导致过于占用内存资源。

**Comment by cnspray** [comment]
谢谢老大的及时回复，那能不能像MINDOC的分支bookstack1.6的那样，引用elasticsearch用参数控制是否启用呢？

**Comment by cnspray** [comment]
老大，如果把空格先替换成%，再执行like查询，这样可以吗？

**Comment by lifei6671** [comment]
目前实现的就是将空格替换成了%再组装的SQL。
ES的以后有时间再提供接口吧。

**Comment by cnspray** [comment]
https://www.iminho.me/wiki/docs/mindoc/config.md“MinDoc 大部分配置信息都在源目录下的conf/app.conf中。只有少部分可在管理后台修改。

因此，如果想要修改 MinDoc 的配置请找到配置文件，使用文本编辑器打开配置文件进行修改。”我对官方的这个文档检索，输入“大  信”，没有结果。

**Comment by lifei6671** [comment]
官网的不是最新版的mindoc，你去演示站看，： <https://doc.iminho.me/search?keyword=%E7%94%A8+%E5%8F%A3>

**Comment by cnspray** [comment]
老大，阅读界面的那个搜索好像不行，就目录旁边的那里搜索。

**Comment by lifei6671** [comment]
阅读界面搜索没加，这个地方的利用率比较低。
