### ISSUE TITLE
请问开源协议是什么？是否可以用于不开源的商业项目的文档显示？

### ISSUE THREAD

**Issue by conanliuhuan** [lifei6671/mindoc#461]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64

2. 你当前使用的是什么操作系统?
Windows10

3. 你是如何操作的？
正常安装流程，部署到外网

4. 你期望得到什么结果?
请问开源协议是什么？

5. 当前遇到的是什么结果?
由于不清楚开源协议，也找不到相关说明，因此我们公司在选型的时候不太敢用。能否告知一下是否可以用于不开源的商业项目的文档显示？

**Comment by lifei6671** [comment]
github上通常做法是在根目录放一个`LICENSE.md`文件来声明开源协议。

**Comment by conanliuhuan** [comment]
> 
> 
> github上通常做法是在根目录放一个`LICENSE.md`文件来声明开源协议。

many thanks!
