### ISSUE TITLE
1.0.2升级到2.0之后打开项目500错误

### ISSUE THREAD

**Issue by rumosky** [lifei6671/mindoc#465]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0正式版本

2. 你当前使用的是什么操作系统?
CentOS7.6 64位

3. 你是如何操作的？
之前的版本是1.0.2正式版，升级到2.0正式版之后，由于数据库修改了，我在后台将数据库恢复了一下，就是把之前项目的内容又插入到新的数据库对应的表里面。结果在前台打开项目之后，显示500服务器错误，找不到项目

4. 你期望得到什么结果?
如何恢复我的项目文档，数据库结构修改了，如何完美的升级。

5. 当前遇到的是什么结果?
无法恢复之前的项目，在前台首页有项目，但是打开之后显示500服务器错误找不到项目

**Comment by lifei6671** [comment]
看下控制台是什么错误。
