### ISSUE TITLE
在win10宿主机中使用docker容器，路径无法映射

### ISSUE THREAD

**Issue by jobsfan** [lifei6671/mindoc#466]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
用一下命令安装的最新版
docker run --name=mindoc --restart=always -v "D:/document/docker/mindoc/uploads":/mindoc/uploads -v "D:/document/docker/mindoc/database":/data/database -e DB_ADAPTER=sqlite3 -e MYSQL_INSTANCE_NAME=./database/mindoc.db -e CACHE=true -e CACHE_PROVIDER=file -e ENABLE_EXPORT=true -p 8181:8181 -d registry.cn-hangzhou.aliyuncs.com/lifei6671/mindoc-docker:latest

2. 你当前使用的是什么操作系统?
windows 10

3. 你是如何操作的？
就执行上面的docker命令，通过本地ip:8181能打开，但是在宿主机里面找不到数据库sqlite3的文件，以及上传测试的封面图等文件。感觉上 -v映射的两个目录都没有作用

4. 你期望得到什么结果?
至少数据库和上传文件要能拿出来，要不然将来数据迁移会存在问题

5. 当前遇到的是什么结果?
就是综上所述

**Comment by lifei6671** [comment]
你进docker看下配置文件设置的目录地址再重新启动镜像。

**Comment by jobsfan** [comment]
@lifei6671 
我后面用docker-compose命令进的，能映射宿主机和docker容器的目录，但是有个新的问题

MinDoc_New:
  image: registry.cn-hangzhou.aliyuncs.com/lifei6671/mindoc-docker:latest（问题出在这个地方！！！！）
  privileged: false
  restart: always
  ports:
    - 8181:8181
  volumes:
    - D:\document\docker\mindoc\database:/mindoc/database
    - D:\document\docker\mindoc\uploads:/mindoc/uploads
    #- D:\document\docker\mindoc\conf:/mindoc/conf
  environment:
    - MINDOC_RUN_MODE=prod
    - MINDOC_DB_ADAPTER=mysql
    - MINDOC_DB_HOST=我的数据库ip
    - MINDOC_DB_PORT=3306
    - MINDOC_DB_USERNAME=mindoc
    - MINDOC_DB_PASSWORD=我的密码
    - MINDOC_DB_DATABASE=mindoc
    - MINDOC_CACHE=true
    - MINDOC_CACHE_PROVIDER=file
    - MINDOC_ENABLE_EXPORT=false
    - MINDOC_BASE_URL=
    - MINDOC_CDN_IMG_URL=
    - MINDOC_CDN_CSS_URL=
    - MINDOC_CDN_JS_URL=
  dns:
    - 223.5.5.5
    - 223.6.6.6


===================问题描述====================

如果我用
registry.cn-hangzhou.aliyuncs.com/lifei6671/mindoc-docker:latest
用这个镜像的话
1、mysql数据库并没有使用【去数据库看，里面是个空的一张表都没有】 ×
2、但是文档导出pdf之类的格式，可以用，会提示正在转换 √

用registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v2.0-beta.2
用这个镜像的话
1、数据库mysql，没问题 √
2、导出pdf等格式，直接提示500错误 ×

我把conf这个目录映射到宿主机，发现它和example是一模一样的，但是呢，我不确定上面那两个镜像对应的配置文件是否是一直，就是不同的版本，配置项规定是不是一样的。
