### ISSUE TITLE
项目空间不支持权限设置

### ISSUE THREAD

**Issue by sdjngl123** [lifei6671/mindoc#469]
请按照一下格式提交issue，谢谢！
 
1. 版本：mindoc_windows_amd64.7z

2. 操作系统：windows

3. 操作现象：系统管理员创建的项目空间，其他用户创建项目时可以随意选择任意的项目空间

4. 期望得到的效果：项目空间支持权限设置，是否允许其他用户将项目写入此项目空间内。

5. 当前遇到的结果：系统管理员创建的项目空间，其他普通用户可以在此项目空间新建项目。

**Comment by lifei6671** [comment]
项目空间可以理解成分类，怎么会分类也设置权限呢？

**Comment by cnspray** [comment]
作者不如把这个的汉字改成分类好了，我第一次的时候也理解为和数据库表空间类似的。

**Comment by lifei6671** [comment]
@cnspray 有需要可以自己定制化，我是根据我的习惯开发的，可能不太实用其他人。
