### ISSUE TITLE
V2.0版本插入序列图，甘特图，表情 失败

### ISSUE THREAD

**Issue by aaxixi** [lifei6671/mindoc#471]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0

2. 你当前使用的是什么操作系统?

windows
3. 你是如何操作的？

快捷键插入  插入Emoji符号 ，插入时序图
4. 你期望得到什么结果?

插入表情，插入时序图
5. 当前遇到的是什么结果?
插入表情时候，浏览器弹出
**Error: settings.emoji == false**

时序图按照demo、插入还是代码，

``seq
participant C
participant B
participant A
Note right of A: By listing the participants\n you can change their order
``

``mermaid
graph TB
    id1(圆角矩形)--普通线-->id2[矩形]
    subgraph 子图表
        id2==粗线==>id3{菱形}
        id3-.虚线.->id4>右向旗帜]
        id3--无箭头---id5((圆形))
    end
``

**Comment by lifei6671** [comment]
编辑器没有开启emoji表情。
甘特图和时序图需要在代码块中。

**Comment by cnspray** [comment]
saveHTMLToTextarea : true,    // 保存 HTML 到 Textarea
                        searchReplace : true,
                        //watch : false,                // 关闭实时预览
                        htmlDecode : "style,script,iframe|on*",            // 开启 HTML 标签解析，为了安全性，默认不开启    
                        //toolbar  : false,             //关闭工具栏
                        //previewCodeHighlight : false, // 关闭预览 HTML 的代码块高亮，默认开启
                        emoji : true,
                        taskList : true,
                        tocm            : true,         // Using [TOCM]
                        tex : true,                   // 开启科学公式TeX语言支持，默认关闭
                        flowChart : true,             // 开启流程图支持，默认关闭
                        sequenceDiagram : true,       // 开启时序/序列图支持，默认关闭,
                        //dialogLockScreen : false,   // 设置弹出层对话框不锁屏，全局通用，默认为true
                        //dialogShowMask : false,     // 设置弹出层对话框显示透明遮罩层，全局通用，默认为true
                        //dialogDraggable : false,    // 设置弹出层对话框不可拖动，全局通用，默认为true
                        //dialogMaskOpacity : 0.4,    // 设置透明遮罩层的透明度，全局通用，默认值为0.1
                        //dialogMaskBgColor : "#000", // 设置透明遮罩层的背景颜色，全局通用，默认为#fff
@aaxixi

**Comment by aaxixi** [comment]
好的我马上去试试

**Comment by aaxixi** [comment]
> 编辑器没有开启emoji表情。
> 甘特图和时序图需要在代码块中。

能告诉我修改哪些文件吗，我不太清楚修改哪里的代码

**Comment by cnspray** [comment]
markdown_edit_template.tpl
找个<div></div>组，插入<a href="javascript:;" data-toggle="tooltip" data-title="emoji" unselectable="on"><i class="fa fa-smile-o" name="emoji" unselectable="on"></i></a>
editormd.js,emoji                : true, 
如果还不行，就再markdown.js中增加emoji                : true,

**Comment by cnspray** [comment]
\views\document\markdown_edit_template.tpl
增加
'''
<a href="javascript:;" data-toggle="tooltip" data-title="emoji" unselectable="on"><i class="fa fa-smile-o" name="emoji" unselectable="on"></i></a>
'''
editormd.js中emoji:true,
如果还不行，就在markdown.js中增加emoji:true,

**Comment by cnspray** [comment]
''<a href="javascript:;" data-toggle="tooltip" data-title="emoji" unselectable="on"><i class="fa fa-smile-o" name="emoji" unselectable="on"></i></a>''

**Comment by aaxixi** [comment]
> ''''

并且时序图也不行，不知道怎样开启

**Comment by cnspray** [comment]
editormd.js中,sequenceDiagram : true,
测试数据：
```seq
A->B: Message
B->C: Message
C->A: Message
```

```sequence
Andrew->China: Says Hello 
Note right of China: China thinks\nabout it 
China-->Andrew: How are you? 
Andrew->>China: I am good thanks!
```

**Comment by aaxixi** [comment]
> editormd.js中,sequenceDiagram : true,
> 测试数据：
> ![image](https://user-images.githubusercontent.com/19868606/56865510-aa870e00-6a01-11e9-9b2a-1a1be1c41036.png)

非常感谢，已经可以了，感觉官网的说明应该错了 ，如果官网有demo的md下载就好了。非常感谢。
