### ISSUE TITLE
代码块文件内容过多出现代码块滚动条

### ISSUE THREAD

**Issue by ihaiker** [lifei6671/mindoc#474]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 v2.0`)?

godoc_linux_amd64 v2.0

2. 你当前使用的是什么操作系统?
Centos 7.4

3. 你是如何操作的？
添加代码块的时候，如果代码块的长度足够多的话，代码块就出现了滚动条。

4. 你期望得到什么结果?
如何解决滚动条的问题

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
自己改下样式，去掉代码块限高。
