### ISSUE TITLE
controllers/AccountController.go:440:20: assignment mismatch: 2 variables but gocaptcha.NewCaptchaImage returns 1 values

### ISSUE THREAD

**Issue by iconan** [lifei6671/mindoc#475]
当前使用的是 v2.0
操作系统Mac OS 10.14.4 (18E226)
执行 go build 后报错：
controllers/AccountController.go:440:20: assignment mismatch: 2 variables but gocaptcha.NewCaptchaImage returns 1 values
具体代码块：
captchaImage, err := gocaptcha.NewCaptchaImage(140, 40, gocaptcha.RandLightColor())

**Comment by lifei6671** [comment]
注意下`github.com/lifei6671/gocaptcha`这个包的版本。
