### ISSUE TITLE
使用时，如何能实现文档的目录滑动的效果，如下图

### ISSUE THREAD

**Issue by GGFocus** [lifei6671/mindoc#478]
![image](https://user-images.githubusercontent.com/18533817/57716201-0791ed80-76ab-11e9-93fb-e8e42b368856.png)

**Comment by GGFocus** [comment]
因为自己目前编写的文档是显示不出来这种效果，找了很久，也没有在自己的文章中实现这种效果

**Comment by Grainfills** [comment]
@GGFocus 添加文档的时候会显示展开或者关闭在阅读的时候，可以关闭这个问题了

**Comment by GGFocus** [comment]
> @GGFocus 添加文档的时候会显示展开或者关闭在阅读的时候，可以关闭这个问题了

你好，您说的展开或关闭，那个应该是左侧的文档列表吧，我说的是在同一篇文章中的目录结构

**Comment by GGFocus** [comment]
> @GGFocus 添加文档的时候会显示展开或者关闭在阅读的时候，可以关闭这个问题了

我想要的效果是这样的
![image](https://user-images.githubusercontent.com/18533817/57751536-abfe4900-7718-11e9-8495-200c0a198fdb.png)

**Comment by lifei6671** [comment]
这个功能只支持markdown编辑器，首先文章中必须有`#`标记的标签，然后在文章的第一行使用`[TOC]`来标记需要显示导航。

**Comment by GGFocus** [comment]
> 这个功能只支持markdown编辑器，首先文章中必须有`#`标记的标签，然后在文章的第一行使用`[TOC]`来标记需要显示导航。

谢谢，已经解决了，原来是因为我写[toc]是小写，没有大写成[TOC]导致的

**Comment by jack361** [comment]
> > 这个功能只支持markdown编辑器，首先文章中必须有`#`标记的标签，然后在文章的第一行使用`[TOC]`来标记需要显示导航。
> 
> 谢谢，已经解决了，原来是因为我写[toc]是小写，没有大写成[TOC]导致的

为啥我现在加也不行,2024年3月27
