### ISSUE TITLE
beego 问题？

### ISSUE THREAD

**Issue by asing** [lifei6671/mindoc#480]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  v2.0
MinDoc last version =>  v2.0

2. 你当前使用的是什么操作系统?
Centos 7

3. 你是如何操作的？
裸机安装最新的mindoc，服务启动不了

4. 你期望得到什么结果?
正常启动运行

5. 当前遇到的是什么结果?
访问8181，提示错误如图所示
![WX20190517-132802](https://user-images.githubusercontent.com/345259/57905021-a1be8500-78a7-11e9-9ecc-ce76a4275a4c.png)

服务器端是这样的
![WX20190517-132833](https://user-images.githubusercontent.com/345259/57905045-b69b1880-78a7-11e9-91ef-2687e1e7b61f.png)

**Comment by QuQu0** [comment]
> 请按照一下格式提交issue，谢谢！
> 
> 1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
>    MinDoc current version =>  v2.0
>    MinDoc last version =>  v2.0
> 2. 你当前使用的是什么操作系统?
>    Centos 7
> 3. 你是如何操作的？
>    裸机安装最新的mindoc，服务启动不了
> 4. 你期望得到什么结果?
>    正常启动运行
> 5. 当前遇到的是什么结果?
>    访问8181，提示错误如图所示
>    ![WX20190517-132802](https://user-images.githubusercontent.com/345259/57905021-a1be8500-78a7-11e9-9ecc-ce76a4275a4c.png)
> 
> 服务器端是这样的
> ![WX20190517-132833](https://user-images.githubusercontent.com/345259/57905045-b69b1880-78a7-11e9-91ef-2687e1e7b61f.png)

看最后一张图提示，端口已经被占用了，换个端口试试？

**Comment by cnspray** [comment]
端口被占用
