### ISSUE TITLE
Vulnerability: Stored XSS and CSRF

### ISSUE THREAD

**Issue by 0x2E** [lifei6671/mindoc#481]
你好，发现 v2.0 存在存储型 XSS 和 CSRF 漏洞，可劫持任意用户。请给一个联系方式我把漏洞细节给你。

----

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

**mindoc_linux_amd64 v2.0**

2. 你当前使用的是什么操作系统?
3. 你是如何操作的？
4. 你期望得到什么结果?
5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
我知道你说的问题，目前编辑器是支持嵌入HTML标签的。除了已知的问题，其他前嵌入非法的HTML是需要使用者团队来控制。
目前还无法罗列出所有存在的非法标签。
