### ISSUE TITLE
修改历史无修改详情

### ISSUE THREAD

**Issue by Huarong** [lifei6671/mindoc#482]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

修改历史增加修改详情。

5. 当前遇到的是什么结果?

只有修改人和修改时间，但是看不到修改了什么。

**Comment by lifei6671** [comment]
点合并可以看到。

**Comment by Huarong** [comment]
看到了，藏得太深，不过可以使用。谢谢
