### ISSUE TITLE
都选择go了，为啥不支持sqlite，MySQL真不好布置设置。

### ISSUE THREAD

**Issue by xdeng** [lifei6671/mindoc#483]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by xdeng** [comment]
原来我提过。。。

**Comment by lifei6671** [comment]
你从哪知道的不支持sqlite？

**Comment by xdeng** [comment]
@lifei6671 简介里
