### ISSUE TITLE
建议增加类似于word中的文档结构视图

### ISSUE THREAD

**Issue by 54hechuan** [lifei6671/mindoc#484]
在一篇很长的分章节的文档中，文档结构图非常重要，建议增加类似于word中文档结构视图，typora 这个软件就支持，它也是基于 markdown 编辑器的，建议借签一下

**Comment by lifei6671** [comment]
你说的是这个功能吗？<https://www.iminho.me/wiki/docs/mindoc/mindoc-toc.md>
