### ISSUE TITLE
可不可以在文档或者文章有变动的时候发送邮件提醒

### ISSUE THREAD

**Issue by qwqeq** [lifei6671/mindoc#489]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0  mindoc_windows_amd64.7z

2. 你当前使用的是什么操作系统?
win10

3. 你是如何操作的？

4. 你期望得到什么结果?
在文章或文档有修改的时候发送邮件到指定浏览用户的邮箱，邮箱支持公司内网邮箱。谢谢。

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
这个需求太小众，有需求的话可以自己开发下。
