### ISSUE TITLE
关于数据迁移的问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [lifei6671/mindoc#490]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc2.0 Windows版本，下载的是mindoc_windows_amd64.7z这个文件

2. 你当前使用的是什么操作系统?
WinServer 2012 R2，数据库 mysql 5.6_44

3. 你是如何操作的？
安装配置完毕。按照[这个地址](https://www.iminho.me/wiki/docs/mindoc/mindoc-backup.md)进行数据库备份和迁移，然后复制之前项目根目录下upload文件夹下的图片，到winServer服务器上。

4. 你期望得到什么结果?
正常工作，用管理员用户登录后展示之前录入的文章和项目空间

5. 当前遇到的是什么结果?
和未进行数据迁移前展示的数据一样，但是我通过数据库查询显示我之前备份的文章都已经录入数据库了，之前的文件也都在

希望得到您的帮助和建议，谢谢！

**Comment by lifei6671** [comment]
看下控制台上的日志，是不是配置的数据库访问路径有问题？

**Comment by JamesLiAndroid** [comment]
看来是数据库名称的问题，我忘了配置迁移后的数据库名称！
