### ISSUE TITLE
首页“文章"为空问题

### ISSUE THREAD

**Issue by xdsnet** [lifei6671/mindoc#494]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64

2. 你当前使用的是什么操作系统?
debian8

3. 你是如何操作的？
匿名用户访问 首页中点击“文章”

4. 你期望得到什么结果?
显示所有非私有且已经发布的文章

5. 当前遇到的是什么结果?
结果为空

因为我定义了很多工作区，在工作区中分别有了很多文章了，但现在首页打开的“文章”栏目是空的，但搜索也能搜索到在非默认空间中的所有文章。

**Comment by lifei6671** [comment]
你说的是项目空间吗？

**Comment by xdsnet** [comment]
我是定义了很多项目空间，但首页 文章 栏目 那里是所有文章都为空，包括默认项目空间中的文章也没有显示出来。
此外一个信息是我采用数据库不是mysql，是sqlite3

**Comment by lifei6671** [comment]
我看都有啊，不知道你说的没有是什么意思呢？

**Comment by xdsnet** [comment]
如图，直接点击 “文章” 内容是空的， xds.duckdns.org 
![TIM截图20190620094039](https://user-images.githubusercontent.com/132992/59812190-a90dfe00-933f-11e9-95d0-1646bc14574b.png)

**Comment by lifei6671** [comment]
文章是文章，项目是项目，功能你没搞懂。
