### ISSUE TITLE
如何在编辑中添加本地图片时，生成图片地址报错，无响应

### ISSUE THREAD

**Issue by Grainfills** [lifei6671/mindoc#495]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0

2. 你当前使用的是什么操作系统?
chrome

3. 你是如何操作的？
进入页面+编辑+添加图片+添加本地图片

4. 你期望得到什么结果?
点击添加图片链接，生成图片地址，大佬的doc.iminho.me是可以的。cdn图片地址

5. 当前遇到的是什么结果?
点击无响应
```
Refused to display 'https://doc.jinxm.club/api/upload?identify=qianduanlean&guid=1561013604276' in a frame because it set 'X-Frame-Options' to 'deny'.
```
是不是因为我把静态资源放CDN了导致了这个问题，如何解决这个或者配置这个

**Comment by lifei6671** [comment]
上传文件是通过iframe实现的，你的服务器输出了`X-Frame-Options`头，标识不准在iframe中上传文件。
