### ISSUE TITLE
点击过快，浏览器会出现丢失IP问题

### ISSUE THREAD

**Issue by ghouman** [lifei6671/mindoc#499]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0

2. 你当前使用的是什么操作系统?
windows10

3. 你是如何操作的？
操作点击稍微快，出现丢失ip导致报错，如下图：
![image](https://user-images.githubusercontent.com/6038779/60097009-08776e00-9785-11e9-9a69-8933d6f17b13.png)
![image](https://user-images.githubusercontent.com/6038779/60097036-13ca9980-9785-11e9-9565-3e5245af5f96.png)
![image](https://user-images.githubusercontent.com/6038779/60097123-48d6ec00-9785-11e9-8601-835f9c4c5313.png)

4. 你期望得到什么结果?
点击过快不会出现错误

5. 当前遇到的是什么结果?
![image](https://user-images.githubusercontent.com/6038779/60097143-58563500-9785-11e9-8872-515cc3cdee4c.png)

**Comment by lifei6671** [comment]
不清楚你点的是哪个链接？

**Comment by ghouman** [comment]
就是随便点系统的链接，速度很快就会出现，我把  conf的配置文件中的baseurl增加了 就没有这个问题了，应该是默认从请求头中获取地址有BUG

#系统完整URL(http://doc.iminho.me),如果该项不设置，会从请求头中获取地址。
baseurl=http://base.isolarcloud.com:8181/  ##改成固定的就OK了

**Comment by lifei6671** [comment]
感觉你不是点的快，而且拖动鼠标了吧。

**Comment by ghouman** [comment]
baseurl=http://base.isolarcloud.com:8181/ ##改成固定的就OK了
