### ISSUE TITLE
导出的md格式，目录名称都是二进制的问题

### ISSUE THREAD

**Issue by eryajf** [lifei6671/mindoc#500]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
```
MinDoc current version =>  v2.0-beta.2
MinDoc last version =>  v2.0
```

2. 你当前使用的是什么操作系统?

```
CentOS Linux release 7.3.1611 (Core)
```

3. 你是如何操作的？

正常的导出项目，导出格式为md格式。

4. 你期望得到什么结果?

希望导出之后目录的名称还是保持原样。

5. 当前遇到的是什么结果?

目前导出之后，目录名称都变成了一堆二进制表述了，最近也在学习go语言，作为一名小白，弱弱的想问下，是不是在导出的时候，没有转换格式导致的呢。

![](https://raw.githubusercontent.com/eryajf/t/master/img/6A01462C-10DB-4fe5-A452-F185E6922903.png)

**Comment by lifei6671** [comment]
二进制表述是什么意思？你是文件名还是文件内容？

**Comment by eryajf** [comment]
可能我的表述有误，就是像截图显示的那样，文件的名称都是mindoc-1au什么的，内容倒是都正常的，不知道是否能让文件名称也正常

**Comment by lifei6671** [comment]
文件名实际上对应的是MinDoc的文档标识。如果你创建文档的时候没有指定标识，就会自动生成一个。

**Comment by eryajf** [comment]
哈哈，刚刚也发现这个问题了，那么是否有方法让文档导出为md格式的时候，显示文件名而不是文档标识呢

**Comment by lifei6671** [comment]
目前实现不了，因为文档的标题有可能不符合文件的命名规则。

**Comment by eryajf** [comment]
恩恩，好的
