### ISSUE TITLE
dep ensure报错

### ISSUE THREAD

**Issue by wangwanchao** [lifei6671/mindoc#503]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?
mac 10.13
go 1.12

3. 你是如何操作的？
dep ensure

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
`Solving failure: No versions of github.com/kardianos/service met constraints:
	v1.0.0: Could not introduce github.com/kardianos/service@v1.0.0, as it is not allowed by constraint master from project mindoc.
	master: unable to deduce repository and source type for "golang.org/x/sys/windows/registry": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sys/windows/registry?go-get=1": Get http://golang.org/x/sys/windows/registry?go-get=1: dial tcp 216.239.37.1:80: i/o timeout`

**Comment by lifei6671** [comment]
请先补充下golang的基础知识。

**Comment by wangwanchao** [comment]
> 请先补充下golang的基础知识。

不好意思，刚看到，具体到什么什么信息？版本号之外还要什么？

**Comment by pq1518110364** [comment]
你解决了吗

**Comment by wangwanchao** [comment]
后来就放弃了，当时只是想体验一下 @pq1518110364
