### ISSUE TITLE
 mindoc首页的qq群链接失效了，能否更新一下？

### ISSUE THREAD

**Issue by hqgaofeng** [lifei6671/mindoc#504]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

NA
2. 你当前使用的是什么操作系统?

NA
3. 你是如何操作的？

NA
4. 你期望得到什么结果?

NA
5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
不好意思，工作忙，QQ群解散了。
