### ISSUE TITLE
代码块如何显示完整

### ISSUE THREAD

**Issue by xiejiachen** [lifei6671/mindoc#507]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
amd64 version

2. 你当前使用的是什么操作系统?
windows server2012 最新版

3. 你是如何操作的？
输入代码块

4. 你期望得到什么结果?
显示完整代码

5. 当前遇到的是什么结果?

显示代码不完整，为右侧有滑动条，希望可以完整显示，不需要滑动

**Comment by lifei6671** [comment]
修改css样式，删掉高度。`.markdown-body .highlight pre, .markdown-body pre`
