### ISSUE TITLE
如何关闭验证码？

### ISSUE THREAD

**Issue by karlxu11** [lifei6671/mindoc#508]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

mindoc_windows_amd64    V2.0

2. 你当前使用的是什么操作系统?
WIN7

3. 你是如何操作的？
在 views\account\login.tpl下已经修改51行 为：{{if ne .ENABLED_CAPTCHA "true"}} 

4. 你期望得到什么结果?
不展示验证码，成功登录

5. 当前遇到的是什么结果?
没有展示验证码，但是无法登录，提示‘验证码不正确’

**Comment by lifei6671** [comment]
管理后台 -> 配置管理 -> 关闭验证码
