### ISSUE TITLE
OpenWrt 上面有没有法搞啊

### ISSUE THREAD

**Issue by libinanshu** [lifei6671/mindoc#509]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
OpenWrt轻量级Linux有这方面打算么

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?
适配？

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
golang语言跨平台支持。你可以自己编译下。
