### ISSUE TITLE
Safari 图片上传没有成功

### ISSUE THREAD

**Issue by iHTCboy** [lifei6671/mindoc#510]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?
macOS 10.14.5 (18F132)

3. 你是如何操作的？
点击图片上传，选择图片后，确认

4. 你期望得到什么结果?
图片上传后，图片地扯还是空

5. 当前遇到的是什么结果?
![image](https://user-images.githubusercontent.com/11418363/61504194-14b1bc80-aa0d-11e9-91d9-1a06c78d8c1c.png)

但是用谷歌浏览器，能正常显示图片地址，并填充：
![image](https://user-images.githubusercontent.com/11418363/61504245-47f44b80-aa0d-11e9-8f7e-b9a5cbf1252e.png)

谢谢~

**Comment by lifei6671** [comment]
你看看演示站能上传成功吗？我测试是正常的。

**Comment by iHTCboy** [comment]
@lifei6671 

大佬，我刚又用另一台mac试是可以！终于发现原因了，是因为我安装了JSONView-Safari: 

![image](https://user-images.githubusercontent.com/11418363/61504887-8ab72300-aa0f-11e9-9166-a24b411ec645.png)

这个插件如果不勾选，就可以上传图片了。

这个插件的地址：
- [JSONView - Safari Extensions Gallery](https://safari-extensions.apple.com/details/?id=com.dcrousso.jsonview-safari-Q5M4T22BE9)
- [dcrousso/JSONView-Safari: A Safari port of the JSONView extension](https://github.com/dcrousso/JSONView-Safari)

有劳大佬看看能不能知道根本原因，看看能不能解决啊。不能就算啦，我上传时，去掉勾选就好😄

感谢大佬速度回复~

**Comment by lifei6671** [comment]
我看了下，上传图片的脚本里面用到了浏览器内置对象`JSON`来解析json，这个插件会覆盖这个对象，导致脚本运行报错。

**Comment by iHTCboy** [comment]
@lifei6671  好的，感谢大佬！get~

**Comment by lifei6671** [comment]
我理解错了。真正的原因是，上传文件用到了`iframe`标签，这个标签的是上传文件后返回的`json`内容，这段内容用`pre`标签包裹，导致你这个插件识别成了需要格式化的内容，然后上传文件处理脚本拿到的数据不是json，而是这个扩展格式化后的内容了。

**Comment by iHTCboy** [comment]
@lifei6671 原来是这样，soga！感谢！❤️
