### ISSUE TITLE
请问支持文档间的跳转吗？

### ISSUE THREAD

**Issue by karlxu11** [lifei6671/mindoc#515]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64  2.0

2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？
在A文档中想创建链接可以跳转到B文档中

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
<https://www.iminho.me/wiki/docs/mindoc/mindoc-jump.md>

**Comment by karlxu11** [comment]
这个我之前有看过，这个是当前文档内的段落跳转。不是多个文档跳转吧

**Comment by lifei6671** [comment]
加上完整链接就行了。

**Comment by karlxu11** [comment]
果然可以了，谢谢大佬！
