### ISSUE TITLE
dockerfile构建镜像出错

### ISSUE THREAD

**Issue by AlexXuz** [lifei6671/mindoc#517]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0

2. 你当前使用的是什么操作系统?
linux centos7

3. 你是如何操作的？
docker build -f

4. 你期望得到什么结果?
成功构建镜像

5. 当前遇到的是什么结果?
![图片](https://user-images.githubusercontent.com/24284953/62198512-5864d880-b3b4-11e9-8f37-36ff41544047.png)

**Comment by lifei6671** [comment]
你是用的我提供的Dockerfile文件吗？感觉像是go的源码没恢复。

**Comment by AlexXuz** [comment]
是的，clone下来以后源码都没有动，直接build就报这个错误的

**Comment by AlexXuz** [comment]
> 
> 
> 你是用的我提供的Dockerfile文件吗？感觉像是go的源码没恢复。

是的，clone下来以后源码都没有动，直接build就报这个错误的

**Comment by lifei6671** [comment]
去国外的机器编译，国内可能因为某些原因被墙了一些包。

**Comment by AlexXuz** [comment]
> 
> 
> 去国外的机器编译，国内可能因为某些原因被墙了一些包。

是用香港服务器编译的哈，之前在本地golang.org老被墙，所以换的服务器

**Comment by lifei6671** [comment]
我一般是在阿里云提供的镜像编译服务编译的，没出现过你的这种问题。

**Comment by AlexXuz** [comment]
> 
> 
> 我一般是在阿里云提供的镜像编译服务编译的，没出现过你的这种问题。

我现在用releases版本倒是构建成功啦，但是有个问题啊，我容器rm之后重新启动数据会丢失，查看日志发现每次都会重新建表，这个是怎么回事呢？dockerfile的入口是用的master的start.sh

**Comment by lifei6671** [comment]
使用方面看看手册吧。

**Comment by AlexXuz** [comment]
找到问题了……按照手册传的环境变量，最后发现环境变量名改了，所以……

**Comment by lifei6671** [comment]
哦哦，你如果是想用master分支编译的话，需要将Dockerfile的基础镜像改成： `golang:1.12.7-alpine3.10`
