### ISSUE TITLE
配置CDN后查询用户角色错误，登陆模块瘫痪

### ISSUE THREAD

**Issue by Grainfills** [lifei6671/mindoc#519]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
配置腾讯云CDN，配置了源站，ng等调整了三天。命中率都访问都正常了。尝试了ng的缓存，cdn的缓存，以及不缓存策略。就是登陆这块报错。
`[E] [BookModel.go:936]  查询用户项目角色出错 -> book_id= 8  member_id= 3 <QuerySeter> no row found `
以及非法请求这个错误。

4. 你期望得到什么结果?
正常的登陆注册流程。

5. 当前遇到的是什么结果?
登陆成功到首页后状态没有改变，点击文章，状态变成以登陆。第二次登陆非法请求。token什么的也有传递，但是password字段的加密失败了。直接post的明文密码。

**Comment by Grainfills** [comment]
睡了一觉想明白了。已解决。麻烦了，我关闭一下。抱歉

**Comment by zszen** [comment]
> 睡了一觉想明白了。已解决。麻烦了，我关闭一下。抱歉

@systemctls 劳烦您公布一下解决方法，我这边也出现这个问题
![图片](https://user-images.githubusercontent.com/1890538/192186923-39d84ba3-13b4-486f-97b5-4a14b6d91dc8.png)
