### ISSUE TITLE
建议根据H1~H6自动生成“当前文档”的目录

### ISSUE THREAD

**Issue by efans007** [lifei6671/mindoc#524]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0

2. 你当前使用的是什么操作系统?
CentOS7.0

3. 你是如何操作的？
编写wiki，里面有H1~H6多级标题

4. 你期望得到什么结果?
期望在页面顶部自动生成层级目录，方便阅读

5. 当前遇到的是什么结果?
当前没有层级目录，内容较多时，不便于阅读

**Comment by cnspray** [comment]
[TOC]了解一下

**Comment by lifei6671** [comment]
[TOC] 
标签
