### ISSUE TITLE
倒入项目失败

### ISSUE THREAD

**Issue by innocencecaosm** [lifei6671/mindoc#525]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

mindoc_linux_amd64.zip 2.0的新版本
2. 你当前使用的是什么操作系统?

centos7
3. 你是如何操作的？

倒入项目 zip 文件包
4. 你期望得到什么结果?

希望导入项目的时候 能够灵活一些，导入office 以及支持md pdf 格式，导入项目很慢不成功
5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
只支持导入md文档，其他不支持。
