### ISSUE TITLE
centos7后台运行不成功

### ISSUE THREAD

**Issue by xiaoqiang** [lifei6671/mindoc#529]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64    linux最新版

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
./mindoc_linux_amd64 service install
systemctl enable mindocd.service

4. 你期望得到什么结果?
服务启动成功

5. 当前遇到的是什么结果?
systemctl status 系统中没有这个服务，页面也无法访问

**Comment by eryajf** [comment]
这个管理文件，需要自行创建一下，可以参考我这里整理的：[http://www.eryajf.net/2501.html](http://www.eryajf.net/2501.html)

**Comment by xiaoqiang** [comment]
> 这个管理文件，需要自行创建一下，可以参考我这里整理的：http://www.eryajf.net/2501.html

已经搞定了，谢谢
