### ISSUE TITLE
希望可以增加导出word文档

### ISSUE THREAD

**Issue by bliblimumu** [lifei6671/mindoc#53]

**Comment by bliblimumu** [comment]
作者可以加下吗？

**Comment by gdlaoqiang** [comment]
以前那个版本的有不知道为什么这个版本就删除了

**Comment by miaomiaoguoke** [comment]
支持，word的还好再编辑，希望没有pdf那种一个标题就一页的问题。

**Comment by lifei6671** [comment]
0.7版本已支持

**Comment by shanguanyunya** [comment]
你好，请问除了默认的演示项目可以导出外，新建的项目右上角没有下载按钮，无法导出。谢谢！
你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
v0.10.1  mindoc_linux_amd64.zip

你当前使用的是什么操作系统?
centos7.4 64bit

你是如何操作的？
按照calibre进行安装的，https://github.com/lifei6671/mindoc/wiki/%E5%9F%BA%E4%BA%8Ecalibre%E7%9A%84%E5%A4%9A%E6%A0%BC%E5%BC%8F%E5%AF%BC%E5%87%BA%E5%8A%9F%E8%83%BD%E9%85%8D%E7%BD%AE。测试了默认演示项目右上角下载各种格式导出都正常，但是后面新建的项目右上角没有下载按钮。
