### ISSUE TITLE
gocaptcha.NewCaptchaImage现在没有返回error，mindoc在open go mod的情况下编译失败。

### ISSUE THREAD

**Issue by hellodudu** [lifei6671/mindoc#530]
https://github.com/lifei6671/mindoc/blob/f1b6594c50db86e1d3e512e0546f2fb5fc3d880c/controllers/AccountController.go#L440-L445

# build error
➜  mindoc git:(master) ✗ go build main.go
github.com/lifei6671/mindoc/controllers
controllers/AccountController.go:440:20: assignment mismatch: 2 variables but gocaptcha.NewCaptchaImage returns 1 values

**Comment by lifei6671** [comment]
是版本问题。你用最新版本。

**Comment by hellodudu** [comment]
mindoc和gocaptcha都是master最新呢

**Comment by lifei6671** [comment]
最新版本应该没问题。你看看你的Gopkg.toml中的版本。应该不是最新的。

**Comment by hellodudu** [comment]
嗯嗯，看到gopkg里面取0.1.0版本的gocaptcha，NewCaptchaImage是返回两个值，go module默认拉取master的代码，多谢，关闭了。
