### ISSUE TITLE
支持压缩包文件（zip）等等其他文件上传

### ISSUE THREAD

**Issue by Mrzhuhanxin** [lifei6671/mindoc#539]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by Mrzhuhanxin** [comment]
当前使用的v2.0版本
Centos7系统
希望可以上传多种格式的文件

**Comment by wang19930902** [comment]
#上传文件的后缀,如果不限制后缀可以设置为 *
upload_file_ext=*

**Comment by Mrzhuhanxin** [comment]
可以了，谢谢
