### ISSUE TITLE
网页部分不会自适应，小屏幕电脑要拖

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#54]

**Comment by lifei6671** [comment]
不拖滚动条，你想怎么样？设计滚动条就是用来拖的。

**Comment by qetee** [comment]
@lifei6671  支持楼主，从产品易用角度考虑，网页呈现都不建议出现横向滚动条，除了比较特殊的；
作者在哪个比较流行的网站上见过横向滚动条？？？   设计滚动条就是用来拖的，我也是醉了；建议去了解下网页交互规范

**Comment by lifei6671** [comment]
@qetee 我不是做前端的，也不是做产品的，如果您对前端有比较深入的研究，可以帮忙改善项目的体验。
