### ISSUE TITLE
使用Markdown编辑器一直显示加载状态？

### ISSUE THREAD

**Issue by yidaoqingcheng** [lifei6671/mindoc#542]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0

2. 你当前使用的是什么操作系统?
centos7.5

3. 你是如何操作的？
宝塔面板安装的

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
使用markdown编辑，一直显示加载状态，无法加载出编辑器。使用html编辑器就正常。请问这是什么问题呢？

**Comment by lifei6671** [comment]
换个浏览器试试。
