### ISSUE TITLE
如何使子目录默认展开？

### ISSUE THREAD

**Issue by yidaoqingcheng** [lifei6671/mindoc#543]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.0

2. 你当前使用的是什么操作系统?
centos7.5

3. 你是如何操作的？

4. 你期望得到什么结果?
子目录默认展开

5. 当前遇到的是什么结果?
目前是子目录默认关闭，且手机端按钮不好点击，如果设置子目录默认展开？后台未发现有该功能

**Comment by lifei6671** [comment]
编辑文档的时候，在左侧文档上右键有设置。
