### ISSUE TITLE
文章作者头像请求failed

### ISSUE THREAD

**Issue by Grainfills** [lifei6671/mindoc#546]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新版本

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
之前域名由doc.jinxm.club转到了https://www.wccode.com/，其他都正常。

4. 你期望得到什么结果?
文章下的作者头像正常显示

5. 当前遇到的是什么结果?
类似这种文章下的 [链接](https://www.wccode.com/blog-15.html)

作者头像还是请求的之前的地址。检查了app配置没有问题，是哪里缓存了吗

**Comment by lifei6671** [comment]
没太懂你到底遇到了什么问题？
