### ISSUE TITLE
pdf导出文档排序问题

### ISSUE THREAD

**Issue by wienerxu** [lifei6671/mindoc#55]
controllers/document.go中的Export函数没有按parent_id和sort_order排序，导出的pdf文档顺序可能有问题。
可以在FindListByBookId(bookResult.BookId)函数orm时增加OrderBy进行排序。

**Comment by lifei6671** [comment]
是可能有问题还是已经发现问题了呢？ RecursiveFun 这个函数就是用来生成排序的。

**Comment by wienerxu** [comment]
没做过子文档排序的没有问题，子文档在编辑后排过序的生成pdf顺序不对。RecursiveFun只遍历没有排序。

**Comment by lifei6671** [comment]
哦哦，我明白了，下个版本优化下。

**Comment by iconan** [comment]
pdf导出后，文档顺序问题什么时候可以修复？
