### ISSUE TITLE
docker-compose mysql 报错 注册默认数据库失败

### ISSUE THREAD

**Issue by gerrard2030** [lifei6671/mindoc#551]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v2.0-beta.2
2. 你当前使用的是什么操作系统?
linux 7.6

3. 你是如何操作的？

docker-compose
4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
用docker-compose 
使用mysql，出现报错
mindoc    | [ORM]2019/10/25 03:26:52 register db Ping `default`, invalid DSN: did you forget to escape a param value?
mindoc    | 2019/10/25 03:26:52.397 [E] [command.go:57]  注册默认数据库失败-> register db Ping `default`, invalid DSN: did you forget to escape a param value?

**Comment by gerrard2030** [comment]
好吧， 问题解决了，  docker-compose 编排问题

**Comment by LiYouliang** [comment]
遇到同样的问题，请问这个环境变量配置哪里有问题吗？

    - MINDOC_DB_ADAPTER=mysql
    - MYSQL_PORT_3306_TCP_ADDR=*.*.*.*
    - MYSQL_PORT_3306_TCP_PORT=3306
    - MYSQL_INSTANCE_NAME=mindoc
    - MYSQL_USERNAME=xxx
    - MYSQL_PASSWORD=xxxxxxx
