### ISSUE TITLE
windows部署启动后，第一次无法登录

### ISSUE THREAD

**Issue by bhwebxu** [lifei6671/mindoc#561]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0 
mindoc_windows_amd64.7z
从https://github.com/lifei6671/mindoc/releases/download/v2.0/mindoc_windows_amd64.7z下载

2. 你当前使用的是什么操作系统?
windows server 2003
mysql-8.0.18-winx64
golang 最新

3. 你是如何操作的？
参考https://www.iminho.me/wiki/docs/mindoc/mindoc-windows.md安装完毕之后,
使用cmd 进入安装目录,运行 mindoc_windows_amd64.exe 
然后提示启动站点8181,使用admin试着login,然后就报错

4. 你期望得到什么结果?
能正常使用

5. 当前遇到的是什么结果?
![1](https://user-images.githubusercontent.com/1984499/70675727-f5217600-1cc4-11ea-980f-f876a463d0ac.png)
![2](https://user-images.githubusercontent.com/1984499/70675731-f652a300-1cc4-11ea-9a45-d18e6562293b.png)
![3](https://user-images.githubusercontent.com/1984499/70675732-f81c6680-1cc4-11ea-841b-a624b7956104.png)

**Comment by winye** [comment]
我也遇到了这个问题

**Comment by bhwebxu** [comment]
> 
> 
> 我也遇到了这个问题

已经解决了,这个一定要安装MySQL 8以下的数据库.文档上也没有说明.
安装低版本(<8)MySQL即可.
