### ISSUE TITLE
导入项目之后一片空白，编辑模式下正常

### ISSUE THREAD

**Issue by Jigsaw111** [lifei6671/mindoc#572]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64
2. 你当前使用的是什么操作系统?
windows server 2012
3. 你是如何操作的？
导入压缩文件
4. 你期望得到什么结果?
可阅读的文档
5. 当前遇到的是什么结果?
阅读模式下一片空白

**Comment by lifei6671** [comment]
需要手动发布，未发布的只能编辑不能看。
