### ISSUE TITLE
打开项目后是新开一个标签页而不是在原网页跳转

### ISSUE THREAD

**Issue by oicu** [lifei6671/mindoc#600]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0

2. 你当前使用的是什么操作系统?
Windows 10 LTSC 2019

3. 你是如何操作的？
首页，打开任意一个项目。

4. 你期望得到什么结果?
在原网页跳转，而不是新开一个页面。

5. 当前遇到的是什么结果?
新开一个项目的页面后，再点“首页”，一会就一堆标签栏，体验并不是很好。

**Comment by GaoIU** [comment]
你使用这个v2.0版本登录之后能进入首页吗？为什么我登录之后就直接异常了

**Comment by oicu** [comment]
> 你使用这个v2.0版本登录之后能进入首页吗？为什么我登录之后就直接异常了

我用的Windows版。目前至少还是能使用的。

**Comment by GaoIU** [comment]
我用的也是Windows版，数据库用的是mysql，登录之后直接就异常了，看了你们好几个人的留言，好像都能使用，就我出这问题了，尴尬

**Comment by oicu** [comment]
> 我用的也是Windows版，数据库用的是mysql，登录之后直接就异常了，看了你们好几个人的留言，好像都能使用，就我出这问题了，尴尬

我没用mysql，就默认的sqlite。

**Comment by dandycheung** [comment]
自己去 views/home/index.tpl 里把 target="_blank" 属性删除就可以了吧。作者按你的想法改掉之后，说不定会有其他人来创建新的 issue 要求每个项目在新标签页里打开呢。

**Comment by oicu** [comment]
> 自己去 views/home/index.tpl 里把 target="_blank" 属性删除就可以了吧。作者按你的想法改掉之后，说不定会有其他人来创建新的 issue 要求每个项目在新标签页里打开呢。

不懂开发哈，谅解一下，只是从用户体验角度提问题。我试试你的方法，谢谢。
