### ISSUE TITLE
mindoc项目文章编辑后看不到内容

### ISSUE THREAD

**Issue by heanbian** [lifei6671/mindoc#606]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64.exe

2. 你当前使用的是什么操作系统?
windows server 2019

3. 你是如何操作的？
新建项目，在项目中编辑文章，查看的时候 看不到内容，mindoc提供的演示版本也看到内容

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
点发布文章。也可以设置项目自动发布。

**Comment by heanbian** [comment]
谢谢您！现在已经正常使用。


------------------------------------------------------------------
发件人：Minho <notifications@github.com>
发送时间：2020年6月14日(星期日) 15:07
收件人：lifei6671/mindoc <mindoc@noreply.github.com>
抄　送：管理员 <heanbian@heanbian.com>; Author <author@noreply.github.com>
主　题：Re: [lifei6671/mindoc] mindoc项目文章编辑后看不到内容 (#606)

点发布文章。也可以设置项目自动发布。
