### ISSUE TITLE
文档发布之后内容为空白

### ISSUE THREAD

**Issue by 354476429** [lifei6671/mindoc#607]
1.你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
mindoc_linux_amd64 v1.0

2.你当前使用的是什么操作系统?
Ubuntu 5.4.0-6ubuntu1~16.04.10

3.你是如何操作的？
新建项目，在项目中编辑文章，编辑文章的时候可以看到编辑内容和预览内容,但点击发布之后,无法查看到发布内容

4.你期望得到什么结果?
期望可以正常查看到发布内容

5.当前遇到的是什么结果?
一开始使用的时候没有异常,但文档多了之后就出现这个问题

**Comment by 354476429** [comment]
一开始使用的时候没有异常,但文档多了之后就出现这个问题,查看mysql数据库发现md_documents.content是有内容的,但md_documents.release是空的,点击了发布也是空的,应该是在发布时出现了问题,导致查看不到发布内容

**Comment by 354476429** [comment]
我本地运行源码读取相同的数据库数据发现没有出现这个问题,发布文档之后是可以正常展示的,服务器上运行的是最新的release v2.0的包,会出现发布之后文档还是空白,尝试了下本地用源码编译的包放在服务器上运行,发现就没有问题了.所以我这边最终的解决办法是用源码本地编译之后替换掉服务器上的release包.

**Comment by GaoIU** [comment]
大佬用的也是mysql吗，我是在Win10上面安装的，搭建好了之后，在点击登录之后就会弹出这个异常：Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'member ON rel1.member_id = member.member_id
WHERE book.privately_owned = 0 or re' at line 9

**Comment by GaoIU** [comment]
我用的是mysql_8.0.17

**Comment by 354476429** [comment]
> 我用的是mysql_8.0.17

我用的mysql5.6,你的数据库里面有没有创建好对应的表和字段呢

**Comment by heirychen** [comment]
要发布，可以设置自动发布
