### ISSUE TITLE
Ubuntu 系统下，通过supervisor 守护进程部署mindoc

### ISSUE THREAD

**Issue by dcdebug** [lifei6671/mindoc#612]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

linux_amd64 
2. 你当前使用的是什么操作系统?
Ubuntu

3. 你是如何操作的？
点击“忘记密码”，写入邮件，验证码,点击发送，提示“邮件已经发送”的滋养

4. 你期望得到什么结果?
能收到邮件

5. 当前遇到的是什么结果?
在log中出现
发送邮件失败：454 Transient reject by behaviour spam at Rcpt State(Connection IP address:113.110.224.169)ANTISPAM_BAT[01201311R1868S553012151f, e02c03291]: too frequently sendingCONTINUE

**Comment by lifei6671** [comment]
这是你邮箱服务器限制了吧，系程序无关。

**Comment by dcdebug** [comment]
> 这是你邮箱服务器限制了吧，系程序无关。
后来我排查限制了一下，跟我的邮箱没有关系，我的这个邮箱在别的平台上是可以正常使用的...（比如Mantis，gitlab)
