### ISSUE TITLE
项目下文档数量超过1000之后发布不生效

### ISSUE THREAD

**Issue by hu-haibo** [lifei6671/mindoc#630]
## 当前的问题
单个项目文档数超过1000之后编辑模式下可以看到内容，手动点击发布按钮看不到发布的内容。请问是不是有1000个文档的限制。
但是如果项目开启了自动发布的话，编辑完毕保存之后可以看到发布的内容。

## 当前运行环境
mindoc版本： v2.0（mindoc_linux_amd64）
系统版本： centos7

**Comment by cshirong** [comment]
同问，该在哪里更改呢？

**Comment by DestinyCong** [comment]
> 同问，该在哪里更改呢？

在项目的设置里面
![image](https://github.com/mindoc-org/mindoc/assets/23352279/2d11cdee-fb92-497e-9a40-8079025d2521)
