### ISSUE TITLE
上传附件失败

### ISSUE THREAD

**Issue by thewon86** [lifei6671/mindoc#646]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v2.0

2. 你当前使用的是什么操作系统?
Fedora 33.20210104.3.1 (CoreOS)

3. 你是如何操作的？
编辑文章，上传附件

4. 你期望得到什么结果?
上传任何后缀格式文件附件

5. 当前遇到的是什么结果?
相同的压缩包格式，有些提示“上传失败 http”，有些提示“不允许的文件类型”
另外，附件文件大小限制多少？

**Comment by gsw945** [comment]
**4**和**5**提到的内容，请参见仓库下的示例配置文件`conf/app.conf.example`

**Comment by gsw945** [comment]
配置文件有注释说明，或者也可以参照如下示例:
- 满足**4**的配置: `upload_file_ext=*`，值为`*`即不限制
-  满足**5**的配置: `upload_file_size=999GB`，默认为`10MB`，所以可以设置为一个很大(几乎不太可能)的值

**Comment by thewon86** [comment]
谢谢，我可能同时提出了多个问题，文件类型和文件大小通过配置解决了。
