### ISSUE TITLE
项目运行一段时间后不能访问了

### ISSUE THREAD

**Issue by billybi** [lifei6671/mindoc#71]
windowd上项目运行一段时间后就不能访问了，必须重新启动项目才行。。。。

**Comment by lifei6671** [comment]
不能访问具体是什么情况？能详细描述下吗。请看下是否存在错误日志。

**Comment by billybi** [comment]
请求一直没有响应

**Comment by lifei6671** [comment]
看下错误日志吧。提供下具体的配置信息和运行平台信息。

**Comment by billybi** [comment]
没有错误日志；
windows 10
go1.8.3

**Comment by lifei6671** [comment]
@billybi 你是自己编译的吗？
或者你以服务的形式运行试试。

**Comment by billybi** [comment]
下载的编译好的程序；我试试以服务形式运行

**Comment by passionchenjianye** [comment]
是存在这个问题，无论是编译好的程序还是自己编译的程序都会过段时间就会自己停止并访问不了，服务的形式没有试过。

**Comment by billybi** [comment]
以服务形式运行好像没这个问题了
