### ISSUE TITLE
main.go:33: cannot use d (type *daemon.Daemon)错误

### ISSUE THREAD

**Issue by 361way** [lifei6671/mindoc#73]
[root@localhost godoc]# go build -ldflags "-w"
# github.com/godoc
./main.go:33: cannot use d (type *daemon.Daemon) as type "github.com/godoc/vendor/github.com/kardianos/service".Interface in argument to "github.com/godoc/vendor/github.com/kardianos/service".New:
        *daemon.Daemon does not implement "github.com/godoc/vendor/github.com/kardianos/service".Interface (wrong type for Start method)
                have Start("github.com/lifei6671/godoc/vendor/github.com/kardianos/service".Service) error
                want Start("github.com/godoc/vendor/github.com/kardianos/service".Service) error
./main.go:33: cannot use d.Config() (type *"github.com/lifei6671/godoc/vendor/github.com/kardianos/service".Config) as type *"github.com/godoc/vendor/github.com/kardianos/service".Config in argument to "github.com/godoc/vendor/github.com/kardianos/service".New
You have new mail in /var/spool/mail/root
编译环境如下：
[root@localhost godoc]# go version
go version go1.8 linux/amd64
[root@localhost godoc]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

**Comment by lifei6671** [comment]
glide 包管理工具恢复下包。
