### ISSUE TITLE
编辑模式中点击返回浏览器上一页页面显示json数据

### ISSUE THREAD

**Issue by billybi** [lifei6671/mindoc#76]
在chorme浏览器中，查看项目，进入项目后点击任意一个文档，再从此页面进入项目编辑模式，此时点击浏览器中返回上一页按钮，页面显示的是json数据；

查看项目，点击项目的"空白文档"这个文档，在点击页面右上角的“项目”——> "返回编辑"，进入编辑模式后在点击浏览器中返回上一页，页面就显示的如下的数据：
{"data":{"doc_title":"空白文档","body":"","title":"空白文档 - Powered by MinDoc"},"errcode":0,"message":"ok"}

chrome版本：
版本 59.0.3071.86（正式版本） （64 位）

**Comment by lifei6671** [comment]
因为页面是异步加载的，异步加载的文件后退确实有这个问题，暂时没找到好的方法解决。

**Comment by billybi** [comment]
好像只有chrome有这个问题，firefox中就没有，而且在chrome中打开调试模式禁用浏览器缓存也没有这个问题。
