### ISSUE TITLE
希望能增加添加积分功能

### ISSUE THREAD

**Issue by passionchenjianye** [lifei6671/mindoc#80]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindco_linux_amd64 0.5.1

2. 你当前使用的是什么操作系统?
centos

3. 你是如何操作的？
下载mindoc_linux_amd64.zip文件，解压运行

4. 你期望得到什么结果?
a, 希望有积分的功能，例如发布一篇文章就可以获得积分这样的功能
b, 希望新增用go编译并打包的步骤
c, 希望可以发布个公开的docker镜像
5. 当前遇到的是什么结果?
a, 未能编译源码
b, 通过Dockfile去翻墙编译镜像，但是到第6步卡着不动了，也不会报错

**Comment by feiyan35488** [comment]
积分功能自己开发吧，这不是核心功能

**Comment by lifei6671** [comment]
@passionchenjianye 本地编译请参考 [MinDoc 本地编译](https://github.com/lifei6671/mindoc/wiki/MinDoc-%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85)。

积分功能不是该项目的核心功能，需要您自己二次开发。

**Comment by passionchenjianye** [comment]
你好，我按照你的方法配置了go环境，然后执行./mindoc install的时候数据表是创建成功，但是会报错。请看图
![a715c1c8-fc41-442e-a75d-afadf387eac4](https://user-images.githubusercontent.com/4251642/27209018-d4809342-527b-11e7-88e1-ac36308480b7.png)

**Comment by lifei6671** [comment]
如果是MySQL数据库，编码必须是utf8mb4
