### ISSUE TITLE
希望在创建项目后有创建目录的功能，文档放到目录下

### ISSUE THREAD

**Issue by liuyunfeng2017** [lifei6671/mindoc#82]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v0.5.1

2. 你当前使用的是什么操作系统?

Ubuntu
3. 你是如何操作的？

创建项目-->新增文档
4. 你期望得到什么结果?

希望创建项目后在创建文档前还可以创建目录，如果系统比较庞大那文档会很多，如果有个目录管控下会清爽很多。
5. 当前遇到的是什么结果?
当前创建项目后直接创建文档

**Comment by lifei6671** [comment]
MinDoc中文档就是目录，目录就是文档，所有数据都储存在数据库，没有对应的物理文件。

**Comment by liuyunfeng2017** [comment]
@lifei6671 系统中没有添加目录的的功能，我看表结构中有parent_id，我手动添加一个文档，parent_id为0，然后再建一个文档parent_id为之前建的文档ID就能实现目录功能，但是系统添加文档的时候没有选择放到哪个文档下的选项，建议在添加文档的时候加一个属性，用于选择上级文档，这样就完美了

**Comment by lifei6671** [comment]
你没明白我的意思，MinDoc 中没有目录的概念，只有上下级文档，你说的这个问题应该是不知道可以右键菜单建立子文档吧？

**Comment by liuyunfeng2017** [comment]
@lifei6671 哦，我现在才发现，谢谢分享
