### ISSUE TITLE
如何自定义模板

### ISSUE THREAD

**Issue by tianfuchao** [lifei6671/mindoc#86]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
windows 版 0.5.1版

2. 你当前使用的是什么操作系统?
windows

3. 你是如何操作的？
在编辑的知识库的时候，选择模板想自定义一些模板，方便内部人员使用。

4. 你期望得到什么结果?
模板可自定义 后台可管理

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
暂时还不支持自定义模板，系统内置了三种模板，您可以直接替换掉对应的模板文件，默认的模板文件在：mindoc/views/document/ 下的以template开头的三个文件。
