### ISSUE TITLE
编辑文档时，保存按钮不可以用

### ISSUE THREAD

**Issue by gao88** [lifei6671/mindoc#88]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by gao88** [comment]
是在IE浏览器的问题

**Comment by lifei6671** [comment]
能详细描述下你遇到的问题吗？IE浏览器也有好几个版本。
