### ISSUE TITLE
docker+nginx下PDF导出异常

### ISSUE THREAD

**Issue by wolcengit** [lifei6671/mindoc#89]
docker+nginx环境下PDF导出，由于生成的中间html中静态资源使用了访问的地址即域名，导致在容器内部的wkhtmltopdf无法访问静态资源，修改controller/documents.go中的RecursiveFun函数，把里面的c.BaseUrl()引用修改为 baseurl := "http://127.0.0.1:" + beego.AppConfig.String("httpport") 后，正常

**Comment by lifei6671** [comment]
正常情况下，容器内部应该可以访问容器外的链接吧？

**Comment by zhangfisher** [comment]
正常情况下，容器使用桥接网络，内部不能访问宿主IP，因此转PDF会出错。
