### ISSUE TITLE
win7下安装不成功

### ISSUE THREAD

**Issue by alicance** [lifei6671/mindoc#9]
C:\Users\huangzuqiang\Desktop\godoc>.\godoc_windows_amd64.exe
MinDoc version => 0.1.2
build time => Fri May  5 12:00:02 UTC 2017
start directory => .\godoc_windows_amd64.exe
go version go1.8.1 linux/amd64
[ORM]2017/05/08 16:39:43 register db Ping `default`, open /usr/local/go\lib\time
\zoneinfo.zip: The system cannot find the path specified.
must have one register DataBase alias named `default`

**Comment by lifei6671** [comment]
试试v0.1.3中能执行吗？

**Comment by alicfeng** [comment]
还是不行，一样的错误

**Comment by lifei6671** [comment]
你确定配置app.conf了吗？我同事在win7上运行成功了。

**Comment by lifei6671** [comment]
如果你的服务器上没有安装golang程序请手动设置一个环境变量如下：键名为 ZONEINFO，值为MinDoc程序所在路径。
