### ISSUE TITLE
支持5.1.73版本的Mysql数据库吗？

### ISSUE THREAD

**Issue by shanghaif** [lifei6671/mindoc#90]
mysql> CREATE DATABASE mindoc_db  DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
ERROR 1115 (42000): Unknown character set: 'utf8mb4'
我的mysql版本是5.1.73，我不想升级数据库到5.5，想继续使用5.1版本的mysql，能否使用其他的字符集呢？

**Comment by lifei6671** [comment]
你需要自己编译，编码格式是在源码里面写死的。
如果不选择utf8mb4的话，一些emoji标签无法储存。
