### ISSUE TITLE
和SmartWiki是否数据库一样

### ISSUE THREAD

**Issue by qzc77** [lifei6671/mindoc#91]
部署了一套mindoc，初始化了一个项目，go没接触过，php还可以，想换成你做的SmartWiki，是否数据库都一样？

**Comment by lifei6671** [comment]
这是两个项目，教程肯定不一样的。SmartWiki的你参考 [https://wiki.iminho.me/show/1](https://wiki.iminho.me)

**Comment by henrypfhu** [comment]
SmartWiki老系统的数据能迁移到新的MinDoc环境吗？如何去迁移？

**Comment by lifei6671** [comment]
@henrypfhu 无法自动迁移。
