### ISSUE TITLE
只有把项目变成公共的才有导出选项

### ISSUE THREAD

**Issue by hollydragon** [lifei6671/mindoc#92]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.5.1

2. 你当前使用的是什么操作系统?
centos linux

3. 你是如何操作的？
添加私有项目，若干文档，尝试导出文档

4. 你期望得到什么结果?
可以导出pdf文档

5. 当前遇到的是什么结果?
**没有导出pdf选项，只有把项目变成公共的才会出现导出选项。**

**Comment by lifei6671** [comment]
因为考虑到私有项目一般是不公开的，导出后可以随意分享，就无法保证不公开了。所以，私有项目没有添加分享和导出功能。

**Comment by hollydragon** [comment]
好的 谢谢 明白了
