### ISSUE TITLE
请问与ShowDoc比有何优势？

### ISSUE THREAD

**Issue by ejzhang** [lifei6671/mindoc#93]
请问与ShowDoc（[http://blog.star7th.com/2015/11/1816.html](http://blog.star7th.com/2015/11/1816.html)）比有何优势？谢谢！
Github：[https://github.com/star7th/showdoc](https://github.com/star7th/showdoc)

**Comment by lifei6671** [comment]
这个我不好说，你自己体验比较下吧：[http://doc.iminho.me](http://doc.iminho.me)

**Comment by venliong** [comment]
* go语言编写(对于喜欢go的人是优点，对于不会go的人是缺点)
* 部署简单，支持所有go支持的平台
* 得益于go的编译、静态、强类型，所以性能很好
* 这个项目较新，好多功能还待完善，bug也不少
* 目前只有一个人在开发，受限投入精力，所以进度会较慢
* 如果你像我一样可以自己修改代码，这个mindoc就只有优点了
* 可以预见go将越来越普及，所以mindoc的代码值得花时间去了解

**Comment by ywz978020607** [comment]
> 请问与ShowDoc（http://blog.star7th.com/2015/11/1816.html）比有何优势？谢谢！ Github：https://github.com/star7th/showdoc

showdoc不支持在线流程图设计，mindoc这个依赖的draw.io，可以走tomcat本地化部署，功能比较丰富
