### ISSUE TITLE
分页pager处理问题

### ISSUE THREAD

**Issue by wienerxu** [lifei6671/mindoc#96]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.5,0.6

2. 你当前使用的是什么操作系统?
win64，linux64

3. 你是如何操作的？
管理员查看附件，翻页显示。

4. 你期望得到什么结果?
页面底部页签显示正确。

5. 当前遇到的是什么结果?
当附件较多时，会有较多分页，大于10页以后，分页栏显示异常。pager.go的fun3和fun4函数部分a标签缺少&lt;li&gt;标签，用于翻页的a...标签没有链接。其他分页处理的地方应该也同样有问题。

**Comment by lifei6671** [comment]
哦哦，我也发现这个问题了，忘了修复了。。

**Comment by lifei6671** [comment]
0.7版本已修复
