### ISSUE TITLE
mkdown新标签打开

### ISSUE THREAD

**Issue by xvipservice** [lifei6671/mindoc#97]
我使用最新docker版安装的
在使用mkdown作为编辑器的时候，用新标签打开url不知该如何操作。

还有概要能也用mkdown编辑吗，或者可以使某个页成为首页？

**Comment by lifei6671** [comment]
不清楚你说的是什么意思？

**Comment by xvipservice** [comment]
mkdown ，超链接，在先标签中打开。现在都是在本页打开的。

**Comment by xvipservice** [comment]
默认点一个项目进去查看的时候显示的是简介，简介能否也使用mkdonw编辑，或者我可以自己指定第一个显示的页面。

**Comment by lifei6671** [comment]
1、Markdown语法本身不支持新标签打开。
2、最新版本简介已经支持Markdown语法。
