### ISSUE TITLE
SmartWiki和godoc的导出是不是不一样？

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/mindoc#98]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新版

2. 你当前使用的是什么操作系统?
win

3. 你是如何操作的？
导出问题，之前导出文件在smartwiki的时候好像是导出word现在godoc导出是PDF。而且没之前方便

4. 你期望得到什么结果?
建议优化之前smartwiki一样增加导出word和pdf格式。希望增加导入office文件

5. 当前遇到的是什么结果?
导出的时候经常出错。很不方便。

**Comment by lifei6671** [comment]
是两个系统，功能肯定不一样。

**Comment by gdlaoqiang** [comment]
后续会增加office导出导入不？
