### ISSUE TITLE
从release中下载的 mindoc_linux_amd64_0.6在运行时提示缺少glibc_2.6

### ISSUE THREAD

**Issue by feiyan35488** [lifei6671/mindoc#99]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64 0.6

2. 你当前使用的是什么操作系统?
centos 6.8 64

3. 你是如何操作的？
从release中下载0.6版本后，直接运行

4. 你期望得到什么结果?
正常运行， 希望使用静态打包，这样就可以避免出现glibc问题

5. 当前遇到的是什么结果?
运行时提示缺少glibc_2.6

**Comment by lifei6671** [comment]
glibc是Linux平台的基础组件，请更新你本地的组件。
